### DISCUSSION TITLE
web search using searxng: No search query generated

### DISCUSSION THREAD

**Discussion by water2004** [open-webui/open-webui#10027] [General]
# Bug Report

## Installation Method

I install open-webui using docker without ollama
```sh
docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main
```

And then install searxng using docker compose, `docker-compose.yml` is shown as below
```yml
version: "3.7"

services:
  redis:
    container_name: redis
    image: docker.1ms.run/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.1ms.run/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:

volumes:
  caddy-data:
  caddy-config:
  valkey-data2:
```

`settings.yml`
```yml
# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings:
  engines:
    keep_only:
      - bing
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "***"  # change this!
  limiter: false  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
search:
  formats:
    - json
engines:
  - name: bing
    disabled: false
```
 admin panel settings:

![Image](https://github.com/user-attachments/assets/7f0e0dfd-b894-48c6-b0aa-211b1eedcde8)

## Environment

- **Open WebUI Version:** latest
- **Ollama (if applicable):** not installed

- **Operating System:** host: ubuntu22.04
- **Browser (if applicable):** latest edge on Windows10

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [x ] I have included the Docker container logs.
- [x ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Behavior:

Firstly, it comes out "Error searching "

![Image](https://github.com/user-attachments/assets/cbb01c22-be7f-49a1-9dbc-e6e5ca3d6e09)

the logs show that the query string is empty
```sh
Traceback (most recent call last):
  File "/app/backend/open_webui/utils/middleware.py", line 340, in chat_web_search_handler
    results = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/utils/middleware.py", line 342, in <lambda>
    lambda: process_web_search(
            ^^^^^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/routers/retrieval.py", line 1324, in process_web_search
    raise HTTPException(
fastapi.exceptions.HTTPException: 400: 400 Client Error: BAD REQUEST for url: http://172.17.0.1:8080/search?q=&q=&format=json&pageno=1&safesearch=1&language=en-US&time_range=&categories=&theme=simple&image_proxy=0
```

log of searxng:
```sh
2025-02-14 10:24:12,076 WARNING:searx.engines.bing: ErrorContext('searx/search/processors/online.py', 125, 'count_error(', None, '1 redirects, maximum: 0', ('200', 'OK', 'cn.bing.com')) True
```

after several tries, it comes out "No search query generated", and there are no logs from open-webui or searxng

![Image](https://github.com/user-attachments/assets/d646eb51-b088-4551-a32f-d5819842d23b)

**Comment by water2004** [comment]
searxng works well, I can get the result json file by browser
url: `***:8080/search?q=weather&format=json`
```json
{
    "query": "weather",
    "number_of_results": 967000,
    "results": [
        {
            "url": "https://weather.com/zh-CN/weather/tenday/l/Wuzhong+District+Jiangsu?canonicalCityId=0762a5370890acd0ad64a8a8ac38a34a9804847a9eecf1e8d33f2cc4bfdbb2d5",
            "title": "吴中区, 江苏省 10 天天气预报 - The Weather Channel",
            "content": "2024年5月10日 · 准备好获悉最精确的吴中区, 江苏省 10 天预报，包括最高温度、最低温度和降水几率 - 尽在 The Weather Channel 和 Weather.com 您的隐私 为了个性化产品 ...",
            "engine": "bing",
            "template": "default.html",
            "parsed_url": [
                "https",
                "weather.com",
                "/zh-CN/weather/tenday/l/Wuzhong+District+Jiangsu",
                "",
                "canonicalCityId=0762a5370890acd0ad64a8a8ac38a34a9804847a9eecf1e8d33f2cc4bfdbb2d5",
                ""
            ],
            "engines": [
                "bing"
            ],
            "positions": [
                1
            ],
            "score": 1,
            "category": "general"
       ...
}
```

**Comment by Mavyre** [comment]
This happens when the reponse generated by the LLM isn't correctly formatted as required by the web search (should be an array of queries). This error depends on the model used and its ability to respect its system prompt.

**Comment by technofox01** [comment]
> This happens when the reponse generated by the LLM isn't correctly formatted as required by the web search (should be an array of queries). This error depends on the model used and its ability to respect its system prompt.

I am having this exact issue and continue to get this error message (even though it will show that it received three search results):

SyntaxError: The string did not match the expected pattern.

I had no issues until after 5.9. I have no idea what go broken but it is definitely on OpenWebUI’s side and not Searxng because I have tested the API outside of OpenWebUI without issue.

**Comment by IndigoFloyd** [comment]
Also here. However, I could not confirm whether SearXNG or Open WebUI goes wrong. If I run `http://searxng:8080/search?q=hello&format=json`, it returns:
```
{
  "query": "hello",
  "number_of_results": 0,
  "results": [
    {
      "title": "HELLO | English meaning - Cambridge Dictionary",
      "url": "https://dictionary.cambridge.org/dictionary/english/hello",
      "content": "Learn the meaning and usage of the word hello in English, with synonyms, pronunciation, and translations. Find out how to say hello in different situations, such as greeting someone, answering the phone, or attracting attention.",
      "engine": "duckduckgo",
      "template": "default.html",
      "parsed_url": [
        "https",
        "dictionary.cambridge.org",
        "/dictionary/english/hello",
        "",
        "",
        ""
      ],
...
```
It's weird because there are exactly some results while `number_of_results` is `0`. But it seems not to be a fatal bug as [https://github.com/searxng/searxng/issues/2457](url) just discussed.
My Open WebUI and SearXNG docker instances run on WSL2. Expecting for any helpful fixes or anwsers.

**Reply by cy-6359** [reply]
Has it been resolved? I also encountered the same problem 😅

**Reply by IndigoFloyd** [reply]
不行，试了下边大哥的方法还是一样搜不到

**Comment by jackiefast** [comment]
i have found a solution for it。
the search url of searxng should be set for "http://your-ip:your-port/search?disabled_engines=&enabled_engines=bing__general"

**Reply by technofox01** [reply]
> http://your-ip:your-port/search?disabled_engines=&enabled_engines=bing__general

Well I will be a bare ass monkey's uncle. I get the same Syntax error message but it actually still provided and explained the search results with a test query asking about the best cars to get in 2024:

According to MotorTrend's latest news coverage [MotorTrendMotorTrendNewsReviewsBuyer's GuideVideosMagazinesThe FutureEvent CoverageAsk MOTORTRENDBeta ](https://www.motortrend.com/news/2024/08/electric-suv-news-vehicles-review-motor-trend-pickings-plugs-gasoline-economy-covid-21-still-new-electric-hybrid-and-fuel-cell-vehicle/), some of the best electric vehicles in 2024 include:
 Audi e-tron GT
 Dodge Durango Plug-in Hybrid
 Ford Mustang Mach-E
 Hyundai Ioniq 5
 Jaguar I-PACE
 Please note that this is not an exhaustive list, and new models may be introduced later in the year. For more information on specific EV models and their features, you can visit MotorTrend's website or consult with automotive experts.
If you have any further questions or need clarification, feel free to ask!

SyntaxError: The string did not match the expected pattern.

1
https://www.motortrend.com/features/every-electric-car-you-can-buy/

2
https://www.consumerreports.org/cars/hybrids-evs/hot-ne

**Reply by water2004** [reply]
it can't work either QwQ, here is the log
```sh
Traceback (most recent call last):
  File "/app/backend/open_webui/routers/retrieval.py", line 1318, in process_web_search
    web_results = search_web(
                  ^^^^^^^^^^^
  File "/app/backend/open_webui/routers/retrieval.py", line 1152, in search_web
    return search_searxng(
           ^^^^^^^^^^^^^^^
  File "/app/backend/open_webui/retrieval/web/searxng.py", line 79, in search_searxng
    response.raise_for_status()  # Raise an exception for HTTP errors.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: http://172.17.0.1:8080/search?disabled_engines=&enabled_engines=bing__general&q=&format=json&pageno=1&safesearch=1&language=en-US&time_range=&categories=&theme=simple&image_proxy=0
```

**Comment by water2004** [comment]
I know why! I should choose a model here!
![image](https://github.com/user-attachments/assets/e3f4c7e6-2674-4bd2-943d-d95ab16548fd)

It works now
![image](https://github.com/user-attachments/assets/5ef22904-b64b-4522-bf73-acd5446a1ca3)

**Reply by IndigoFloyd** [reply]
试了下deepseek-r1和qwen2.5还是报错，按理说默认“当前模型”应该会和前者保持一致呀，实在是不知道哪里出了问题😭

**Reply by technofox01** [reply]
> 试了下deepseek-r1和qwen2.5还是报错，按理说默认“当前模型”应该会和前者保持一致呀，实在是不知道哪里出了问题😭

Try using this in your web search settings:

http://localhost:8080/search?disabled_engines=&enabled_engines=bing__general

Edit:

I tried your settings, took me a bit figure out what menu you used because I was not able to translate your screenshot to English (I only know English, Spanish/Latin, and some German). Try putting it back to Current / Current for both model settings and then restart both OpenWebUI and Ollama. Relogin and try to see if it works now, you may still get a Syntax error initially but it will present and summarize the results.

**Reply by IndigoFloyd** [reply]
> > 试了下deepseek-r1和qwen2.5还是报错，按理说默认“当前模型”应该会和前者保持一致呀，实在是不知道哪里出了问题😭
> 
> Try using this in your web search settings:
> 
> http://localhost:8080/search?disabled_engines=&enabled_engines=bing__general
> 
> Edit:
> 
> I tried your settings, took me a bit figure out what menu you used because I was not able to translate your screenshot to English (I only know English, Spanish/Latin, and some German). Try putting it back to Current / Current for both model settings and then restart both OpenWebUI and Ollama. Relogin and try to see if it works now, you may still get a Syntax error initially but it will present and summarize the results.

Thank you so much for your warm reply. I deploy my system with docker compose file as follows:
```
services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    # I have modified this settings.yml to append json under format.
    environment:
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - .env
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  open-webui:
      image: ghcr.io/open-webui/open-webui:main
      container_name: open-webui
      ports:
        - "3000:8080"
      environment:
        - OLLAMA_BASE_URL=http://ollama:11434
      volumes:
        - /home/IndigoFloyd/open-webui:/app/backend/data
      restart: always
```
And my settings are:
![image](https://github.com/user-attachments/assets/0c62950b-9145-46bc-b322-ef340cf568d7)
and 
![image](https://github.com/user-attachments/assets/96ea0196-bc54-462b-994f-7906a8c3c8be)
Unfortunately it doens't work.
![image](https://github.com/user-attachments/assets/a2912c9e-130e-45db-8874-05a88979174f)

May you provide more suggestions plaese🥰?
