### DISCUSSION TITLE
Vertex AI API key refresh

### DISCUSSION THREAD

**Discussion by aryzle** [open-webui/open-webui#10030] [Ideas]
# Feature Request

**Is your feature request related to a problem? Please describe.**
When using Google Vertex AI, the API key expires every 1-12 hours (1 by default). Currently there's no way to automatically refresh the key, so it has to be done manually through the admin UI or via an API request to the `/openai/config/update` endpoint.

**Describe the solution you'd like**
https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-vertex-using-openai-library#refresh_your_credentials
There is an example here of refreshing creds automatically for google APIs. If there's a way to designate that we're using Vertex AI, then the app could refresh the token when it expires.

**Describe alternatives you've considered**
Currently you can either update the key manually in the ui or through the `/openai/config/update` endpoint. I've automated this by running a cron that updated the key every 55m.
```
TOKEN=$(gcloud auth application-default print-access-token)

curl -X POST "<openwebui-URL>/openai/config/update" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer <openwebui API KEY>" \
    -d "{
        \"ENABLE_OPENAI_API\": true,
        \"OPENAI_API_BASE_URLS\": [\"https://<REGION>-aiplatform.googleapis.com/v1beta1/projects/<PROJECTID>/locations/<REGION>/endpoints/openapi\"],
        \"OPENAI_API_KEYS\": [\"$TOKEN\"],
        \"OPENAI_API_CONFIGS\": {
            \"0\": {
                \"enable\": true,
                \"model_ids\": [\"google/gemini-1.5-flash\", \"google/gemini-2.0-flash-exp\"]
            }
        }
    }"

```

**Context**
This would likely be helpful for other APIs as well, not just Vertex AI

**Comment by ei-grad** [comment]
Initially, I found it a bit unexpected that this was moved to Discussions, but after thinking it over I came to agree that the idea makes sense: using a sidecar to patch the `/config/update` endpoint with a refreshed token—or a proxy container implementing this logic—is a much cleaner solution than introducing Vertex AI‑specific workarounds into the open‑webui codebase.

Starting with the fact that the gcloud CLI isn't exactly trivial to install and configure, and it's also quite heavy.

**Comment by athoik** [comment]
Why not use LiteLLM?

**Reply by ei-grad** [reply]
Did you mean to use litellm as a python library to use in open-webui?

**Comment by ei-grad** [comment]
Wrote a proxy for that: https://github.com/ei-grad/vertexai-openapi-proxy

```yaml
services:
  proxy:
    image: ghcr.io/ei-grad/vertexai-openapi-proxy:latest
    #build: .
    environment:
      - VERTEXAI_PROJECT=${VERTEXAI_PROJECT}
      - VERTEXAI_LOCATION=${VERTEXAI_LOCATION}
      # Point to the mounted ADC file inside the container
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_adc.json
      # Optional: Comma-separated list of models. See .env.example or README.md for details.
      # - VERTEXAI_AVAILABLE_MODELS=${VERTEXAI_AVAILABLE_MODELS}
    volumes:
      # Mount the ADC file from your host to the container
      # IMPORTANT: Replace ~/.config/gcloud/application_default_credentials.json
      # with the actual path to your ADC file if it's different.
      - ~/.config/gcloud/application_default_credentials.json:/app/gcp_adc.json:ro
    restart: unless-stopped

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      OPENAI_API_BASE_URL: http://proxy:8080/v1
      OPENAI_API_KEY: dummy_key_for_vertex_proxy
      # turn off the heavy PyTorch-based embedding engine used by default:
      RAG_EMBEDDING_ENGINE: openai
      RAG_EMBEDDING_MODEL: "none"
    volumes:
      - webui-data:/app/backend/data
    restart: unless-stopped

volumes:
  webui-data:
```
