### DISCUSSION TITLE
Langfuse integration

### DISCUSSION THREAD

**Discussion by flefevre** [open-webui/open-webui#1014] [General]
**langfuse integration**
In order to monitor the open webui application (prompt usage, model sélection, metrics) , it would be à good idéa to intégrateur the langfuse api. 
I am not part of it, so perhaps there is better alternative but it will be définitively a mandatory feature in the newt release of 'open webui'

**Comment by flefevre** [comment]
https://github.com/langfuse/langfuse

**Reply by Michelklingler** [reply]
Hello!
We've been talking about it in the discord for a few days and we found out that the connection is pretty straight forward using LiteLLM.

Of course it would only monitor the call made throught the LiteLLM integration.

We would just need to update 2 things in the code and it would work out of the box with a little of configuration.

1 - Add `langfuse` dependency  to requierement.txt file 


2 - Add pass the $user_id to LiteLLM to be able to have the user usage monitoring in the dashboard.

<img width="526" alt="Screenshot 2024-03-19 at 4 49 39 PM" src="https://github.com/open-webui/open-webui/assets/63208430/ad402a5a-b8bf-4d2c-a659-f425c6c2aebb">

When this is added to the code, do the following to send your call to langfuse:

1 - When launching the Docker container pass the 2 following env. variable:

LANGFUSE_PUBLIC_KEY: "xxxxx"
LANGFUSE_SECRET_KEY: "xxxxx"

Those key are provided when you create a project in Langfuse.

2 - Edit the LiteLLM config.yaml file 

And add under general setting the following:

```
general_settings: {}
litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]  
```

As mentionned in their doc https://litellm.vercel.app/docs/observability/langfuse_integration

Tested it works like a charm!
I just need someone to update the requierement file and pass the user variable with the API call to LiteLLM.

**Reply by jannikstdl** [reply]
Thanks for the documentation!

**Reply by flefevre** [reply]
@Michelklingler thanks a lot for your sharing.

i do not see the LANGFUSE_HOST variable , did you set it? in your docker-compose file?

did you sumit a PR to integrate ths in openwebui?

thanks again

**Reply by flefevre** [reply]
Additionnaly to the question on how you pass the LANGFUSE_HOST variable, I would like to know how to you trace the call that is made directly from Openwebui to Ollama ? since some models can be served by ollama and other from the litellm

**Reply by srd00** [reply]
About LANGFUSE_HOST I suppose he just forgot to mention it

About local ollama models all you gotta do is add these to litellm/config.yaml (sample data)

```
general_settings: {}
litellm_settings:
  failure_callback:
  - langfuse
  success_callback:
  - langfuse
model_list:
- litellm_params:
    api_base: http://127.0.0.1:11434
    model: ollama/mixtral:latest
  model_name: ollama/mixtral:latest   # Can be changed, this is what is actually shown on the ui
router_settings: {}
```

you can also use your own modelfile modelname and you can also add those through the ui.

**Reply by bleriot14** [reply]
Please can you explain what do you mean with "2 - Add pass the $user_id to LiteLLM to be able to have the user usage monitoring in the dashboard." ? How can I pass it ? We can only send these headers from openwebui:
X-OpenWebUI-User-Name
X-OpenWebUI-User-Id
X-OpenWebUI-User-Email
X-OpenWebUI-User-Role

**Comment by Michelklingler** [comment]
On the other side LiteLLM team added a flag I requested to be able to discard forwarding message content to Langfuse as it was too private for me to share actual message written to the chatbot.

Langfuse would only record Model / call / UserID

https://github.com/BerriAI/litellm/issues/2586

**Comment by Michelklingler** [comment]
PR to add the Langfuse dependency to the requirements.txt file:

https://github.com/open-webui/open-webui/pull/1267

**Comment by flefevre** [comment]
@Michelklingler thanks a lot.
I didn't understand why i didn't see your answer.

I will test it before the end of the week.
i have à question, you made a PR with only the modification of the requirement, but you spoke also 'add Pass $user id', where is thèse filé ? Why you didn't subit in your PR ?

Sorry if i miss understand.

**Reply by flefevre** [reply]
I have seen that someone from langfuse answered me on how to do it directly inside open webui with out needed litellm configuration. 
Hé said we Just to add New extension points, but i have no idéa on how to do it. 
IT will allow to monitor direct call to ollama. 

What is your vision ? 

https://discord.com/channels/1111061815649124414/1111063505563562064/1214526473575337984

**Reply by Michelklingler** [reply]
Check the thread above.

You only have to: 

1. pass your langfuse API key as an environnement variable when you run the WebUI

2. Add the 2 line yo activate langfuse call back in the LiteLLM configuration file.

![image](https://github.com/open-webui/open-webui/assets/63208430/f6223425-c2f2-4428-8e42-3791426138a7)

I will make a clearer documentation about this soon

**Reply by flefevre** [reply]
@Michelklingler thanks for the shared element.
Something is still not clear for me: where do i put the environmental variabel LANGFUSE_HOST or OPENWEBUI_LANGFUSE_HOST in order to link to the local installation of Langfuse?
Thanks for your explanation

**Reply by Michelklingler** [reply]
https://docs.openwebui.com/tutorial/langfuse

I edited a clearer documentation above.

I hope it helps, if not let me know how I can help.

**Reply by flefevre** [reply]
Hello @Michelklingler thanks a lot for the clearer documentation.
You said:
`If data privacy is a concern for you, it is recommended to install the local version instead.`

But I didn't find any element on the Langfuse HOST configuration. It seems we can only use Langfuse official service.
is it a environmental variable in the docker-compose.yml file OR in the LiteLLM Configuration File ?

Could you provide such additional information for the community?
Thanks again. François

**Reply by melihkacaman** [reply]
Yes, I don't understand it also. 
Could you please give us more information about that. 
I am using the langfuse locally, too. 

Thanks.

**Reply by Michelklingler** [reply]
Hi everyone!

Below is the config to run Langfuse locally.

The following code added to your docker-compose will create:

1 - A local Langfuse server that will monitor all request made through the LiteLLM integration.
2 - A local PostgreSQL database and a UI to save all request informations

Add the following below the docker-compose you use to launch the OpenWeb-UI (if you still run openWebUI with docker run, I highly suggest you move toward a docker-compose solution at this point, it will make it easier to maintain)

```
### SERVICE : Langfuse ###
  langfuse-server:
    image: ghcr.io/langfuse/langfuse:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

 ### SERVICE : PostgreSQL Database for Langfuse ###
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

### SERVICE : GUI for PostgreSQL Database ###
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
```

**Reply by srd00** [reply]
Thanks! Tracking traces seem to work pretty well, did you have any luck on passing user_id and session_id to the langfuse callback?

**Reply by Michelklingler** [reply]
We would need to pass the User ID variable to LiteLLM as well.
For now the WebUI only pass the message ID, Model Name and content of the request + response.

Probably a minor adjustement to the code.

**Reply by ther3zz** [reply]
Do you know if this passes user feedback?
I've played around with it a bit and I can see traces but cannot see any feedback within langfuse

**Reply by meetzuber** [reply]
I am also not able to see user_id and feedback in langfuse. Is there any work around/ configuration which I am missing.

**Reply by srd00** [reply]
Finally managed to pass the user (in my case user.email). But can't access the session-id on the litellm proxy so that it can be sent as metadata for langfuse.

To send user data, add this to proxy on litellm/main.py

```
async def proxy(path: str, request: Request, `user=Depends(get_verified_user)):
    # snipped ...
    headers["Content-Type"] = "application/json"

    # Setting up metadata for langfuse integration used try so that it doesn't overwrite something down the line
    body = body.decode("utf-8")
    body = json.loads(body)
    try:
        body['metadata']['trace_user_id'] = user.email
    except KeyError as e:
        body['metadata'] = {}
        body['metadata']['trace_user_id'] = user.email
    body = json.dumps(body)
    
    r = None
    try:
        r = requests.request(...
        # snipped ...
```

Can anyone help with session-id?

**Reply by ther3zz** [reply]
> Finally managed to pass the user (in my case user.email). But can't access the session-id on the litellm proxy so that it can be sent as metadata for langfuse.
> 
> To send user data, add this to proxy on litellm/main.py
> 
> ```
> async def proxy(path: str, request: Request, `user=Depends(get_verified_user)):
>     # snipped ...
>     headers["Content-Type"] = "application/json"
> 
>     # Setting up metadata for langfuse integration used try so that it doesn't overwrite something down the line
>     body = body.decode("utf-8")
>     body = json.loads(body)
>     try:
>         body['metadata']['trace_user_id'] = user.email
>     except KeyError as e:
>         body['metadata'] = {}
>         body['metadata']['trace_user_id'] = user.email
>     body = json.dumps(body)
>     
>     r = None
>     try:
>         r = requests.request(...
>         # snipped ...
> ```
> 
> Can anyone help with session-id?

Are you also seeing user feedback in langfuse?

**Comment by Michelklingler** [comment]
Langfuse is open source.
The cloud version is only a hosted version, turnkey solution.

You can install Langfuse locally using this repository:
https://github.com/langfuse/langfuse

**Comment by yeahdongcn** [comment]
I see a warning in https://docs.openwebui.com/tutorial/langfuse/

```text
warning
Bundled LiteLLM support has been deprecated from 0.2.0
```

Can I still config `langfuse` through `litellm` config?

**Reply by rzippert** [reply]
Yes, this deprecation only means that litellm is not bundled anymore into openwebui, but can be setup separately as an "OpenAI endpoint". Check the [docs](https://docs.openwebui.com/migration) for more information.

**Comment by flefevre** [comment]
Hello
Personnaly I have migrated to the last openwebui
So I do not use anymore the internal litellm

I have deployed an external litellm service through docker which I have
configure to use an external langfuse service also deployed through docker.

Everything is working.
Openwebui is great!

**Reply by yeahdongcn** [reply]
Could you share your litellm config? Thanks.

**Reply by ther3zz** [reply]
> Could you share your litellm config? Thanks.

here's mine

```
general_settings: 
  master_key: sk-

litellm_settings:
  failure_callback: ["langfuse"]
  success_callback: ["langfuse"]

model_list:
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/mistral
  model_name: ollama/mistral
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/mistral-openorca
  model_name: ollama/mistral-openorca
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/phi3
  model_name: ollama/phi3
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llava
  model_name: ollama/llava
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llama3-gradient
  model_name: ollama/llama3-gradient
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llama3-chatqa:8b
  model_name: ollama/llama3-chatqa:8b
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llava-llama3
  model_name: ollama/llava-llama3
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/command-r
  model_name: ollama/command-r
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/deepseek-v2:latest
  model_name: ollama/deepseek-v2:latest
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llama3:70b
  model_name: ollama/llama3:70b
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/mistral-nemo:12b
  model_name: nemo
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llama3.1:70b
  model_name: ollama/llama3.1:70b
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llama3.1:latest
  model_name: ollama/llama3.1:latest
- litellm_params:
    api_base: http://192.168.1.200:11434
    model: ollama/llava-phi3:latest
  model_name: ollama-llava-phi3

router_settings:
  redis_host: 192.168.1.200
  redis_port: 6379

proxy:
  enabled: true
  port: 4000
```
