### DISCUSSION TITLE
Seek help!  cannot be used with Searxing, console prompt 400: Search query generation is disabled

### DISCUSSION THREAD

**Discussion by cy-6359** [open-webui/open-webui#10157] [Q&A]
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/1efdf79e-955f-445b-b66b-66d2c55e414e" />
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/0d8a6b4d-6c6a-49f6-baa2-adc12e9f292b" />
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/016cf2bb-aa91-4a97-89fe-7c53f5569df0" />
<img width="900" alt="image" src="https://github.com/user-attachments/assets/dd706f05-1060-4b02-b96b-06bfa9c4dc5d" />

**I have enabled the search function**
**I don't know how to solve it..**

open-webui docker compose 👇🏻
```
version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/backend/data
    environment:
      - ENABLE_OPENAI_API=False
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE="duckduckgo"
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
    restart: unless-stopped
```
