### DISCUSSION TITLE
Is anyone else having issues with the latest docker image?

### DISCUSSION THREAD

**Discussion by Cereal916** [open-webui/open-webui#10503] [Q&A]
I tried to pull the latest image and got an error
Failed to deploy a stack: compose build operation failed: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory. I'm still a bit new to docker but it sounds like its an issue with build... would anyone mind nudging me in the right direction?

```
open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    volumes:
      - /docker/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
```
