### DISCUSSION TITLE
How to enable reasoning for AWS Bedrock Claude 3.7 Sonnet

### DISCUSSION THREAD

**Discussion by nodomain** [open-webui/open-webui#10705] [General]
You may have read the news: https://www.anthropic.com/news/claude-3-7-sonnet

I added it to via litellm-proxy with these parameters:

```yaml
  - model_name: "Claude 3.7 Sonnet"
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      aws_region_name: us-west-2
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
```

How can we make use of the reasoning capabilities?
