### DISCUSSION TITLE
Ollama to Docker to OpenwebUI

### DISCUSSION THREAD

**Discussion by logan683** [open-webui/open-webui#10709] [General]
Something is preventing Openweb UI from seeing Ollama through Docker.  I have literally gone through every single post anywhere I can find about this.  Much of the information relates to Linux, however, I am on a Windows 11 machine.  I found one thing that sort of fixed the issue at:
https://github.com/open-webui/open-webui/discussions/803

Specifically, this:
~https://github.com/open-webui/open-webui/discussions/803#discussioncomment-8520916~
https://github.com/open-webui/open-webui/discussions/803#discussioncomment-8520895

I keep models on a separate drive from the installs for Ollama and Docker.  I'm not sure if this matters.  Using the run docker command from the above comment makes a Docker instance in Docker Desktop I can see, but it doesn't provide port numbers.  I'm not sure it's using my GPU, either.  If I copy and run the command for GPU from the Openweb UI documentation, I get a bunch of the following errors:
ERROR [open_webui.routers.ollama] Connection error: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]

Openweb UI is also extremely slow.  Ollama command line is near instantaneous using the same model.  Any help would be appreciated.  Thank you very much.

Edit: Linked wrong comment.

**Comment by tryiou** [comment]
i'm using docker compose here for both ollama and open webui, having them on same internal network,
this setup use a nvidia GPU.

### docker-compose.yml

```yaml
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
#~     volumes:  # optional: mount external ollama folder
#~       - /mnt/nvme/ai/.ollama:/root/.ollama
#~     ports:  # optional: to reach ollama from host
#~       - "11434:11434"
#~     environment:
#~       - OLLAMA_MAX_LOADED_MODELS=2
#~       - GGML_CUDA_ENABLE_UNIFIED_MEMORY=1
#~       - OLLAMA_GPU_OVERHEAD=536870912
    pull_policy: always
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "30000:8080"
    environment:
      WEBUI_AUTH: 'False'
      OLLAMA_BASE_URL: 'http://ollama:11434'
#~     volumes:  # optional: mount external open-webui folder
#~       - ./data:/app/backend/data
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

deploying/updating it with :
```bash
# save this docker-compose.yml file in a new folder, get a terminal into it, then:
docker compose pull
docker compose up -d --remove-orphans
```
