### DISCUSSION TITLE
Receiving error: Unexpected token

### DISCUSSION THREAD

**Discussion by Thoemmy** [open-webui/open-webui#11053] [Issues]
Hi i have the latest release of openwebui installed - v0.5.18

Unfortunately i am receiving following two errors:

```
SyntaxError: Unexpected token 'd', "data: {"id"... is not valid JSON
```

![image](https://github.com/user-attachments/assets/7ed8b061-38d3-40f2-bb98-f766e68478d3)

```
SyntaxError: Unexpected token ':', ": OPENROUT"... is not valid JSON
```

![image](https://github.com/user-attachments/assets/2f50ad58-11b2-4b4f-8955-7ccb2721db3d)

This is happening when i use openai api and openrouter api so i am a bit clueless..

Admin Connection Screenshot:
![image](https://github.com/user-attachments/assets/249b1b32-893a-4252-b882-211064889ca2)

Both connection checks results in ok

![image](https://github.com/user-attachments/assets/ca087eb4-eaef-4db6-8161-5381b1bec26b)

I have following docker compose setup:

```yaml
version: "3.8"
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G
volumes:
  open-webui:
```

Disclaimer: I am using an nginx proxy which allows only ports 80 and 443

If you need more information i am happy to provide it.

Thanks a lot.

Best regards
Thömmy
