### DISCUSSION TITLE
The model returned the following errors: too many total text bytes

### DISCUSSION THREAD

**Discussion by hongbo-miao** [open-webui/open-webui#11063] [Issues]
I am using Bedrock Clause model -> LiteLLM -> Open WebUI.

I am using

- Open WebUI `v0.5.18`
- LiteLLM `v1.61.20-stable`

I can succeed asking question when knowledge collection does not have a lot of files.
However, I got error when ask question with a large knowledge collection with many markdown files inside.

Also, worth mentioning this knowledge collection never changed, in the past with old Open WebUI and LiteLLM versions, I can succeed ask questions.

```sh
INFO:     172.31.156.135:33904 - "POST /chat/completions HTTP/1.1" 200 OK
07:08:16 - LiteLLM Proxy:ERROR: proxy_server.py:3039 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - litellm.BadRequestError: BedrockException - validationException {"message":"The model returned the following errors: too many total text bytes: 15020337 > 9000000"}
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1596, in __anext__
    async for chunk in self.completion_stream:
    ...<50 lines>...
        return processed_chunk
  File "/usr/lib/python3.13/site-packages/litellm/llms/bedrock/chat/invoke_handler.py", line 1482, in aiter_bytes
    message = self._parse_message_from_event(event)
  File "/usr/lib/python3.13/site-packages/litellm/llms/bedrock/chat/invoke_handler.py", line 1501, in _parse_message_from_event
    raise BedrockError(
    ...<6 lines>...
    )
litellm.llms.bedrock.common_utils.BedrockError: validationException {"message":"The model returned the following errors: too many total text bytes: 15020337 > 9000000"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/litellm/proxy/proxy_server.py", line 3018, in async_data_generator
    async for chunk in response:
    ...<14 lines>...
            yield f"data: {str(e)}\n\n"
  File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1751, in __anext__
    raise exception_type(
          ~~~~~~~~~~~~~~^
        model=self.model,
        ^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        extra_kwargs={},
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2202, in exception_type
    raise e
  File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 909, in exception_type
    raise BadRequestError(
    ...<4 lines>...
    )
litellm.exceptions.BadRequestError: litellm.BadRequestError: BedrockException - validationException {"message":"The model returned the following errors: too many total text bytes: 15020337 > 9000000"}
```

This is my deployment code

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-hm-open-webui
  namespace: production-hm-argo-cd
  labels:
    app.kubernetes.io/name: hm-open-webui
spec:
  project: production-hm
  source:
    repoURL: https://helm.openwebui.com
    # https://artifacthub.io/packages/helm/open-webui/open-webui
    targetRevision: 5.20.0
    chart: open-webui
    helm:
      releaseName: hm-open-webui
      values: |
        # https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
        ---
        image:
          repository: ghcr.io/open-webui/open-webui
          # https://github.com/open-webui/open-webui/releases
          tag: v0.5.18
        ollama:
          enabled: false
        pipelines:
          enabled: false
        persistence:
          enabled: true
          existingClaim: hm-open-webui-persistent-volume-claim
        serviceAccount:
          enable: false
        # https://docs.openwebui.com/getting-started/env-configuration/
        # https://github.com/open-webui/open-webui/blob/main/backend/open_webui/config.py
        extraEnvVars:
          - name: ENV
            value: prod
          - name: WEBUI_NAME
            value: AI Chat
          - name: WEBUI_URL
            value: https://open-webui.hongbomiao.com
          - name: OPENAI_API_BASE_URLS
            value: http://hm-litellm-service.production-hm-litellm.svc:80;http://hm-open-webui-pipelines.production-hm-open-webui-pipelines.svc:9099
          - name: OPENAI_API_KEYS
            valueFrom:
              secretKeyRef:
                name: hm-open-webui-secret
                key: OPENAI_API_KEYS
          - name: DEFAULT_MODELS
            value: claude-3-7-sonnet
          - name: PDF_EXTRACT_IMAGES
            value: "true"
          - name: RAG_FULL_CONTEXT
            value: "true"
  destination:
    namespace: production-hm-open-webui
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
```

Initially I thought it is related to `RAG_FULL_CONTEXT` as I recently turned it on. So I tried to turn it off, but I still got same error.

I checked LiteLLM log, I can see Open WebUI accessed LiteLLM's `/models` endpoint which returns

```json
{
  "data": [
    {
      "id": "claude-3-7-sonnet",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    },
    {
      "id": "claude-3-5-sonnet",
      "object": "model",
      "created": 1677610602,
      "owned_by": "openai"
    }
  ],
  "object": "list"
}
```

However, Open WebUI never tried to access LiteLLM  `/model/info` endpoint which include token limitation info which may be related with this issue.

```json
{
  "data": [
    {
      "model_name": "claude-3-5-sonnet",
      "litellm_params": {
        "aws_region_name": "us-west-2",
        "use_in_pass_through": false,
        "model": "bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0"
      },
      "model_info": {
        "id": "2accf8119d59a8649d0791da4a0808b70729759e34cb2a49019f4be05d6c2f89",
        "db_model": false,
        "key": "anthropic.claude-3-5-sonnet-20241022-v2:0",
        "max_tokens": 8192,
        "max_input_tokens": 200000,
        "max_output_tokens": 8192,
        "input_cost_per_token": 0.000003,
        "cache_creation_input_token_cost": null,
        "cache_read_input_token_cost": null,
        "input_cost_per_character": null,
        "input_cost_per_token_above_128k_tokens": null,
        "input_cost_per_query": null,
        "input_cost_per_second": null,
        "input_cost_per_audio_token": null,
        "output_cost_per_token": 0.000015,
        "output_cost_per_audio_token": null,
        "output_cost_per_character": null,
        "output_cost_per_token_above_128k_tokens": null,
        "output_cost_per_character_above_128k_tokens": null,
        "output_cost_per_second": null,
        "output_cost_per_image": null,
        "output_vector_size": null,
        "litellm_provider": "bedrock",
        "mode": "chat",
        "supports_system_messages": null,
        "supports_response_schema": true,
        "supports_vision": true,
        "supports_function_calling": true,
        "supports_tool_choice": true,
        "supports_assistant_prefill": true,
        "supports_prompt_caching": true,
        "supports_audio_input": false,
        "supports_audio_output": false,
        "supports_pdf_input": true,
        "supports_embedding_image_input": false,
        "supports_native_streaming": null,
        "tpm": null,
        "rpm": null,
        "supported_openai_params": [
          "max_tokens",
          "max_completion_tokens",
          "stream",
          "stream_options",
          "stop",
          "temperature",
          "top_p",
          "extra_headers",
          "response_format",
          "tools"
        ]
      }
    },
    {
      "model_name": "claude-3-7-sonnet",
      "litellm_params": {
        "aws_region_name": "us-west-2",
        "use_in_pass_through": false,
        "model": "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
      },
      "model_info": {
        "id": "09760fb8d7c845875a86710f1aa0c5afcc1f1bd1f0a439d4ed67bf1b1d1173f9",
        "db_model": false,
        "key": "anthropic.claude-3-7-sonnet-20250219-v1:0",
        "max_tokens": 8192,
        "max_input_tokens": 200000,
        "max_output_tokens": 8192,
        "input_cost_per_token": 0.000003,
        "cache_creation_input_token_cost": null,
        "cache_read_input_token_cost": null,
        "input_cost_per_character": null,
        "input_cost_per_token_above_128k_tokens": null,
        "input_cost_per_query": null,
        "input_cost_per_second": null,
        "input_cost_per_audio_token": null,
        "output_cost_per_token": 0.000015,
        "output_cost_per_audio_token": null,
        "output_cost_per_character": null,
        "output_cost_per_token_above_128k_tokens": null,
        "output_cost_per_character_above_128k_tokens": null,
        "output_cost_per_second": null,
        "output_cost_per_image": null,
        "output_vector_size": null,
        "litellm_provider": "bedrock_converse",
        "mode": "chat",
        "supports_system_messages": null,
        "supports_response_schema": true,
        "supports_vision": true,
        "supports_function_calling": true,
        "supports_tool_choice": true,
        "supports_assistant_prefill": true,
        "supports_prompt_caching": true,
        "supports_audio_input": false,
        "supports_audio_output": false,
        "supports_pdf_input": false,
        "supports_embedding_image_input": false,
        "supports_native_streaming": null,
        "tpm": null,
        "rpm": null,
        "supported_openai_params": [
          "max_tokens",
          "max_completion_tokens",
          "stream",
          "stream_options",
          "stop",
          "temperature",
          "top_p",
          "extra_headers",
          "response_format",
          "tools",
          "thinking"
        ]
      }
    }
  ]
}
```
