### DISCUSSION TITLE
Embedding model set: sentence-transformers/all-MiniLM-L6-v2 =>  exited with code 0 (Docker)

### DISCUSSION THREAD

**Discussion by toddpage** [open-webui/open-webui#11225] [Issues]
Trying to run on Ubuntu 24.04 server as docker. Using the same config as another server, which works.  But, it exit with code 0.

here is the start log after doing a `docker compose up`

```
open-webui  | /app/backend/open_webui
open-webui  | /app/backend
open-webui  | /app
open-webui  | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
open-webui  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
open-webui  | INFO  [open_webui.env] 'DEFAULT_LOCALE' loaded from the latest database entry
open-webui  | INFO  [open_webui.env] 'DEFAULT_PROMPT_SUGGESTIONS' loaded from the latest database entry
open-webui  | WARNI [open_webui.env] 
open-webui  | 
open-webui  | WARNING: CORS_ALLOW_ORIGIN IS SET TO '*' - NOT RECOMMENDED FOR PRODUCTION DEPLOYMENTS.
open-webui  | 
open-webui  | INFO  [open_webui.env] Embedding model set: sentence-transformers/all-MiniLM-L6-v2
open-webui exited with code 0
```

**YAML**
```  
open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - /opt/machineLearning/ollama:/app/backend/data
    depends_on:
      #- ollama
      - ollama-server
    ports:
      - ${OPEN_WEBUI_PORT-3010}:8080
      #- "3011:8081
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```
