### DISCUSSION TITLE
issue: Digest Mismatch: Unable to Download Models

### DISCUSSION THREAD

**Discussion by jlar0che** [open-webui/open-webui#11344] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.

### Installation Method

Docker

### Open WebUI Version

v0.5.20

### Ollama Version (if applicable)

v0.5.13

### Operating System

Ubuntu Server 22.04.2

### Browser (if applicable)

Firefox v136.0, Chrome v133.0.6943.142

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have checked the browser console logs.
- [x] I have checked the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

- [x] Click the "down arrow" next to the Models in the web ui
- [x] Type in Model name (e.g. deepseek-r1:32b)
- [x] Click on the `Pull "_model-name_" from Ollama.com` button
- [ ] Wait for the download to successfully complete 100% and the model gets added to the available models list

### Actual Behavior

Hash verification process at the end of the download fails (see attached photo). Model never completes download.

![Image](https://github.com/user-attachments/assets/ac12e327-6772-4451-8bbb-4ff24590cbf1)``

### Steps to Reproduce

1. Setup Ubuntu Server 22.04.2
2. Verify enough disk space with `df -h` (see screenshot below)
![Image](https://github.com/user-attachments/assets/1f1f6703-1447-4025-b0f8-7dec4851671d)
3. Install Docker via apt repository for Ubuntu as per instructions here: https://docs.docker.com/engine/install/ubuntu/
4. Install Open Web UI with Ollama support (see docker-compose.yml file below)
```
services:
    ollama:
        volumes:
            - /volume1/docker/ollama:/root/.ollama:rw
        container_name: ollama
        pull_policy: always
        tty: true
        restart: always
        image: ollama/ollama:latest
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=compute,utility
        dns:
          - 8.8.8.8
          - 1.1.1.1
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]

    open-webui:
        image: 'ghcr.io/open-webui/open-webui:cuda' #or use ":main"
        container_name: open-webui
        restart: always
        volumes:
            - '/volume1/docker/open-webui:/app/backend/data:rw' 
        depends_on: 
          - ollama
        environment:
            - 'OLLAMA_BASE_URL=http://ollama:11434'
            - 'WEBUI_SECRET_KEY='
        ports:
            - '3808:8080'
        extra_hosts:
          - host.docker.internal:host-gateway
        dns:
          - 8.8.8.8
          - 1.1.1.1

volumes:
  ollama: {}
  open-webui: {}
```
5. Attempt to download Models
6. Tried to download models after connecting to Open Web UI directly with IP and Port (to eliminate any possible issue with reverse proxy)
7. Added DNS entries to docker-compose.yml to solve the issue, but didn't work
8. Tried purging models on Ubuntu Server with `rm -rf /volume1/docker/ollama/models/*` and then redownloading models. Didn't Fix. Some models download (like deepseek-r1:1.5b and deepseek-r1:8b) but larger models continue to fail (like deepseek-r1:14b and deepseek-r1:32b).
9. Tried manually adding nameserver entry to Ollama container by adding `echo "nameserver 8.8.8.8" > /etc/resolv.conf` via Exec console. Didn't fix.

### Logs & Screenshots

![Image](https://github.com/user-attachments/assets/e4165977-4446-4151-857a-4ad32f4f3d49)
