### DISCUSSION TITLE
issue: Model appears in selection dropdown while being disabled

### DISCUSSION THREAD

**Discussion by bannert1337** [open-webui/open-webui#11689] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.5.20

### Ollama Version (if applicable)

v0.6.0

### Operating System

Alpine Linux (Server), CachyOS (Client)

### Browser (if applicable)

Zen Browser v1.9.1b (Firefox 136.0.1) (64-bit)

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

When models are disabled and appear as disabled in `Admin Panel` > `Settings` > `Models` they should not appear in the model selection dropdown nor be selectable.

### Actual Behavior

Models are shown in the model selection dropdown of chats even though being disabled.

### Steps to Reproduce

1. Go to `Admin Panel` > `Settings` > `Models`
2. Disable a model
3. Go to `New Chat`
4. Find model to still be available and selectable

### Logs & Screenshots

![Image](https://github.com/user-attachments/assets/00f9855d-065c-48f5-9e7c-c06997f846c8)

![Image](https://github.com/user-attachments/assets/f42401de-8d88-4629-8dd0-da84c708c24d)

### Additional Information

There might be an issue with persisting the activation state of a model.

Open WebUI running in Docker compose stack:
```yaml
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT:-3000}:8080
    environment:
      WEBUI_URL: https://chat.domain.tld
      ENABLE_SIGNUP: false
      ENABLE_COMMUNITY_SHARING: true
      ENABLE_OLLAMA_API: true
      OLLAMA_BASE_URL: http://ollama:11434
      ENABLE_RAG_WEB_SEARCH: true
      RAG_WEB_SEARCH_ENGINE: searxng
      RAG_WEB_SEARCH_RESULT_COUNT: 5
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 25
      ENABLE_LOGIN_FORM: false
      RAG_RERANKING_MODEL:
      ENABLE_RAG_HYBRID_SEARCH: false
      ENABLE_WEBSOCKET_SUPPORT: "true"
      RAG_EMBEDDING_ENGINE: ollama
      AUDIO_STT_ENGINE: openai
      WEBSOCKET_MANAGER: "redis"
      WEBSOCKET_REDIS_URL: "redis://redis-valkey:6379/1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: docker.io/valkey/valkey:alpine
    container_name: redis-valkey
    volumes:
      - redis-data:/data
    command: "valkey-server --save 30 1"
    healthcheck:
      test: "[ $$(valkey-cli ping) = 'PONG' ]"
      start_period: 5s
      interval: 1s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  open-webui:
  redis-data:
```

I am using the OpenRouter pipe from the Open WebUI community:
https://openwebui.com/f/rburmorrison/openrouter
