### DISCUSSION TITLE
feat: Does it support the Deepseek API service?

### DISCUSSION THREAD

**Discussion by Quaternijkon** [open-webui/open-webui#11979] [Q&A]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.

### Problem Description

I found it only support openai API, does it support deepseek API?

### Desired Solution you'd like

I found it only support openai API,

**Comment by athoik** [comment]
Hi,

Deepseek can be used through LiteLLM.

You need to create config for litellm (eg /opt/litellm/litellm_config.yaml - https://litellm.vercel.app/docs/simple_proxy)

```
model_list:
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: sk-...
```

Then in open-webui set the OpenAI API connection to  `http://litellm-proxy:4000` and you are done! 
You can start using sharing multiple models using LiteLLM, just add then to config and they will become available to LiteLLM.
