### DISCUSSION TITLE
Open WebUI now integrates with OpenTelemetry - help needed

### DISCUSSION THREAD

**Discussion by ips972** [open-webui/open-webui#12344] [Q&A]
the new release notes show this:
 OpenTelemetry Support for Observability: Open WebUI now integrates with OpenTelemetry, allowing you to connect with tools like Grafana, Jaeger, or Prometheus for detailed performance insights and real-time visibility—entirely opt-in and fully self-hosted. Even if enabled, no data is ever sent to us, ensuring your privacy and ownership over all telemetry data.
 
 
 and grafana dashboards has this - lovely dashboard for open webui based on influxdb:
 https://grafana.com/grafana/dashboards/22867-grafana-dashboard-for-open-webui/
 
 i'm running open-webui with docker-compose.yml - container based - and for the love of god - i can't find any guides or explanations how to set this up.. 
 
 can anyone  help?

**Comment by gonzalo** [comment]
for sure I'm so interested in this topic

**Comment by avatsaev** [comment]
Checked the source code and found this:

https://github.com/open-webui/open-webui/blob/main/backend/open_webui/utils/telemetry/setup.py

And this:

https://github.com/open-webui/open-webui/blob/main/backend/open_webui/main.py#L448

So as far as I underdstand, you basically you have to setup two ENV VARs:

- `ENABLE_OTEL=true`
- `OTEL_EXPORTER_OTLP_ENDPOINT`="http://your-otel-endpoint:4317"

I've deployed OTEL using OpenTelemetry backend in a Docker image on my server which is running fine: https://grafana.com/blog/2024/03/13/an-opentelemetry-backend-in-a-docker-image-introducing-grafana/otel-lgtm/

See how to deploy it yourself here: https://github.com/grafana/docker-otel-lgtm, check the start secipt to get the docker run command

I've set the ENV Vars on my openwebui deployment and can see some traces in promotheus, and some spans in tempo


<img width="1503" alt="image" src="https://github.com/user-attachments/assets/c9560b35-4907-4d45-bb4d-1454a41cc1a3" />

<img width="1506" alt="image" src="https://github.com/user-attachments/assets/3c799489-a0e6-4e46-bb7c-d33e0c0c8468" />

**Reply by ips972** [reply]
thanks alot for the detailed answers. 

the link i gave above for ready made dashboards mention that the data from OTEL is sent to influxdb and not Prometheus - do you have an idea how they made this happen

**Reply by avatsaev** [reply]
Sorry i'm not sure how to make the dashboard you linked work with influxDB, the documentation is lacking on this, I'm going to build my own dashboard with what I was able to setup here, and go from there.

**Reply by gonzalo** [reply]
I'm trying to follow your instructions and deployed as follows.

compose.yaml
```
name: open_telemetry_grafana
services:
    otel-lgtm:
        ports:
            - 3000:3000
            - 4317:4317
            - 4318:4318
        tty: true
        stdin_open: true
        image: grafana/otel-lgtm
        networks:
          ia-frontend_web:
            aliases:
              - open_telemetry
networks:
  ia-frontend_web:
    external: true
```

Seems to start fine. at least grafana is available

Addedd to my openwebui deployment 

```
    environment:
      - CUSTOM_NAME=xxxx
      - ADMIN_EMAIL=xxxxxxxx
      - ENV=dev  
      - ENABLE_OTEL=true
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://open_telemetry:4318"
```

But no data received on prometheus. Chekcing open webui logs I see multiple errors like this

`open-webui  | 2025-04-07 17:49:28.079 | WARNING  | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:328 - Transient error StatusCode.UNAVAILABLE encountered while exporting traces to "http://open_telemetry:4318", retrying in 4s. - {}`

It seems htatn open-webui is not able to reach endpoint but if i try directecly from inside the container it seems to be available..

```
root@1502aeaf34bb:/app/backend# curl http://open_telemetry:4317
curl: (1) Received HTTP/0.9 when not allowed
```

Any clue?

**Reply by avatsaev** [reply]
>  OTEL_EXPORTER_OTLP_ENDPOINT="http://open_telemetry:4318"

connect openwebui to the gRCP port 4317 instead of HTTP port 4318

openwebui instrumentation uses gRCP protocol to send logs and traces 

> OTEL_EXPORTER_OTLP_ENDPOINT="http://open_telemetry:4317"

should be working fine after that

**Reply by gonzalo** [reply]
thanks @avatsaev , I failed pasting after some tests. My first (and current attempt) tries to use 4317 port

```
ENV variables
      - ENABLE_OTEL=true
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://open_telemetry:4317"

openwebui container logs

2025-04-09 16:35:36.802 | WARNING  | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:328 - Transient error StatusCode.UNAVAILABLE encountered while exporting traces to "http://open_telemetry:4317", retrying in 16s. - {}
2025-04-09 16:35:52.807 | WARNING  | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:328 - Transient error StatusCode.UNAVAILABLE encountered while exporting traces to "http://open_telemetry:4317", retrying in 32s. - {}

curl from openwebui container
root@6545005f676e:/app/backend# curl http://open_telemetry:4317
curl: (1) Received HTTP/0.9 when not allowed

```


Brrrrr, so frustrating...

**Reply by arunbugkiller** [reply]
@gonzalo facing same issue - were you able to make this work?

**Comment by ips972** [comment]
So? Does anyone have a working example config? Docker-compose.yml would be greate :-)

**Comment by matthew-kusz** [comment]
I got it to work with this setup using podman in my `compose.yaml` file:
````
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.3.0-rc.1
    ports:
      - 9090:9090
    command:
      - "--web.enable-remote-write-receiver"
      - "--web.enable-otlp-receiver"
      - "--enable-feature=exemplar-storage"
      - "--enable-feature=native-histograms"
      - "--storage.tsdb.path=/data/prometheus"
      - "--config.file=/data/prometheus/config.yaml"
    volumes:
      - /path/to/config/prometheus.yaml:/data/prometheus/config.yaml:z,rw
      - /path/to/data/prometheus:/data/prometheus:z,rw
    restart: unless-stopped
    userns_mode: keep-id:uid=65534

  otelcol-contrib:
    container_name: otelcol-contrib
    image: open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.123.0
    ports:
      - 4317:4317
      - 4318:4318
    command:
      - "--config=/etc/otelcol-contrib/config.yaml"
    volumes:
      - /path/to/config/otelcol-contrib.yaml:/etc/otelcol-contrib/config.yaml:z,rw
    restart: unless-stopped
    networks: metrics

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    ports:
      - 3200:3200
      - 4417:4417
      - 4418:4418
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - /path/to/config/tempo.yaml:/etc/tempo.yaml:z,rw
      - /path/to/data/tempo:/data/tempo:z,rw
    restart: unless-stopped
    userns_mode: keep-id:uid=10001

   grafana:
     container_name: grafana
     image: grafana/grafana-enterprise
     ports:
       - 3001:3000
     volumes:
       - /path/to/data/grafana:/var/lib/grafana:z,rw
     restart: unless-stopped
     userns_mode: keep-id:uid=472

networks:
  metrics:
    external: true 
````
I have open-webui running in separate container on the `metrics` network. 

If you are looking for a quick setup for testing and don't want to worry about config files then you can also run
````
#!/bin/bash

RELEASE=${1:-latest}

podman pull docker.io/grafana/otel-lgtm:"${RELEASE}"

touch .env

podman run \
        --network <your-network> \
        --replace \
        --name lgtm \
        -p 3001:3000 \
        -p 4317:4317 \
        -p 4318:4318 \
        --rm \
        -dt \
        docker.io/grafana/otel-lgtm:"${RELEASE}"
````
This is almost taken straight from the `run-lgtm.sh` file in [https://github.com/grafana/docker-otel-lgtm](https://github.com/grafana/docker-otel-lgtm).

**Comment by varampati6** [comment]
I got the error below for the configuration, which is attached below.

docker-compose.yaml:

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.6.2
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
     - /data/openwebui/data:/app/backend/data
    restart: unless-stopped
    extra_hosts:
     - "host.docker.internal:host-gateway"
    environment:
      - USER_AGENT=myagent
      - ENABLE_OTEL=true
      - OTEL_SERVICE_NAME=open-webui
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://us-hostname-1.com:4317
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://us-hostname-1.com:4317/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=service.name=open-webui
      - OTEL_LOG_LEVEL=debug
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - otel-network
networks:
  otel-network:
    driver: bridge

Open WebUI container log:

2025-04-14 13:51:58.631 | INFO     | open_webui.utils.logger:start_logger:140 - GLOBAL_LOG_LEVEL: DEBUG - {}
2025-04-14 13:51:58.631 | DEBUG    | open_webui.socket.main:periodic_usage_pool_cleanup:117 - Running periodic_usage_pool_cleanup - {}
2025-04-14 13:52:09.306 | WARNING  | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:328 - Transient error StatusCode.UNAVAILABLE encountered while exporting traces to us-hostname-1.com:4317, retrying in 1s. - {}
2025-04-14 13:52:10.307 | WARNING  | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:328 - Transient error StatusCode.UNAVAILABLE encountered while exporting traces to us-hostname-1.com:4317, retrying in 2s. - {}
2025-04-14 13:52:12.308 | WARNING  | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:328 - Transient error StatusCode.UNAVAILABLE encountered while exporting traces to us-hostname-1.com:4317, retrying in 4s. - {}
2025-04-15 05:06:44.297 | ERROR    | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:341 - Failed to export traces to us-hostname-1.com:4317, error code: StatusCode.UNIMPLEMENTED - {}
2025-04-15 05:06:54.202 | ERROR    | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:341 - Failed to export traces to us-hostname-1.com:4317, error code: StatusCode.UNIMPLEMENTED - {}
2025-04-15 05:07:19.203 | ERROR    | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:341 - Failed to export traces to us-hostname-1.com:4317, error code: StatusCode.UNIMPLEMENTED - {}
2025-04-15 05:07:24.203 | ERROR    | opentelemetry.exporter.otlp.proto.grpc.exporter:_export:341 - Failed to export traces to us-hostname-1.com:4317, error code: StatusCode.UNIMPLEMENTED - {}

**Comment by mahenning** [comment]
For everyone still wondering how this works (including myself):

https://jorgedelacruz.uk/2025/02/15/looking-for-the-perfect-dashboard-influxdb-telegraf-and-grafana-part-xlvii-monitoring-open-webui/

This is a blog post of the person who wrote the OWUI grafana dashboard. Apparently, it uses a bash script to scrape all the chats and put the extracted information into the InfluxDB. It seems this is not using the telemetry of OWUI at all.

**Comment by Soliver84** [comment]
The experimental integration has been integrated into openwebui for 14 hours now. It would be great if the programmer could provide a dashboard and a quick guide.

**Comment by SuperPat45** [comment]
Can you provide a docker compose example?

**Comment by JTHesse** [comment]
This is working for me:

```
services:

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - openwebui:/app/backend/data
    environment:
      - ENABLE_OTEL=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://grafana:4317
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  grafana:
    image: grafana/otel-lgtm
    ports:
       - 3000:3000

volumes:
  openwebui:
```

However, the used models or number of tokens is not received.
