### DISCUSSION TITLE
deploying ollama web ui from helm chart with argo cd never sync

### DISCUSSION THREAD

**Discussion by didlawowo** [open-webui/open-webui#1236] [General]
# Bug Report

i deployed ollamo using helm chart with argo cd

## Description

the item never sync totally the pvc declaration seems to be wrong

**Bug Summary:**
dployment is good, but not sync, pb on pvc template

<img width="1139" alt="image" src="https://github.com/open-webui/open-webui/assets/12622760/4f32e1a5-6a90-4579-8224-52270fba5f25">

**Steps to Reproduce:**
deployed chart using argocd

**Expected Behavior:**
sync full

**Actual Behavior:**
see screenshot it loop over the diff sync

## Environment
k3S 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-webui
  namespace: kube-infra
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  project: mlops
  source:
    path: charts/open-webui
    repoURL: git@github.com:didlawowo/continuous-delivery.git
    targetRevision: main
    helm:
      values: |
        ollama:
          persistence:
            enabled: true
          nodeSelector:
            kubernetes.io/hostname: nvidia
          runtimeClassName: nvidia
          gpu:
            enabled: true
          resources:
            limits:
              nvidia.com/gpu: 1
          models:
          - llava

        webui:

          enabled: true
          ingress:
            className: traefik
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            host: ollama-webui.home.oursain.net

            tls:
              enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!
