### DISCUSSION TITLE
Citations / sources not showing up in v0.5.20 (but they do in v0.4.8)

### DISCUSSION THREAD

**Discussion by Soap2G** [open-webui/open-webui#12445] [Issues]
### TL;DR:
From the console logs, `Object { sources: (4) […] }` apprears in v0.4.8, but it doesn't in v0.5.20

The only major change is websockets; could this be something related to that?
Otherwise I'm deploying the various versions on the same infrastructure, and I'm getting payloads from the same API endpoint.

### Check Existing Issues

- [x]  I have searched the existing issues and discussions.

### Installation Method

Helm Charts

### Open WebUI Version
0.5.20

### Chart Version
5.21.0

### Where do you deploy the infrastructure

OKD

### Browser (if applicable)
Firefox, Chrome

### Confirmation

- [x]  I have read and followed all instructions in `README.md`.
- [x] I have included the browser console logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

Citations should show up in  v0.5.20, as they do in v0.4.8.

The JSON provided is of this type:
```json
{
  "output": {
    "confidence": [
      0.745,
      0.722,
      0.715
    ],
    "context": "...",
    "instruction": "<question>",
    "question_keyphrases": "...",
    "response": "...",
    "urls": [
      "...",
      "...",
      "..."
    ]
  }
}
```

### Actual Behavior
Citations not showing up in  v0.5.20, but they do in v0.4.8. API endpoint is the same in both cases.

### Steps to Reproduce
Here's my helm chart:
```yaml
open-webui:
  nameOverride: "open-webui-dev"
  annotations:
    rollme: "{{ randAlphaNum 5 | quote }}"
  ollama:
    # -- Automatically install Ollama Helm chart from https://otwld.github.io/ollama-helm/. Use [Helm Values](https://github.com/otwld/ollama-helm/#helm-values) to configure
    enabled: false
  pipelines:
    # -- Automatically install Pipelines chart to extend Open WebUI functionality using Pipelines: https://github.com/open-webui/pipelines
    enabled: false
  ingress:
    enabled: true
    host: "something"
    tls: false
    annotations:
      route.openshift.io/termination: edge
      haproxy.router.openshift.io/ip_whitelist: ""
  persistence:
    enabled: false
  image:
    repository: "something"
    tag: "dev" 
    pullPolicy: "Always"
  replicaCount: 1 

  websocket:
    enabled: true
    manager: redis
    url: redis://open-webui-redis:6379/0
    redis:
      enabled: true
      name: open-webui-redis
      args: [ "--save", "" ]
  service:
    type: ClusterIP  # recommended ClusterIP when using OpenShift Routes  
    port: 8080

  openaiBaseApiUrl: ""
  extraEnvVars:
    - name: ENABLE_OAUTH_SIGNUP
      value: "true"
    - name: OPENID_PROVIDER_URL
      value: xxx
    - name: OAUTH_PROVIDER_NAME
      value: xxx
    - name: OAUTH_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: oidc-client-secret
          key: clientID
    - name: OAUTH_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: oidc-client-secret
          key: clientSecret
    # Logging settings
    - name: GLOBAL_LOG_LEVEL
      value: debug
    # General settings
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: db-secret-dev
          key: dbfullstring
    - name: ENABLE_LOGIN_FORM
      value: "false"
    - name: DEFAULT_USER_ROLE
      value: "user"
    # User settings
    - name: DEFAULT_MODELS
      value: accgpt
    # Connection settings
    - name: OPENAI_API_BASE_URLS
      value: "http:/xxx:8000/v1;http://xxx:3222;https://api.openai.com/v1"
    - name: OPENAI_API_KEYS    
      valueFrom:
        secretKeyRef:
          name: openai-api-keys
          key: openai-api-keys
    - name: TASK_MODEL_EXTERNAL
      value: "/models/Meta-Llama-3.1-8B-Instruct"
```

### Logs & Screenshots

Relevant logs from v0.4.8
```sh
Object { id: 58, object: "chat.completion.chunk", created: 1743432245.573347, model: "accgpt_v0_0_55", choices: (1) […] }
Help.6Go9sj4i.js:5:760
Object { sources: (4) […] }
Help.6Go9sj4i.js:5:760
usage 
Object { models: (1) […] }
0.odnS2zZ4.js:1:40549
usage 
```

Same logs from v0.5.20
```sh
Object { done: true, content: "something.", title: "New chat" }
Help.DNJn_PVO.js:144:1476
usage 
Object { models: [] }
0.DhqISB5E.js:1:47512
```

### Additional Information

`Object { sources: (4) […] }` apprears in v0.4.8, but it doesn't in v0.5.20

The only major change is websockets; could this be something related to that?
