### DISCUSSION TITLE
feat: ROCm /w RAG and SentenceTransformers

### DISCUSSION THREAD

**Discussion by Schwenn2002** [open-webui/open-webui#12798] [Ideas]
Unfortunately, ROCM is only supported for ollama, but that works fine.

For RAG, the SentenceTransformers are unfortunately only implemented with CUDA, otherwise you only have the CPU. SentenceTransformers with CUDA are also faster than ollama with ROCM and the reranking also runs on CPU.

In any case, I have the effect that about 100 documents (100k-10MB) are processed for a very long time in the RAG before the LLM (regardless of whether 3B, 8B or 22B) is executed on a Radeon Pro W7900 with 48GB VRAM.

PyTorch can do ROCM: https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/3rd-party/pytorch-install.html

**Comment by Schwenn2002** [comment]
Another Link:

https://rocm.blogs.amd.com/artificial-intelligence/sentence_transformers_amd/README.html

**Comment by Schwenn2002** [comment]
If I rebuild the Docker with the attached Dockerfile (docker-compose up --build open-webui-rocm) and then call the embedding model via the console, it is loaded with GPU, obviously ROCm in torch also uses CUDA.

### **docker-compose.yaml:**
```
services:

  open-webui-rocm:
    build:
      context: .
      dockerfile: ./open-webui-rocm/Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-rocm
    ipc: host
    volumes:
      - /data/open-webui-rocm/data:/app/backend/data
    ports:
      - 4443:8080
    environment:
      - 'WEBUI_NAME=xxxx'
      - 'WEBUI_URL=https://xxxx'
      - 'OLLAMA_BASE_URL=http://x.x.x.x:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ROCR_VISIBLE_DEVICES=1'
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.0'
      - 'HSA_ENABLE_SDMA=0'
      - 'RAG_EMBEDDING_MODEL=ibm-granite/granite-embedding-278m-multilingual'
      - 'GLOBAL_LOG_LEVEL=DEBUG'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - 993
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```

### **Dockerfile**
```
FROM ghcr.io/open-webui/open-webui:main

RUN apt update
RUN apt install -y wget
RUN apt install -y gpg

RUN apt install -y python3-setuptools python3-wheel libpython3.11

WORKDIR /app/backend
RUN wget https://repo.radeon.com/amdgpu-install/6.3.1/ubuntu/jammy/amdgpu-install_6.3.60301-1_all.deb
RUN apt install -y ./amdgpu-install_6.3.60301-1_all.deb
RUN amdgpu-install -y --usecase=rocm,hip,opencl --no-dkms

RUN pip3 uninstall -y torch torchvision torchaudio
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2 --no-cache-dir

RUN python -c "from datasets import load_dataset"
RUN python -c "from sentence_transformers import InputExample, util"
RUN python -c "from torch.utils.data import DataLoader"
RUN python -c "from torch import nn"
RUN python -c "from sentence_transformers import losses"
RUN python -c "from sentence_transformers import SentenceTransformer, models"
```

### **ROCm Test with torch and cuda:**
```
docker exec -it open-webui-rocm /bin/bash

root@3ac111a1e730:/app/backend# python
Python 3.11.11 (main, Dec 24 2024, 22:24:26) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sentence_transformers import SentenceTransformer
>>> import torch
>>> print("CUDA aktiviert:", torch.cuda.is_available())
CUDA aktiviert: True
>>> model = SentenceTransformer('ibm-granite/granite-embedding-278m-multilingual')
>>> print("Model runs on GPU:", next(model.parameters()).is_cuda)
Model runs on GPU: True
```

![Image](https://github.com/user-attachments/assets/c853ee85-7170-4138-bcc6-bc893136eece)
![Image](https://github.com/user-attachments/assets/e1fe865d-cb07-43c2-8e59-b54a170ffc5f)

### open-webui
**The CPU is still used via open-webui (why?).** Is it hard coded that the model runs on the CPU?

**Comment by Schwenn2002** [comment]
**Additional information:** 

For python 3.11 you need the installation package for ROCm6.3. For torch2.5.1 there are only packages for ROCm6.2. According to my research, ROCm is compatible. This is also confirmed by the fact that the embedding model with CUDA support is loaded by SentenceTransformers.

How do I tell open-webui to use the GPU?

**Comment by oatmealm** [comment]
USE_DOCKER_CUDA worked for me as in open-WebUI acknowledged and checked if the gpu is enabled, but on my hardware it only worked once and stopped after restarting the server and simply hangs after attempting to load the libraries. You also need to make sure your pip installed the corresponding libraries of PyTorch that are built for rocm of course.

**Comment by Schwenn2002** [comment]
Thank you very much, now the Docker from open-webui actually runs with ROCm. 

**Perhaps an open-webui:rocm can be built?**

The adjustments are specified in the Dockerfile above (usecase=rocm should be sufficient for amdgpu-install).

**Comment by oatmealm** [comment]
You can also use it outside docker. Works the same. But as mentioned for me it caused problems. I think you can simply adapt the existing Dockerfile for this use case. Provided you also make sure to install the PyTorch libraries (torch, torchvision ... ) from the alternative pip index.

**Comment by Schwenn2002** [comment]
I have already customized Docker and integrated ROCm with the Dockerfile mentioned above.

It would only be good for updates if I didn't have to do a rebuild every time an update for open-webui is released. 

With the Dockerfile above it should be easy to offer ROCm as a standard container (just like we do with CUDA like open-webui:rocm with a Tag). That would help everyone...

**Comment by oatmealm** [comment]
BTW, just for completion for people who run opwenwebui on bare metal, downgrading pytorch-rocm to 2.4.x solved the problem and gpu doesn't segfault.

**Comment by Schwenn2002** [comment]
Attached are my updated files, the Docker must then be started with docker-compose up -d --build!

**Testing ROCm in a container:**
```
docker exec -it open-webui-rocm /bin/bash

root@3ac111a1e730:/app/backend# python
Python 3.11.11 (main, Dec 24 2024, 22:24:26) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sentence_transformers import SentenceTransformer
>>> import torch
>>> print("CUDA aktiviert:", torch.cuda.is_available())
CUDA aktiviert: True
>>> model = SentenceTransformer('ibm-granite/granite-embedding-278m-multilingual')
>>> print("Model runs on GPU:", next(model.parameters()).is_cuda)
Model runs on GPU: True
```
Or try the ROCm commands in the container:
```
docker exec -it open-webui-rocm /bin/bash
rocm-smi
```

**docker-compose.yaml**
```
  open-webui-rocm:
    build:
      context: .
      dockerfile: ./open-webui-rocm/Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-rocm
    ipc: host

    volumes:
      - /data/open-webui-rocm/data:/app/backend/data
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
    ports:
      - 3000:8080
    environment:
      - 'USE_CUDA=true'
      - 'USE_CUDA_VER=rocm6.2'
      - 'USE_CUDA_DOCKER=true'
      - 'USE_CUDA_DOCKER_VER=rocm6.2'
      - 'WEBUI_NAME=ollama.xxx.xx'
      - 'WEBUI_URL=https://ollama.xxx.xx'
      - 'OLLAMA_BASE_URL=http://x.x.x.x:11434'
      - 'WEBUI_SECRET_KEY='
      - 'REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt'
      # only one ROCM-Device !!!       
      - 'ROCR_VISIBLE_DEVICES=1'
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.0'
      - 'HSA_ENABLE_SDMA=0'
      - 'RAG_EMBEDDING_MODEL=ibm-granite/granite-embedding-278m-multilingual'
      - 'WEBUI_SESSION_COOKIE_SECURE=true'
      # only if redis enabled
      #- 'ENABLE_WEBSOCKET_SUPPORT=true'
      #- 'WEBSOCKET_MANAGER=redis'
      #- 'WEBSOCKET_REDIS_URL=redis://redis:6379/2'
      - 'GLOBAL_LOG_LEVEL=ERROR'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - 993
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```

**Dockerfile**
```
FROM ghcr.io/open-webui/open-webui:main

# Start
RUN apt update
RUN apt install -y wget
RUN apt install -y gpg

RUN apt install -y python3-setuptools python3-wheel libpython3.11

WORKDIR /app/backend
RUN wget https://repo.radeon.com/amdgpu-install/6.3.1/ubuntu/jammy/amdgpu-install_6.3.60301-1_all.deb
RUN apt install -y ./amdgpu-install_6.3.60301-1_all.deb
RUN amdgpu-install -y --usecase=rocm,hip --no-dkms

# Install pytorch ROCM
# Prüfe Torch-Version und installiere ROCm, falls '+cpu' gefunden wird
RUN if pip show torch | grep 'Version' | grep -q '+cpu'; then \
        pip3 uninstall -y torch torchvision torchaudio && \
        pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm6.2.4 --no-cache-dir; \       
    else \
        echo "nothing to do..."; \
    fi
```
