### DISCUSSION TITLE
issue: 400: Invalid 'stop': array too long when using Workspace model specifically

### DISCUSSION THREAD

**Discussion by theprezz87** [open-webui/open-webui#13157] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.6.5

### Operating System

Almalinux

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

Autocomplete to work in continue.dev

### Actual Behavior

{"detail":"400: Invalid 'stop': array too long. Expected an array with maximum length 4, but got an array with length 10 instead."} when using a **Workspace** model **only**

### Steps to Reproduce

If I am using open webui API with an openai model directly and activate the autocomplete with Continue.dev, it works fine. If I create a model in **Workspace** using the very same openai model and use the **Workspace** custom name model in Continue.dev, I get {"detail":"400: Invalid 'stop': array too long. Expected an array with maximum length 4, but got an array with length 10 instead."}

### Logs & Screenshots

```
name: Generic AutoComplete
    provider: openai
    model: gpt-4-turbo
    apiBase: https://api-to-open-webui/api
    apiKey: sk-xxx
    env:
      useLegacyCompletionsEndpoint: false
    roles:
      - autocomplete
```
Works

```
name: Generic AutoComplete
    provider: openai
    model: workshop-model-using-gpt-4-turbo-with-nothing-else
    apiBase: https://api-to-open-webui/api
    apiKey: sk-xxx
    env:
      useLegacyCompletionsEndpoint: false
    roles:
      - autocomplete
```
{"detail":"400: Invalid 'stop': array too long. Expected an array with maximum length 4, but got an array with length 10 instead."}
