### DISCUSSION TITLE
k8s deployment: web ui returns empty content

### DISCUSSION THREAD

**Discussion by davidshen84** [open-webui/open-webui#13210] [Q&A]
Hi,

I have a simple deployment like the following:

```yaml
open-webui:
  ollama:
    enabled: false

  ollamaUrls:
    - http://ollama.ollama.svc.cluster.local:11431

  service:
    type: LoadBalancer

  ingress:
    enabled: false

  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 1Gi
```

I have my own ollama instance in the same cluster. After I applied the chart, all pods are in *healthy* state. But when I try to access the open-webui server, I get an empty response. There's no access/error log in the pod.

If I use port-forward and access localhost:8080, the port-forward process will be terminated when I try to make requests to it. It's like the open-webui pod actively tries to block me.

Am I missing anything?

Thanks
