### DISCUSSION TITLE
Documents for workspace knowledge processing

### DISCUSSION THREAD

**Discussion by redolencetech** [open-webui/open-webui#13668] [Q&A]
Hey all,

I'm now starting to explore OpenWebUI for hosting my own LLMs internally (I have OW running on a VM housing all my Docker instances, Ollama with all my models on a separate machine with a GPU), and I am trying to set up workspace knowledge with my internal data - we have a set of handbooks and guidelines detailing all our manufacturing processes, expected product specs etc, and I'd like to seed them into a workspace so that users can query across the datasets. I have set up my Portainer stack as below:

```
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "5000:8080"
    volumes:
      - /home/[user]/docker/open-webui:/app/backend/data
    environment:
      - ENABLE_ONEDRIVE_INTEGRATION=true
      - ONEDRIVE_CLIENT_ID=[client ID]
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped
  docling:
    image: quay.io/docling-project/docling-serve
    ports:
      - "5001:5001"
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
```

I've tried to set up document processing via Docling (using http://192.168.1.xxx:5001/) and Tika (using http://192.168.1.xxx:9998/tika), however in both cases documents don't upload into my workspace. I have also enabled OneDrive in the application settings but it doesn't show up as an option - ideally I'd like to point it to a folder with all of my background information and let it digest the entire dataset, but that's a separate goal
