### DISCUSSION TITLE
issue: Unable to create new account, even on fresh install

### DISCUSSION THREAD

**Discussion by iamronr** [open-webui/open-webui#13811] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

0.6.9

### Operating System

MacOS

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

Start container and go to open web login screen. I'm expecting to see login with username and password OR `If you don't have an account, sign up`

### Actual Behavior

I'm taken to the login screen, but I can't create a new account, even from a fresh install.

### Steps to Reproduce

Just go to login screen. 

### Logs & Screenshots

```
open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    env_file: .env
    environment:
      - PUID=911
      - PGID=1001
      - UMASK=002
      - ENV=prod
      # - OLLAMA_BASE_URL=${RMEDIAIPH}:11434
      - WEBUI_SECRET_KEY=${RMEDIASECRET}
      # - ENABLE_SIGNUP=True
      # - ENABLE_OAUTH_SIGNUP=True
      # - ENABLE_LOGIN_FORM=True
      # - DEFAULT_USER_ROLE=pending
      - WEBUI_NAME=rGPT
    extra_hosts:
      - host.docker.internal:${RMEDIAIP}
    ports:
      - 3030:8080
    volumes:
      - ${RMEDIAS}/open-webui:/app/backend/data
    restart: unless-stopped
```

![Image](https://github.com/user-attachments/assets/2a913fc4-3a3e-4492-9b34-82cd4fac27b0)
