### DISCUSSION TITLE
MCP调用工具报错

### DISCUSSION THREAD

**Discussion by Kun-Zhang-x** [open-webui/open-webui#13865] [Issues]
**openwebui==0.6.5
mcpo==0.0.13
vllm==0.8.5
模型为qwq32b和qwen3-32b**

**openwebui->设置->高级参数->function calling设置为原生，调用工具报错**

**vllm启动脚本如下:**
```
version: '3'
services:
  vllm:
    container_name: qwen3
    restart: always
    image: vllm/vllm-openai:v0.8.5
    ipc: host
    volumes:
      - /data/soft/Qwen3-32B:/models/Qwen3-32B
    command: ["--model", "/models/Qwen3-32B", "--served-model-name", "Qwen/Qwen3-32B", "--max-model-len", "29999", "--max-num-seqs", "32", "--gpu-memory-utilization", "0.90", "--tensor-parallel-size", "2", "--pipeline-parallel-size", "3", "--kv-cache-dtype", "auto", "--trust-remote-code", "--enable-auto-tool-choice", "--tool-call-parser", "hermes","--enable-reasoning","--reasoning-parser","deepseek_r1"]
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

**界面显示如图所示**
![image](https://github.com/user-attachments/assets/c1f4589b-e50d-425f-9ea3-d1d56cca1010)

**vllm报错日志如下：**
ERROR 05-09 04:25:03 [serving_chat.py:200] Error in preprocessing prompt inputs
ERROR 05-09 04:25:03 [serving_chat.py:200] Traceback (most recent call last):
ERROR 05-09 04:25:03 [serving_chat.py:200]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/serving_chat.py", line 183, in create_chat_completion
ERROR 05-09 04:25:03 [serving_chat.py:200]     ) = await self._preprocess_chat(
ERROR 05-09 04:25:03 [serving_chat.py:200]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-09 04:25:03 [serving_chat.py:200]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/serving_engine.py", line 403, in _preprocess_chat
ERROR 05-09 04:25:03 [serving_chat.py:200]     conversation, mm_data_future = parse_chat_messages_futures(
ERROR 05-09 04:25:03 [serving_chat.py:200]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-09 04:25:03 [serving_chat.py:200]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/chat_utils.py", line 1165, in parse_chat_messages_futures
ERROR 05-09 04:25:03 [serving_chat.py:200]     sub_messages = _parse_chat_message_content(
ERROR 05-09 04:25:03 [serving_chat.py:200]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-09 04:25:03 [serving_chat.py:200]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/chat_utils.py", line 1105, in _parse_chat_message_content
ERROR 05-09 04:25:03 [serving_chat.py:200]     result_msg["tool_calls"] = list(parsed_msg["tool_calls"])
ERROR 05-09 04:25:03 [serving_chat.py:200]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 05-09 04:25:03 [serving_chat.py:200] pydantic_core._pydantic_core.ValidationError: 1 validation error for ValidatorIterator
ERROR 05-09 04:25:03 [serving_chat.py:200] 0.function.arguments
ERROR 05-09 04:25:03 [serving_chat.py:200]   Field required [type=missing, input_value={'name': 'tool_get_table_schema_post'}, input_type=dict]
ERROR 05-09 04:25:03 [serving_chat.py:200]     For further information visit https://errors.pydantic.dev/2.11/v/missing
INFO:     10.5.100.67:9246 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
INFO 05-09 04:25:03 [logger.py:39] Received request chatcmpl-4e9a67f12fc1442ea00f4b20f734237c: prompt: '<|im_start|>user\n### Task:\nGenerate a concise, 3-5 word title with an emoji summarizing the chat history.\n### Guidelines:\n- The title should clearly represent the main theme or subject of the conversation.\n- Use emojis that enhance understanding of the topic, but avoid quotation marks or special formatting.\n- Write the title in the chat\'s primary language; default to English if multilingual.\n- Prioritize accuracy over excessive creativity; keep it clear and simple.\n### Output:\nJSON format: { "title": "your concise title here" }\n### Examples:\n- { "title": "?? Stock Market Trends" },\n- { "title": "?? Perfect Chocolate Chip Recipe" },\n- { "title": "Evolution of Music Streaming" },\n- { "title": "Remote Work Productivity Tips" },\n- { "title": "Artificial Intelligence in Healthcare" },\n- { "title": "?? Video Game Development Insights" }\n### Chat History:\n<chat_history>\nUSER: 使用get_table_name工具获取案件基本信息的表名\nASSISTANT: <details type="tool_calls" done="true" id="chatcmpl-tool-1b249cf373a14e20ae7efb97dd89d74a" name="tool_get_table_schema_post" arguments="&quot;&quot;" result="&quot;{\\n  \\&quot;error\\&quot;: \\&quot;Request body expected for operation &#x27;tool_get_table_schema_post&#x27; but none found.\\&quot;\\n}&quot;" files="">\n<summary>Tool Executed</summary>\n</details>\n</chat_history><|im_end|>\n<|im_start|>assistant\n', params: SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.6, top_p=0.95, top_k=20, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1000, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=None, extra_args=None), prompt_token_ids: None, lora_request: None, prompt_adapter_request: None.
INFO 05-09 04:25:03 [async_llm_engine.py:211] Added request chatcmpl-4e9a67f12fc1442ea00f4b20f734237c.

**但是奇怪的是，当我把模型配置成阿里百炼的同型号模型就没有问题**

下面是我找到的两个相似的issue，但是并没有合适的解决方案：
[https://github.com/open-webui/open-webui/issues/13125](url)
[https://github.com/open-webui/open-webui/issues/13732](url)
