### DISCUSSION TITLE
issue: logout returns 500 error unless user delete his cookie with SSO

### DISCUSSION THREAD

**Discussion by yalattas** [open-webui/open-webui#13974] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Other

### Open WebUI Version

v0.6.5

### Operating System

K8s environment

### Browser (if applicable)

Brave

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

Logout user once user clicks on logout button.

### Actual Behavior

System is returning 500 to logout.

I am using Google SSO only without setting the following environment variable `OPENID_PROVIDER_URL`

chart only set client key and client secret

### Steps to Reproduce

use open-webui helm chart

configure google SSO.

login

then logout

### Logs & Screenshots

response from signout endpoint
```
{"detail":"Failed to sign out from the OpenID provider."}
```

### Additional Information

the line causing the issue is here
https://github.com/open-webui/open-webui/blob/4ce1e88750c6da2f94b834697902ceb9f5524726/backend/open_webui/routers/auths.py#L571C44-L571C63

**Comment by yalattas** [comment]
quick solution just to add the following env var if you're using google. Yet, chart should handle this case

```Yaml
extraEnvVars:
    - name: OPENID_PROVIDER_URL
      value: "https://accounts.google.com/.well-known/openid-configuration"
```

**Comment by michael-pisman** [comment]
Same issue with GitHub SSO

@yalattas solution by setting `OPENID_PROVIDER_URL` also works.

```yaml
extraEnvVars:
  - name: OPENID_PROVIDER_URL
    values: "https://github.com/login/oauth/.well-known/openid-configuration"
```
