### DISCUSSION TITLE
What are the available values for WHISPER_MODEL in Docker configuration?

### DISCUSSION THREAD

**Discussion by seth100** [open-webui/open-webui#14128] [Q&A] [answered]
Hi,

I'm using the following Docker Compose configuration:

```yml
open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - 8080:8080
    environment:
      OLLAMA_BASE_URL: 'http://ollama:11434'
      WHISPER_MODEL: 'large-v3'
      WHISPER_MODEL_AUTO_UPDATE: True
      WHISPER_LANGUAGE: 'it'
    volumes:
      - ./data:/app/backend/data
    env_file:
      - .env 
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```

and I'd like to know what values I could use for `WHISPER_MODEL`, since the `base` one is not recognizing correctly the words I say (italian language), so I'd like to try something more powerful.
Besides, if I want something like `large-v3` or `large-v3-turbo`, do I need to install it manually in the Docker container? If so, how?

Thanks
