### DISCUSSION TITLE
issue: User hangs on creation

### DISCUSSION THREAD

**Discussion by RamboRogers** [open-webui/open-webui#14504] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.6.12 (latest)

### Operating System

RKE2

### Browser (if applicable)

Chrome

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

A user is added.

### Actual Behavior

Container hangs.

### Steps to Reproduce

Running container in RKE2, whenever I add a user, I get a hardlock the last 3 versions.  Not sure what's going on?

### Logs & Screenshots

0._b3aThe7.js:2 Backend config: Object
12:27:34.237 0._b3aThe7.js:1 connected o_2SJYK7dBz8EeCBAAAD
12:28:19.262 0._b3aThe7.js:1 Socket undefined disconnected due to ping timeout
12:28:41.263 0._b3aThe7.js:1 connect_error Error: timeout
    at CGwCSIWv.js:1:37620
12:29:05.261 0._b3aThe7.js:1 connect_error Error: timeout
    at CGwCSIWv.js:1:37620
12:29:32.259 0._b3aThe7.js:1 connect_error Error: timeout
    at CGwCSIWv.js:1:37620
12:30:22.999 0._b3aThe7.js:1 connect_error Error: timeout
    at CGwCSIWv.js:1:37620

Container Logs:

│ 2025-05-29 16:27:30.547 | INFO     | open_webui.routers.openai:get_all_models:391 - get_all_models() - {}                                               │
│ 2025-05-29 16:27:30.547 | INFO     | open_webui.routers.ollama:get_all_models:323 - get_all_models() - {}                                               │
│ 2025-05-29 16:27:30.870 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:53351 - "GET /api/v1/chats/e60914a5-c024-427f-b1f5-358a │
│ 2025-05-29 16:27:31.203 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:53351 - "GET /api/v1/chats/1bd6b931-a133-47c7-b750-8d1c │
│ 2025-05-29 16:27:31.238 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:53351 - "GET /api/v1/chats/03696424-4813-47c8-8a4c-06f9 │
│ 2025-05-29 16:27:31.319 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /api/models HTTP/1.1" 200 - {}             │
│ 2025-05-29 16:27:32.739 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /_app/version.json HTTP/1.1" 200 - {}      │
│ 2025-05-29 16:27:34.082 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /api/v1/auths/signout HTTP/1.1" 200 - {}   │
│ 2025-05-29 16:27:34.100 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /auth HTTP/1.1" 200 - {}                   │
│ 2025-05-29 16:27:34.138 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /static/loader.js HTTP/1.1" 304 - {}       │
│ 2025-05-29 16:27:34.143 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /static/splash.png HTTP/1.1" 304 - {}      │
│ 2025-05-29 16:27:34.173 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /static/splash-dark.png HTTP/1.1" 304 - {} │
│ 2025-05-29 16:27:34.220 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /api/config HTTP/1.1" 200 - {}             │
│ 2025-05-29 16:27:34.239 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /ws/socket.io/?EIO=4&transport=polling&t=P │
│ 2025-05-29 16:27:34.244 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "GET /static/favicon-dark.png HTTP/1.1" 304 - { │
│ 2025-05-29 16:27:34.255 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:52522 - "POST /ws/socket.io/?EIO=4&transport=polling&t= │
│ 2025-05-29 16:27:34.255 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - 10.42.0.0:53351 - "GET /ws/socket.io/?EIO=4&transport=polling&t=P │
│ 2025-05-29 16:27:47.234 | INFO     | open_webui.models.auths:insert_new_auth:108 - insert_new_auth - {}

**Comment by RamboRogers** [comment]
I restart the container and I can log in as the user no problem.

**Comment by rgaricano** [comment]
If it's solved (probably cookie or cache issue), then, please, close the topic. 
(it unload the review work for the maintainer)

**Comment by RamboRogers** [comment]
No, not solved, repeats with a new user.

**Comment by trevor-hornbill** [comment]
I was getting the same issue, turned out i had the Webhook URL set to an invalid URL, clearing this stopped the hanging on user creation.

**Comment by wxfvf** [comment]
The same issue. I upgraded from version v3.x, and encountered this problem right after upgrading to v5.10. It still exists in version 6.14 as well. However, the issue does not occur with fresh installations.

**Reply by wxfvf** [reply]
I tried it: when I imported the configuration from the newly created open-webui container into the old one, the issue disappeared.  when I imported the old configuration into the new container and set the access port to 80, the issue could be reproduced.

**Comment by biebiep** [comment]
I'm seeing this same issue on a new deployment with keycloak following the keycloak guide on the docs. Unsure if its the issue that leads up to this, but the result is the same.

this is my example docker-compose:

```
services:

  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: changeme
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

    command: ['start-dev']
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - 8080:8080
    networks:
      - openwebui_backend
    restart: unless-stopped

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    environment:
      WEBUI_SECRET_KEY: changeme
      PORT: "8000"
      LOG_LEVEL: "DEBUG"
      # Keycloak / OIDC settings
      OAUTH_CLIENT_ID: openwebui
      OAUTH_CLIENT_SECRET: secret
      OPENID_PROVIDER_URL: http://myIP:8080/realms/openwebui/.well-known/openid-configuration
      OPENID_REDIRECT_URI: http://myIP:8000/oauth/oidc/callback
      ENABLE_OAUTH_SIGNUP: "true"
      OAUTH_SCOPES: "openid email profile" 
    volumes:
      - openwebui_data:/app/backend/data
    ports:
      - 8000:8000
    networks:
      - openwebui_backend
    depends_on:
      - keycloak
    restart: unless-stopped
volumes:
 keycloak_data:
 openwebui_data:
networks:
 openwebui_backend:
```
 
 
 The user account creation then hangs the entire application (also from other machines) for 5 minutes until the post_webhook after the "open_webui.models.auths:insert_new_auth:108 - insert_new_auth - {}" times out. Restarting the openwebui container clears the lock and allows login, so the user has been created.
