### DISCUSSION TITLE
issue: Text streaming choppy during call

### DISCUSSION THREAD

**Discussion by choyuansu** [open-webui/open-webui#14506] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

v0.6.11
Issue persists in v0.6.12

### Operating System

Ubuntu 24.04

### Browser (if applicable)

Firefox 136.0.4

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

The generated text is streamed smoothly onto the UI.

### Actual Behavior

The generated text gets stuck for a couple seconds, then continues.

### Steps to Reproduce

docker-compose.yaml
```yaml
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
```

1. `docker compose up -d`, create admin, setup models
2. Click call button and either submit through text or speak

### Logs & Screenshots

https://github.com/user-attachments/assets/67f60b99-12af-4473-be3d-ad81558c94b2

[call-issue-browser.log](https://github.com/user-attachments/files/20496346/call-issue-browser.log)

[call-issue-docker.log](https://github.com/user-attachments/files/20496349/call-issue-docker.log)

### Additional Information

I added logs before and after the audio speech post request [here](https://github.com/open-webui/open-webui/blob/ba0088f39b7a093920b142a5172554686f24df60/backend/open_webui/routers/audio.py#L332-L350) and before the `chat-events` emit [here](https://github.com/open-webui/open-webui/blob/ba0088f39b7a093920b142a5172554686f24df60/backend/open_webui/socket/main.py#L318). I observed that `chat-events` aren't emitted during the audio speech post request, but the speech code seems to be async, so I'm not sure why the event emits are blocked.
