### DISCUSSION TITLE
continue.dev edit option using vscode and openwebui API.

### DISCUSSION THREAD

**Discussion by santosh0787** [open-webui/open-webui#14623] [Q&A]
Hello, 
Has anyone used the Continue.dev extension in VSCode with OpenWebUI as the backend for the 'edit' feature? Chat works fine for me, but autocomplete and edit aren't working.

I'm using openwebui, with openrouter API as connections. Below is my continue.dev config.yaml snippet.

im accessing openwebui from other computer. I tried it on the same computer where OpenWebUI is installed, but I encountered the same issue there as well.

```
  - name: mistralai/codestral-2501
    provider: openai
    model: mistralai/codestral-2501
    apiBase: http://192.168.0.186:3003/api
    apiKey: sk-xxxxxx
    roles:
      - chat
      - apply
      - summarize
      - edit
     env:
      useLegacyCompletionsEndpoint: false
```

with above snippet when I try to do edit I get '405 method not allowed error' . I checked in logs and found error
```
 "Error: Error streaming edit diffs: HTTP 405 Method Not Allowed from http://192.168.0.186:3003/api/completions"
{"detail":"Method Not Allowed"}
```

So I changed apiBase to http://192.168.0.186:3003/api/chat, now I get below error when I do edit: 

```
Error: Error streaming edit diffs: HTTP 400 Bad Request from http://192.168.0.186:3003/api/chat/completions
{"detail":"'messages'"}
```

Using direct openrouter api 'edit' works fine. But has anybody found trick to work with openwebui api?  I didn't tried with ollama as my computer doesn't have enough resources to run LLM locally.
