### DISCUSSION TITLE
Feature Request: Support LiteLLM MCP Gateway with Fixed Endpoint and Team/Key Access Control for MCPO

### DISCUSSION THREAD

**Discussion by flefevre** [open-webui/open-webui#15177] [Ideas]
Hi Open WebUI team 👋,

I'm opening this issue to request support for a recent feature released by [LiteLLM's MCP Gateway](https://docs.litellm.ai/docs/mcp#litellm-proxy---walk-through-mcp-gateway). As of their latest update, the MCP Gateway now supports:

- A fixed endpoint for all model calls (great for simplifying configuration),
- Access control based on API key or Team ID, providing fine-grained control over which users can access which tools/models.

This feature would be extremely helpful to integrate with Open WebUI, especially for organizations that want to centrally manage model access across teams without exposing multiple endpoints or managing model-specific logic at the client/UI level.

**Proposed Integration Points**

- Add support for a single MCP endpoint configuration in the settings , 
- Allow users to specify an API key or Team ID in their WebUI config or headers,
- Detect tool compatibility and route requests accordingly.

**Benefits**

- Simplifies backend integration for teams using LiteLLM,
- Enhances compatibility with enterprise-grade setups,
- Enables better access control and observability via LiteLLM's dashboard.

**Open Question**
One question: I’m not sure if this new LiteLLM MCP Gateway setup is currently compatible with Open WebUI's own [MCPO feature](https://docs.openwebui.com/openapi-servers/mcp). Could you clarify whether these two are interoperable, or if additional work would be needed?

Thanks again, and happy to contribute if this direction aligns with your roadmap!

Thanks again!

**Comment by vipersurfvpn** [comment]
Would really love if this feature could be made available

**Comment by javydekoning** [comment]
It is compatible with the new MCP integration, I just tested the LiteLLM example from the docs and it works:

<img width="722" height="310" alt="image" src="https://github.com/user-attachments/assets/1fabbaa2-10fe-4756-9e4d-3f62fb5ced2e" />

**Comment by pcgeek86** [comment]
I got this working, but only with a single, specific MCP server. I tested it with Tavily. I am still confused about how to aggregate all of the MCP servers + tools into a single endpoint though. What is the correct HTTP URL path to specify, so that all of the configured tools are accessible from a single URL? Isn't the purpose of having an MCP Gateway that you don't have to worry about adding all the MCP servers individually on the MCP client software?

## Create LiteLLM Configuration File

In your LiteLLM configuration file, add this:

```yaml
model_list:
  - model_name: granite4
    litellm_params:
      model: ollama/granite4:latest
      api_base: "http://host.docker.internal:11434"
  - model_name: gemma3
    litellm_params:
      model: ollama/gemma3:latest
      api_base: "http://host.docker.internal:11434"
  # Add others from your list following this pattern

mcp_servers:
  tavily:
    url: https://mcp.tavily.com/mcp/?tavilyApiKey=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

litellm_settings:
  drop_params: True
  set_verbose: True
```

## Run LiteLLM Docker Container

Launch your LiteLLM container, using the Docker Compose snippet below.
I put my LiteLLM configuration file in `./litellm/litellm-config.yaml`, relative to `docker-compose.yml`.

```yaml
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: litellm
    ports:
    - 4000:4000
    volumes:
    - ./litellm/litellm-config.yaml:/app/config.yaml
    environment:
    # ⚠️⚠️ IMPORTANT: Set a secure key here ⚠️⚠️
    - LITELLM_MASTER_KEY=YOUR_CUSTOM_BEARER_TOKEN_HERE
    command: [ "--config", "/app/config.yaml", "--detailed_debug" ]
    extra_hosts:
    - host.docker.internal:host-gateway
    restart: always
```

## Configure OpenWebUI

Go into the OpenWebUI Admin Settings ⚠️ **not the User Settings** ⚠️ 

- Click profile icon in top-right of OpenWebUI
- Select **Admin Panel**
- Click the **Settings** tab
- Click **External Tools**
- Click the "_OpenAPI_" text to change to MCP Streamable HTTP (_see screenshot_)
- Specify the URL: `https://myserver:port/MCP_SERVER_NAME/mcp`
- Specify the **Bearer token** from your LiteLLM container configuration (eg. I am using `LITELLM_MASTER_KEY` environment variable in `docker-compose.yml`)

<img width="713" height="454" alt="image" src="https://github.com/user-attachments/assets/2f504054-7c90-4464-be32-7bc1af98e8ab" />

<img width="896" height="988" alt="image" src="https://github.com/user-attachments/assets/03fdf3fd-a4fd-49a8-bfae-f44b5a73442f" />
