### DISCUSSION TITLE
issue: WEBUI_BANNERS on docker compose

### DISCUSSION THREAD

**Discussion by devbysb** [open-webui/open-webui#15351] [Issues]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

0.6.15

### Operating System

ubuntu 24.04 (docker)

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

No error on docker compose up

### Actual Behavior

yaml: line 13: mapping values are not allowed in this context

### Steps to Reproduce

Hi I have followed https://docs.openwebui.com/getting-started/env-configuration/#webui_banners
With this docker compose yaml file

```
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui/data:/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:8080
    restart: always
    environment:
      - ENABLE_PERSISTENT_CONFIG=false
      - WEBUI_BANNERS="[{\"id\": \"1\", \"type\": \"warning\", \"title\": \"Your messages are stored.\", \"content\": \"Your messages are stored and may be reviewed by human people. LLM's are prone to hallucinations, check sources.\", \"dismissible\": true, \"timestamp\": 1000}]"
```

I have done docker compose up 
And I have this error
yaml: line 13: mapping values are not allowed in this context

### Logs & Screenshots

yaml: line 13: mapping values are not allowed in this context
