### DISCUSSION TITLE
Question: actual container image for Synology - Docker Hub

### DISCUSSION THREAD

**Discussion by marcel293** [open-webui/open-webui#1604] [General]
Are there plans to add the actual container image **_v0.1.119_** to the Docker hub. At the moment there is only the **_v1.0.0-alpha_** available. I would like to use it on my Synology.

[https://hub.docker.com/r/ollamawebui/ollama-webui](url)

Thx,
Marcel

**Comment by justinh-rahb** [comment]
I am unsure who uploaded that but it was not by this project or its maintainers.

**Reply by marcel293** [reply]
Thx. Is it planed or possible to get the container over this repository?

**Comment by KusAdama** [comment]
There is docker compose file [in quick start](https://docs.openwebui.com/getting-started/quick-start#using-slim-images).

So on Synology you can create it with the Container manager. Just create folder and add it as path in the project and choose to create .yml file.

Past in the slim version (because Synology does not have HW capabilities to handle models anyway)

```
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main-slim
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
volumes:
  open-webui:
```

Just the update need to be done within the ssh (ssh into project folder > down, pull and up -d for the docker compose and should be good. Or script it.
