### DISCUSSION TITLE
BUG No completion from Ollama-served model proxied behind LiteLLM

### DISCUSSION THREAD

**Discussion by corticalstack** [open-webui/open-webui#1832] [General]
# Bug Report

## Description
Configured a proxied LiteLLM model in open-webui. Cannot get response completion from the model, UI visualisation just shows a blining awaiting response.

Note I do get compeltion from said model exposed via LiteLLM when inferring LiteLLM directly, with the example curl below:

```
curl --location 'http://192.168.1.12:4000/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-1234' \
--data ' {
      "model": "ollama/llama3",
      "messages": [
        {
          "role": "user",
          "content": "What is entropy theory"
        }
      ],
    }
'
```

When configuring the ollama/llama3 model in open-webui LiteLLM settings, I have tried both `http://192.168.1.12:4000` and `http://192.168.1.12:4000/chat/completions` as api base urls.

Also note I do get completioned from other LLM endpoints proxied behind LiteLLM sich as OpenAI GPT-3.5-Turbo and Groq Llama3-70B.

Thanks for any help.

## Environment

- **Open WebUI Version:** [e.g., 0.1.121]
- **Ollama 0.1.32
- **LiteLLM 1.35.29 OAS 3.1
- **Ubuntu 22.04.3 LTS

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

**Comment by justinh-rahb** [comment]
Base URLs should be that of your Ollama server, not the LiteLLM proxy:

<img width="688" alt="Screenshot 2024-04-28 at 12 40 18 PM" src="https://github.com/open-webui/open-webui/assets/52832301/393b38f9-d11d-490e-a68e-996e4ef51339">

**Comment by corticalstack** [comment]
That's defeating my objective, which is to have EVERY LLM made available for seelction behind a proxy, for purposes of load balancing, capturing token consumption etc.

If I wanted open-webui to have direct access to ollama runner, I'd just configure the OLLAMA_BASE_URL.

**Comment by cheahjs** [comment]
If you're adding it as a model under LiteLLM, then you've misconfigured things. As described, you've configured Open WebUI's LiteLLM instance to talk to your external LiteLLM instance using the Ollama API (the `ollama/` provider prefix in your model name), which fails since LiteLLM doesn't expose an Ollama compatible endpoint. It just so happens to work with OpenAI and Groq because they are OpenAI-compatible endpoints.

![image](https://github.com/open-webui/open-webui/assets/818368/bcae1b0d-86f6-4559-97fc-7608008c8e82)

You will want to configure your external LiteLLM proxy as an OpenAI compatible endpoint, not a LiteLLM model inside of Open WebUI.

![image](https://github.com/open-webui/open-webui/assets/818368/66ae8c26-1cfb-42bf-8b55-cfd928dd19ab)

If you _really_ need the model level granularity, then use `openai/<external_litellm_model_name>` as the Open WebUI LiteLLM model name.

**Comment by corticalstack** [comment]
@cheahjs thanks for that, have been trying your suggestions. I think the right side of yiour sketches would need a fix - prefixing the llama3 model with openai/ in LiteLLM so that LiteLLM exposes as an openAI compatible endpoint, no?

Also, I dont quite understand the second diagram with the arrow labelled OpenAI going direct from open-webui to external LiteLLM. I guess you mean update the open-webui OpenAI api endpoint url to be that of my external LiteLLM server? SO How could I then configure Llama3, if not in the settings>models>LiteLLM config? It would be an endpoint including model name? That doesn't look to work either, as open-webui is adding routes to the url that don't mate the routes exposed by external LiteLLM.  Thanks for any additional help/suggestions, much aprpeciated.

**Comment by justinh-rahb** [comment]
I think there's still misunderstanding in the purpose/use of LiteLLM, both the one that's built into our project and running one externally. Our UI can create a config.yaml file for our internal instance of LiteLLM, that file _could_ potentially be mounted by an external instance too, but we have no way to make an external instance restart to reload that config when it is changed.

Effectively your choices are:
1. Use ours and configure it from the UI. The models here should be connecting to backend APIs directly, not to another LiteLLM instance.
2. Use external and configure it yourself, add it to WebUI as an "OpenAI" connection (Base URL `http://litellm:4000/v1`)

**Comment by corticalstack** [comment]
@justinh-rahb appreciate additional feedback. Just to clarify my perspective. My preference is to have seperation of concerns between components. I do not want a webUI for chat managing an endpoint proxy server. I will have other consumers of LLM endpoints besides chat UIs. Hence focus on external LiteLLM. The same approach would be taken by large enterprise. I'm OK restarting an external endpoint proxy when config changes.

**Comment by corticalstack** [comment]
Incidentally, configuring my external LiteLLM proxy as an OpenAI connection worked in making available the LiteLLM config.yaml models configured as openai format models.

Indeed would agree there was misunderstanding on my part getting external LiteLLM, open-webui, and ollama to sing together nicely. Perhaps some end-to-end docs with notes, example config, and the viz @cheahjs shared would help. I appreciate the help of you both @justinh-rahb @cheahjs , however hope my principle of seperation was understood. Thanks again!

For any others with similar issues, the following works in chatting with a self-hostes, Ollama served Llama3 proxied by external LiteLLM.

**Open-webui** updated in settings>connections>OpenAI API to point to external LiteLLM, e.g.: `http://<External LiteLLM:4000/v1`, and LiteLLM master key as api key

Example model config for Llama-3 being served by Ollama
```
- model_name: openai/llama3
    litellm_params:
        model: ollama/llama3
        api_base: http://<Ollama server>:11434
        api_key: "empty"
        rpm: 1440
    model_info:
      version: latest
```

**Comment by patrickwasp** [comment]
I stumbled across this same issue. 

to give a better idea of the system I'm trying to build here is my docker-compose.yaml file and my litellm_config.yaml file

```yaml
services:

  ollama:
    image: ollama/ollama:0.1.32
    tty: true
    restart: unless-stopped
    ports:
      - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
      - ./config/ollama/modelfiles:/modelfiles
    environment:
      - ENV_VARIABLE=value
      - OLLAMA_DEBUG=true
      - LLAMA_TRACE=1
      - GGML_DEBUG=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  litellm:
    image: ghcr.io/berriai/litellm:main-v1.35.31
    restart: unless-stopped
    environment:
      - LITELLM_LOG=DEBUG
    ports:
      - 4000:4000
    volumes:
      - ./config/litellm/litellm_config.yaml:/app/config.yaml
    command: --config /app/config.yaml

  open-webui-litellm:
    image: ghcr.io/open-webui/open-webui:0.1.122
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./data/open-webui/litellm:/app/backend/data
      - ./config/litellm/webui/config.yaml:/app/backend/data/litellm/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

```yaml
model_list:
  - model_name: ollama/mistral:v0.2
    litellm_params:
      model: ollama/mistral:v0.2
      api_base: http://ollama:11434
```

then in open-webui-litellm I had to modify the connection setting for the OpenAI API url and key. After that webui automatically found the models being proxied by litellm and I could talk to them.

![Screenshot from 2024-04-29 21-31-10](https://github.com/open-webui/open-webui/assets/70671760/98e408a4-548a-4987-b285-8ea022a7bfcf)
