### DISCUSSION TITLE
Open AI API settings lost after restart of docker container

### DISCUSSION THREAD

**Discussion by Joakim-T** [open-webui/open-webui#1896] [General]
# Bug Report

## Description
When restarting the Open WebUI docker container API key settings are lost

**Bug Summary:**
When restarting the Open WebUI docker container API key settings are lost

**Steps to Reproduce:**
Enter a API key, save and restart Docker

**Expected Behavior:**
API key persists after restart

**Actual Behavior:**
API key is lost after restart

## Environment

- **Open WebUI Version:** 0.1.1222

- **Operating System:** Docker running in Portainer

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [X] I have included the Docker container logs.

## Logs and Screenshots

**Docker Container Logs:**
[owebui.log](https://github.com/open-webui/open-webui/files/15176668/owebui.log)

**Screenshots (if applicable):**
Before restart
![pre](https://github.com/open-webui/open-webui/assets/9702419/892cd150-da4a-4add-a801-e32394de9415)

After restart
![Screenshot 2024-05-01 133816](https://github.com/open-webui/open-webui/assets/9702419/cd1fb9cc-1bc3-40b3-b683-88378ac993c8)

## Installation Method

Docker

**Comment by Yanyutin753** [comment]
###  follow the documentation to add environment variables
![image](https://github.com/open-webui/open-webui/assets/132346501/cfbc371a-f7bf-45da-bd1d-42a03305d6a7)

**Comment by vialcollet** [comment]
Hi all
When using the variables like in the doc, models from open ai or groq are not pulled.
I am using the latest docker image available for a cloud deployment. I don't use Ollama on this instance.
Here is my setup:
```yaml
version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    networks:
      - webproxy
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
  
networks:
  webproxy:
    name: webproxy
    external: true
```

```env
ENV=prod
OPENAI_API_BASE_URLS="https://api.openai.com/v1;https://api.groq.com/openai/v1"
OPENAI_API_KEYS="key1;key2"
```
![image](https://github.com/open-webui/open-webui/assets/4971086/367133fe-919b-403c-9784-6bb7e7201647)

**Comment by vialcollet** [comment]
Ouch.. my bad I just realized I had by mistake deleted the environment key... :))

So  it's owrking obviously very well like so:

```yaml
version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    networks:
      - webproxy
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    environment:
      - 'OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}'
      - 'OPENAI_API_KEYS=${OPENAI_API_KEYS}'
      - 'OLLAMA_BASE_URL=${OLLAMA_BASE_URL}'
      - 'ENV=${ENV}'

volumes:
  open-webui: {}
  
networks:
  webproxy:
    name: webproxy
    external: true
```
