### DISCUSSION TITLE
Help: Using an API Gateway endpoint to access a model in OpenWebUI

### DISCUSSION THREAD

**Discussion by josemartin357** [open-webui/open-webui#1949] [General]
Hello, am new to OpenWebUI.
I am using an API Gateway (Kong) that has a proxy so in it, i set-up my Azure OpenAI resource URI, api key, model, etc. As a result, I have an endpoint.
Is it possible to use that endpoint as a model option in OpenWebUI? That way i dont have to insert again the Azure OpenAI resource URI and API key; just the API gateway endpoint.
Any help is appreciated; i love the product :)

**Comment by arsaboo** [comment]
yes, if it is an openAI-compatible endpoint, you can add it to your environment:

```yaml
    environment:
      OPENAI_API_BASE_URLS: "https://openrouter.ai/api/v1"
      OPENAI_API_KEYS: "KEY"
```
