### DISCUSSION TITLE
Is Open WebUI HTTPS Capable?

### DISCUSSION THREAD

**Discussion by yuchenxie4645** [open-webui/open-webui#2127] [General]
Is Open WebUI HTTPS Capable? If not, how do I make it HTTPS capable, if yes, how do I make it HTTPS capable?
I have my own personal domain already attached to Open WebUI but it shows as unsecure, I wanted to know, how do I make it HTTPS. 
If this helps, I am using cloudflare for SSL certificate.

**Comment by james-westbrook** [comment]
Open WebUI itself doesn't implement SSL, most people have used another service (Nginx, Apache, AWS ALB, etc.) in front of Open WebUI to implement SSL. The maintainers have said in Discord many times that SSL and load balancing are too opinionated for them to want to implement it in Open WebUI.

**Reply by yuchenxie4645** [reply]
Can you elaborate on “most people have used another service”. My understanding is that the “another service” will forward it to Open WebUI. If my understanding is correct, is there anyway I can do that?

**Reply by skrenes** [reply]
Check out https://github.com/nginx-proxy/nginx-proxy

**Comment by tedraymond** [comment]
Yes it does,

I've used uvicorn in previous tools, noticed WebUI does as well.

In Start.sh 

In the last line where there is uvicorn app --host -- port .... '*'

Just add the uvicorn options 

--ssl-certfile="/path/to/file.pem" --ssl-keyfile="/path/to/file.key"

Did so today to replace my older gradio app and worked like a charm.

**Reply by avimar** [reply]
I'm running the docker command `docker run -d -p 3000:8080 -v open-webui:/app/backend/data  --name open-webui --restart always  ghcr.io/open-webui/open-webui:main` 
How do I edit that `start.sh` file?

**Reply by frankkubler** [reply]
i'm using docker compose to build open-webui. I predited the start.sh  with uvicorn parameters and then in docker-compose.yaml I link the modified files and my certbot files to the docker : 
 open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-latest}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - /etc/letsencrypt/:/app/certs
      - ./modified_start.sh:/app/backend/start.sh 
  
Hope this helps

**Reply by beckerben** [reply]
After i added the --ssl-certificate and --ssl-keyfile, this does add SSL support, but now my container shows unhealthy with error: jq: error (at <stdin>:0): break

Everything seems to work other than the unhealthy status shown in portainer. Odd.

**Reply by frankkubler** [reply]
@beckerben you are right, i got the same thing. Everything works with a unhealthy status of my docker. I will made investigation and back here if a found something.

**Reply by beckerben** [reply]
@kubikub it is the Dockerfile HEALTHCHECK it is looking at http not https

**Reply by thomvaill** [reply]
You can also use the `UVICORN_SSL_CERTFILE` and `UVICORN_SSL_KEYFILE` instead of the script arguments so you don't have to patch start.sh at all ;)

**Reply by frankkubler** [reply]
@thomvaill how can I do that ? i'm using a docker-compose.yml file. I tried to put UVICORN_SSL_CERTFILE and UVICORN_SSL_KEYFILE with environement var but it didn't work. Many thanks for your reply

**Reply by ara-arowana** [reply]
@kubikub @thomvaill could you make this work? I feel like I'm pretty close, but when setting these vars OpenWebUI responds with 500 for any request. I checked that key and cert file are readable from inside the container, what else could be the problem?

**Comment by UberMetroid** [comment]
I use a cloudflare tunnel for https.

**Reply by Koesn** [reply]
I have an issue with tunneling where streaming seems stuttering, like 2-3 chunk per second, not fluid all chunk shown. Already try through Tailscale also, but it's smoothly streaming. Do you experience this with cloudflare? How to fix this? Thanks.

**Reply by justinh-rahb** [reply]
Try disabling chunked encoding:

<img width="1018" alt="Screenshot 2024-07-15 at 7 44 42 PM" src="https://github.com/user-attachments/assets/bebf66d3-6fcf-4e08-bf7c-6f92c9dce7d6">

**Reply by Koesn** [reply]
Thank's but still no luck. It seems the tunnel send about 5-6 words. Can we make "Fluidly stream large external response chunks" works smoother between accepted chunk? Or are there any chunk size settings, maybe be the tunnel send a larger chunk. I have no idea..

**Reply by dausruddin** [reply]
@Koesn have you found a fix?

**Comment by KelvinCampelo** [comment]
Install Nginx: sudo apt install nginx

Create Nginx server block: /etc/nginx/sites-available/openwebui

```
server {
    listen 80;
    server_name YOURDOMAIN.com;

    location / {
        proxy_pass http://127.0.0.1:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Enable server block: sudo ln -s /etc/nginx/sites-available/openwebui /etc/nginx/sites-enabled/

Test and restart Nginx: sudo nginx -t and sudo systemctl restart nginx

Install Certbot: sudo apt install certbot python3-certbot-nginx

Obtain SSL certificate: sudo certbot --nginx -d YOURDOMAIN.com

Verify SSL: Visit https:// YOURDOMAIN. com

Test renewal: sudo certbot renew --dry-run

**Reply by yuchenxie4645** [reply]
I really appreciate your help, however, I got it fix using my own way. I bought a domain off of namecheap and transferred it to CloudFlare which provided me a "flexible"  SSL certificate which encrypts the client end not the server end. Again, I really appreciate your help :D

**Reply by hasron** [reply]
Thank You! 
please check the port: 
`proxy_pass http://127.0.0.1:8080;`

**Comment by frankkubler** [comment]
I followed @KelvinCampelo steps but could not connect https openwebui server. I got  ERR_SSL_PROTOCOL_ERROR.
My Nginx server block: /etc/nginx/sites-available/openwebui : 
```
                                                          
server {
    listen 80;
    server_name mydomain.duckdns.org;
    return 301 https://$host:10443$request_uri;
}

server {

    listen 10443 ssl; # managed by Certbot
    server_name mydomain.duckdns.org;
    ssl_certificate /etc/letsencrypt/live/mydomain.duckdns.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.duckdns.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
```
Did I something wrong ?

**Reply by thiswillbeyourgithub** [reply]
Same error with either nginx or caddy

**Comment by reiebrole30** [comment]
I am using a cloudflare domain ,

my setups are all via docker
cloudflared
ollama
open-webui


heck, even the login is via cloudflare authentication

```
---
version: "3.8"
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: /ollama
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
     environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
      - ENABLE_MODEL_FILTER=True
      - DEFAULT_MODELS=gpt-3.5-turbo
      - MODEL_FILTER_LIST:gpt-3.5-turbo;gemma:2b;gpt-4-turbo-preview;Code
        llama;Mistral 7B;MythoMax
      - WEBUI_NAME=Rei Home Server
      - OPENAI_API_KEYS=xxxxxxxxxxxx
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Cf-Access-Authenticated-User-Email
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN=xxxxxxxxxxxxxxx
    command: tunnel run
    restart: unless-stopped
volumes:
  ollama: {}
  open-webui: {}



```
