### DISCUSSION TITLE
Embeddings model for Azure Open AI via LiteLLM

### DISCUSSION THREAD

**Discussion by mphacker** [open-webui/open-webui#2288] [General]
**Is your feature request related to a problem? Please describe.**
I am using Open WebUI with Azure OpenAI through the LiteLLM integration. I would like to do RAG using an embedding model hosted in Azure.

**Describe the solution you'd like**
Ability to choose a model defined in LiteLLM for embeddings

**Describe alternatives you've considered**
I have tried looking at options to use the build in LiteLLM to get embeddings to work, but no luck so far.

**Additional context**
n/a

**Comment by forcewake** [comment]
Hey @mphacker,
If you still interested I've found the right way to do it:

Your litellm config should looks like:
```yaml
model_list:
  - model_name: xxx-gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: https://xxx.openai.azure.com
      api_version: "2023-03-15-preview"
      api_key: ""
  - model_name: text-embedding-3-large
    litellm_params: 
      model: azure/text-embedding-3-large
      api_key: ""
      api_base: https://xxx.openai.azure.com
```

And you config in open-webui, should be similar to:
![image](https://github.com/user-attachments/assets/abd02c35-1a55-4267-a76c-c0278b17cd7c)
