### DISCUSSION TITLE
Not properly using WEBUI_URL for logout URL

### DISCUSSION THREAD

**Discussion by skrenes** [open-webui/open-webui#2567] [General]
# Bug Report

## Description

**Bug Summary:**
The logout URL is not using `WEBUI_URL`. 

**Steps to Reproduce:**
Set the environment variable `WEBUI_URL=https://example.com`. Sign into Open-WebUI and then sign out.

**Expected Behavior:**
The URL after logging out should be `WEBUI_URL`/auth (e.g. example.com/auth).

**Actual Behavior:**
The URL after logging out is `WEBUI_URL`:{reverse-proxy-port}/auth/ (e.g. https://example.com:2828/auth/).

## Environment

- **Open WebUI Version:** v0.1.125
- **Ollama (if applicable):** N/A

- **Operating System:** Debian GNU/Linux 12 (bookworm) / Docker version 26.1.3, build b72abbb
- **Browser (if applicable):** Chromium v125.0.6422.60 and Safari v17.5

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs. **N/A**
- [x] I have included the Docker container logs. **N/A**

## Installation Method

```yaml
services:
  open-webui:
    container_name: open-webui
    hostname: open-webui
    image: ghcr.io/open-webui/open-webui
    restart: on-failure
    volumes:
      - /apps/Open-WebUI/data:/app/backend/data
    environment:
      - TZ=America/Edmonton
      - ENABLE_IMAGE_GENERATION=True
      - ENABLE_LITELLM=False
      - IMAGE_GENERATION_ENGINE=openai
      - OPENAI_API_KEY=my_key
      - WEBUI_SECRET_KEY=my_secret
      - WEBUI_URL=https://example.com
    networks:
      - reverse_proxy
```

## Additional Information

I have an nginx-proxy that routes https://example.com to Open WebUI. It's a slightly customized version of [nginx-proxy](https://github.com/nginx-proxy/nginx-proxy). It works by having my router forward `WAN_IP`:`443` to `SERVER_IP`:`reverse_proxy_port` (which is `2828`), which is Nginx that forwards to `http://open-webui:8080`.

I have dozens of containers that have no problem with this, so it's interesting that Open WebUI has figured out the `reverse_proxy_port` of 2828, unless that's just coincidence. In any case, it should respect `WEBUI_URL` verbatim (including port, which is implied as 443 since the protocol is https) when it's defined.
