### DISCUSSION TITLE
ImportError: libctranslate2-81fc0d88.so.4.2.1: cannot enable executable stack as shared object requires: Permission denied

### DISCUSSION THREAD

**Discussion by Majroch** [open-webui/open-webui#2917] [General]
# Bug Report

## Description

**Bug Summary:**
Cannot run docker image `ghcr.io/open-webui/open-webui` as suggested in README and documentation.

**Steps to Reproduce:**
Run example command from README or documentation page (I tried only the `ollama` tag to run using this method):

```bash
docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama
```

Optionally, run container using docker compose configuration file:

```yaml
---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      OLLAMA_BASE_URL: 'http://ollama:1143'
      WEBUI_SECRET_KEY: ~
    depends_on:
      - ollama
    networks:
      - default
      - proxy # One of external networks, for nginx proxy
      - homarr # one of external networks, for Homarr dashboard
    volumes:
      - '/home/USERNAME/ollama/backend:/app/backend/data'

  ollama:
    image: ollama/ollama:latest
    volumes:
      - '/home/USERNAME/ollama/data:/root/.ollama'
    tty: true
    restart: unless-stopped
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu,video]

networks:
  proxy:
    external: true
  homarr:
    external: true
```

**Expected Behavior:**
App launching properly, without any errors.

**Actual Behavior:**
Cannot run application in docker container, because of error message:

```
ImportError: libctranslate2-81fc0d88.so.4.2.1: cannot enable executable stack as shared object requires: Permission denied
```

## Environment

- **Open WebUI Version:** main, ollama tags in image (specific version unknown)
- **Ollama (if applicable):** latest tag in image (specific version unknown)

- **Operating System:** OpenSUSE Tumbleweed MicroOS 20240531 with Docker and nvidia drivers installed (configured with docker setup properly)
- **Browser (if applicable):** Firefox 126.0.1 (64-bit) installed through flatpak

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
No logs from console, not required.

**Docker Container Logs:**

Logs from my container with open-webui:

[_ollama-open-webui-1_logs.txt](https://github.com/user-attachments/files/15741184/_ollama-open-webui-1_logs.txt)

Those logs can be incomplete, because of container was running for long time when i was searching for what happened and how to potentially fix it.

**Screenshots (if applicable):**
No screenshots required.

## Installation Method

I have prepared Docker and docker compose on my server, with NVIDIA drivers and nvidia-container-toolkit installed and working with other containers properly.

To configure my docker instance, i use Portainer webapp.

## Additional Information

This containers were configured on my servers docker instance, rather on my desktop. Firefox is installed on desktop, but docker with nvidia, etc. is on my server. I also have Jellyfin, stable diffusion, and bunch of other stuff running on it, and all of them seems fine, without any problems.

Additionally, i run watchtower, to handle my update process of all containers, but this seems unrelated.

And, last time I tried installing open-webui on my server, i had weird error, that digest was incorrect, and just abandoned the idea of installing it on it. But today i tried again, but this error happened.

About this problem, I've search for it on Google and other issues here, but no luck with anything on first sight.
