### DISCUSSION TITLE
socket.io , return 400

### DISCUSSION THREAD

**Discussion by leobenkel** [open-webui/open-webui#2918] [General]
# Bug Report

## Description

**Bug Summary:**

I am getting a bunch of 
```
"GET /ws/socket.io/?eio=4&transport=polling&t=o_pp-gu HTTP/1.1" 400
```

in the log, any reason ? 

**Steps to Reproduce:**

i'm not sure, just start it ? 

**Expected Behavior:**

not a lot of 400 in the log :) 

**Actual Behavior:**

I am getting a bunch of 
```
"GET /ws/socket.io/?eio=4&transport=polling&t=o_pp-gu HTTP/1.1" 400
```

## Environment

- **Open WebUI Version:** latest
- **Ollama (if applicable):** latest

- **Operating System:** ubuntu

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.

## Installation Method

docker

**Comment by granludo** [comment]
Same thing happening on a mac launching on docker.
I get a lot of
```
open-webui  | INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
open-webui  | Invalid transport (further occurrences of this error will be logged with level INFO)
open-webui  | ERROR [engineio.server] Invalid transport (further occurrences of this error will be logged with level INFO)
open-webui  | INFO:     192.168.65.1:43249 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PGOn0JR HTTP/1.1" 400 Bad Request
open-webui  | INFO:     192.168.65.1:43249 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PGOn0pa HTTP/1.1" 400 Bad Request
open-webui  | INFO:     192.168.65.1:43255 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PGOn2Hh HTTP/1.1" 400 Bad Request
open-webui  | INFO:     192.168.65.1:43270 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PGOn3lv HTTP/1.1" 400 Bad Request

```

My docker compose:

```
services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
      CORS_ALLOWED_ORIGINS: "*"
      TRANSPORT: "websocket"  # Enforce WebSocket transport
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
```
Then the behavior of open-webui is not normal
