### DISCUSSION TITLE
Searxng URL How to obtain

### DISCUSSION THREAD

**Discussion by windkwbs** [open-webui/open-webui#3003] [General]
Searxng URL How to obtain?

**Comment by JuanjoJG-WATA** [comment]
here you have a full tutorial: [Step by step installation](https://docs.searxng.org/admin/installation-searxng.html)

**Comment by thfrei** [comment]
So I found this link quite useful: https://docs.openwebui.com/tutorial/web_search

My search URL for open-webui is then: `http://searxng:8080/search?q=<query>`

In order for this to work, you need to update the settings.yml to allow for json output.

When you use docker compose, you cann add one more service searxng:

What is important though, is that you enable the json format for searxng responses. On the docker volume edit the settings.yml:
The `settings.yml` is maybe around here: `/var/lib/docker/volumes/ollama_searxng/_data` (depending how your volume is named)

```yaml
# ~lines 60
  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - json   # <--- json

server:
  # Is overwritten by ${SEARXNG_PORT} and ${SEARXNG_BIND_ADDRESS}
  port: 8888
  bind_address: "127.0.0.1"
  # public URL of the instance, to ensure correct inbound links. Is overwritten
  # by ${SEARXNG_URL}.
```

My search URL for open-webui is then: `http://searxng:8080/search?q=<query>`

Reference, complete docker compose / stack (portainer)

```yaml
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:0.1.43
    ports:
      - '11434:11434'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - web

  open-webui:
    image: ghcr.io/open-webui/open-webui:git-06976c4
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
      - 'WEBUI_SECRET_KEY=[secret]'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.[myurl].com`)"
      - "traefik.http.routers.chat.entrypoints=web" # changed (add ,websecure later)
    restart: unless-stopped


  searxng:
    image: searxng/searxng:2024.6.7-f5eb56b63
    ports:
      - '11435:8080'
    networks:
      - web
    volumes:
      - searxng:/etc/searxng
    environment:
      - 'INSTANCE_NAME=searxng-in'
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
  searxng: {}
  
networks:
  web:
    external: true
```
