### DISCUSSION TITLE
Pipelines Not Detected

### DISCUSSION THREAD

**Discussion by windkwbs** [open-webui/open-webui#3206] [General]
1

**Comment by justinh-rahb** [comment]
1. Go to **Admin Settings > Connections > OpenAI**
2. Add the API URL `http://host.docker.internal:9099` and the API key `0p3n-w3bu!`

Your pipelines should now be active.

**Comment by laurentiu-miu** [comment]
With the configuration (API URL and API KEY) for docker. 
open-webui server > Verify connection: _Server connection verified_
pipelines server > {"status":true}
I still get in Admin Panel/Settings/Pipelines: Manage Pipelines - **Pipelines Not Detected**. 
Images: 
open-webui sha256:f53d1dbd8d9bd6a5297ba5efc63618df7 (latest main 11 Jul) - before upgrade was ok
pipelines sha256:f14c09b9edaa6781088ee6d2617565f72

By deleting the volumes in Docker and reinstalling everything from scratch, it works.

**Comment by xjaroo** [comment]
with the docker container, then use container name 

Navigate to the Settings > Connections > OpenAI API section in Open WebUI.
Set the API URL to http://**pipelines**:9099 and the API key to 0p3n-w3bu!. Your pipelines should now be active.

**Reply by cangowang** [reply]
anyone can help this? my enviroment as below : 
![image](https://github.com/user-attachments/assets/f8a4a249-c5b6-447f-a515-48405e02d790)
but, when i config OpenAI API to http://open-webui:9099 with API key : 0p3n-w3bu!
I still get the error   Pipelines Not Detected.

the docker container name is the name of open-webui, correct?

**Comment by hugalafutro** [comment]
can you explain this better? with non standard ports? 
where's the 9099 coming from? 
by `host.docker.internal` do you mean `172.17.0.1`, hostname of the docker host, service name, container name or ... what?

sorry if it's obvious to native english speaking tech guru of which I ain't either :D
thank you!

**Comment by Lue-C** [comment]
I get the same error message "Pipelines not detected". I tried the latest image as well as that of version 0.5.20, but neither of them worked. I also tried deleting the volume and copying the URL "http://pipelines:9099" and the key "0p3n-w3bu!" but this also did not help.

**Reply by hugalafutro** [reply]
I do not understand why its not included in the image, perhaps they split it at some point, I am hundred percent sure I never used any pipelines container before migrating and pipe functions worked but I had the old open-webui install since forever so maybe the pipelines were there from before.

I made a custom pipelines app on Truenas and it works now, so I guess you have to run another container https://github.com/open-webui/pipelines

**Reply by vsilent** [reply]
because it's a separate server, that's why, separate container.

**Reply by vsilent** [reply]
@Lue-C  Looks like pipeline server is not started. Check it from the the command line docker compose logs pipelines
1. Check the docker-compose.yml file is valid
2. docker compose down (for container re-creation)
3. docker compose up -d

**Reply by hugalafutro** [reply]
> because it's a separate server, that's why, separate container.

Yes I get that now, but what I mean is:

At a certain faraway point in the past I started using open-webui via the `docker-compose.yml` that was available on the page at the time. I have never installed any other container nor have I heard the word pipelines in relation with the open-webui app until this discussion. I have been using that initial install of open-webui with function that provides access to anthropic api models for months, only ever running `docker compose up -d`.

Then "recently" (for me, I don't use the app everyday) the anthropic api function stopped working with some esoteric (for me in the context at the time) pipelines error and my googling led me to discovering of the pipelines container and this discussion. 

So logically, the functionality must have been at some point split from the main container. I'm not blaming anybody nor am I trying to be confrontational, I just find it weird that this is the 2nd thread about the "issue" where everyone just keeps telling me how is it another container and what not (and yes, I get that now), but **noone acknowledges it must not have been the case in the past**. For me there never was another container until now. I reiterate: I never heard the word pipelines in conjunction with open-webui, nor the login information of `http://pipelines:9099/` and `0p3n-w3bu!` was ever mentioned anywhere at the time when I installed it.

edit:
for reference I dug out the `docker-compose.yml` from ~half a year old backup, this is what I was running with and nothing else and the function that now needs extra pipelines container worked without it which to me implies the pipelines functionality at the time was part of the main container.
```
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    container_name: open-webui
    volumes:
      - ./data:/app/backend/data
    environment:
      - OPENAI_API_KEY=${OAIAPI}
      - AUTOMATIC1111_BASE_URL=${A1111URL}
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_MODEL=perfectdeliberate_v5
      - IMAGE_SIZE=512x512
    ports:
      - 3333:8080
networks: {}
```

**Comment by vsilent** [comment]
Make sure you have set 

`container_name: pipelines `

Here is a working example 
```
volumes:
  openwebui:
  pipelines:

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
#    env_file: .env
#    ports:
#      - "3001:8080"
    volumes:
      - openwebui:/app/backend/data
    networks:
      - default_network

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - pipelines:/app/pipelines
    restart: always
    environment:
      - PIPELINES_API_KEY=0p3n-w3bu!
    networks:
      - default_network

networks:
    default_network:
        external: true
```
