### DISCUSSION TITLE
Support deployment behind a reverse proxy with HTTPS protocol enabled

### DISCUSSION THREAD

**Discussion by yusiwen** [open-webui/open-webui#3727] [General]
In `backend/start.sh`:

https://github.com/open-webui/open-webui/blob/824966ad4a6b238731076021b8ad4c1e3cbe8f3f/backend/start.sh#L58

The startup argument of uvicorn should contain `--proxy-headers` to support the X-Forwarded-Proto header. It's crucial when Open-WebUI is deployed behind a reverse proxy and HTTPS is enabled.

For example, when using OIDC, the `redirect_uri` generated in the authorization request will be `http://<open-webui>/...`, which is wrong without `--proxy-headers` enabled.

**Comment by YetheSamartaka** [comment]
I experience the same issue where due to this, OIDC is generating http requests instead of https ones.

**Reply by flexchar** [reply]
Have you gotten a fix?

**Reply by YetheSamartaka** [reply]
Unfortunately not yet. I've tried adding --proxy-headers and rebuilding the docker image but it did not have desired effect and I'm still getting HTTP links.

**Comment by flexchar** [comment]
I'm attempting to deploy behind Cloudflare proxy, which means it's served on HTTP but proxied with TLS on HTTPS. Cannot use authentication due the same issue.

**Reply by yusiwen** [reply]
I've create my own `start.sh`, the only chanage is the last line:

```bash
WEBUI_SECRET_KEY="$WEBUI_SECRET_KEY" exec uvicorn main:app --host "$HOST" --port "$PORT" --proxy-headers --forwarded-allow-ips '*'
```

I mount it to the container using  `-v ./start.sh:/app/backend/start.sh`, and it's done. The redirect_uri value in the OIDC authorization request to my Authelia is correct

**Reply by YetheSamartaka** [reply]
Hi. I tried doing exactly the same thing but I'm still experiencing issues. Could that be the setting of my reverse proxy? Would you share essential parts of yours, please?

**Reply by yusiwen** [reply]
My docker compose file for open-webui:

```yaml
---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: if_not_present
    volumes:
      - ./.ollama/open-webui:/app/backend/data
      - ./start.sh:/app/backend/start.sh
    ports:
      - 3060:8080
    environment:
      - WEBUI_URL=https://${CHAT_DOMAIN}
      - OLLAMA_BASE_URL=${OLLAMA_SERVER:-http://192.168.2.45:11434}
      - OPENAI_API_BASE_URLS=https://api.openai.com/v1
      - OPENAI_API_KEYS=${OPENAI_ACCESS_KEY}
      - OAUTH_CLIENT_ID=open_webui
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OPENID_PROVIDER_URL=https://${AUTHELIA_DOMAIN}/.well-known/openid-configuration
      - OAUTH_PROVIDER_NAME=Authelia
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_ENGINE=openai
      - IMAGE_SIZE=1024x1024
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    networks:
      - ollama

networks:
  ollama:
```

The server part of my nginx configuration for open-webui:

```nginx
....
server {
.....
 location / {
    proxy_read_timeout 900;
    proxy_pass_header Server;
    proxy_cookie_path ~*^/.* /;

    proxy_pass http://localhost:3060;

    proxy_request_buffering off;
    proxy_http_version 1.1;

    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
...
}
```

Maybe `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` will do the trick
