### DISCUSSION TITLE
[BUG] Backend Required, unsupported method (frontend only)

### DISCUSSION THREAD

**Discussion by DuckY-Y** [open-webui/open-webui#3884] [General]
## Context
So I've been trying to setup open-webui behind a reverse proxy, in this case Traefik.
![Screenshot 2024-07-12 150000](https://github.com/user-attachments/assets/a86d9301-f1de-4af4-9830-24da453fe09e)
As you can see from the screenshot, this is the page I'm greeted with when accessing webui.
I simply don't understand as to why I'm getting this error when I point Traefik at the internal 8080 port of open-webui?
If I were to uncomment the ports part and visit the site with ip and port specified (e.g. chat.bss:8081), then it works perfectly fine

## docker-compose.yaml
```
  chat-webui:
    build:
      context: ../apps/chat_open-webui/.
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    container_name: chat-webui
    # ports:
    #   - "8081:8080"
    volumes:
      - chat-webui:/app/backend/data
    restart: unless-stopped
    depends_on:
      - traefik
    networks:
      - ai-network
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-webui.entrypoints=web"
      - "traefik.http.routers.chat-webui.rule=Host(`chat.bss`)"
      - "traefik.http.services.chat-webui.loadbalancer.server.port=8080"
```
## Environment

- **Open WebUI Version:** [[eff736a](https://github.com/open-webui/open-webui/commit/eff736acd2e0bbbdd0eeca4cc209b216a1f23b6a)]
- **Operating System:** [Ubuntu 22.04]

## Logs
![image](https://github.com/user-attachments/assets/1073db61-6f5a-46a8-999d-6527f64b51b0)
No errors reported in logs

**Comment by DuckY-Y** [comment]
I simply don't understand why a reverse proxy pointing at the internal port 8080 in the docker network would have this issue as effect.
Does nginx also produce this issue or is it limited to Traefik?

**Comment by Snuupy** [comment]
running into the same issue with nginx on iceraven (but not chrome/kiwi on mobile), I can't figure out why

**Reply by Snuupy** [reply]
needed to clear cache in browser, fixed

**Reply by ofekdavid** [reply]
King!

**Reply by Aeidle** [reply]
Legend

**Reply by tronford** [reply]
LEGEND

**Reply by dogunbound** [reply]
^^^^ Had this happen to me (2026). Clearing cache fixed it. Although this should never be an issue after updating.

**Comment by Pietro395** [comment]
I am trying to serve Open WebUI via nginx as a reverse proxy.

But I always get this error


My docker compose:
```
services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=https://redacted
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
```

My nginx configuration file:
```
    server_name ollama.redacted.in;
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_buffering off;
        proxy_set_header Origin '';
        proxy_set_header Referer '';
    }
    location /api {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Origin '';
        proxy_set_header Referer '';
        proxy_pass http://localhost:11434/api;
    }
    location /api/v1 {
        proxy_pass http://localhost:11434/api/v1;
    }
```
