### DISCUSSION TITLE
How to Register Bedrock LLM in Version 0.3.8

### DISCUSSION THREAD

**Discussion by Taehui** [open-webui/open-webui#3901] [Q&A]
I have set it up as shown below 'config.yaml', but the Bedrock model is not visible in the web application. The current version of open-webui is 0.3.8.

```
model_list:
  - model_name: bedrock-claude-3-5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: us-east-1

litellm_settings:
  drop_params: True
```
