### DISCUSSION TITLE
mem0 compatabile with openwebui and ollama?

### DISCUSSION THREAD

**Discussion by MichaelTen** [open-webui/open-webui#4074] [General]
**Is your feature request related to a problem? Please describe.**
get mem0 working with openwebUI... 

https://github.com/mem0ai/mem0

**Describe the solution you'd like**
some api or integration.. or at least have it be compatible with decent documentation. possibly via docker. 

**Describe alternatives you've considered**
i thought about trying to test it myself. someone on the mem0 discord who seemed reputable indicated that mem0 does not yet work with ollama. 

**Additional context**
openWebUI+Ollama+Llama3-8B(or more).. + mem0.. could be good. 

thanks and limitless peace.

**Comment by Tuxaios** [comment]
Is this plan feasible now?
openwebui + ollama + mem0

**Reply by Tuxaios** [reply]
@MichaelTen

**Reply by MichaelTen** [reply]
i'm not sure. is it now?

**Comment by bgeneto** [comment]
What about this pipeline?

https://github.com/open-webui/pipelines/blob/main/examples/filters/mem0_memory_filter_pipeline.py

**Reply by Tuxaios** [reply]
I can't integrate it. Do you have a ready-made version?

**Reply by bgeneto** [reply]
Unfortunately not...

**Reply by TurboEncabulator9000** [reply]
I got this set up, but it throws a 500 error.

```
openwebui  | 2025-03-07 01:37:21.863 | INFO     | uvicorn.protocols.http.httptools_impl:send:468 - 192.168.65.1:44973 - "POST /api/v1/chats/ebc3c1f5-45b3-4eb7-8172-65507d280cdc HTTP/1.1" 200 - {}
openwebui  | 2025-03-07 01:37:21.873 | INFO     | uvicorn.protocols.http.httptools_impl:send:468 - 192.168.65.1:44973 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 - {}
qdrant     | 2025-03-07T01:37:21.983394Z  INFO actix_web::middleware::logger: 192.168.65.1 "POST /collections/memories/points/query HTTP/1.1" 200 80 "-" "qdrant-client/1.13.3 python/3.11.11" 0.002069    
pipelines  | pipe:mem0_memory_filter_pipeline
pipelines  | 0
pipelines  | INFO:     172.18.0.2:33588 - "POST /mem0_memory_filter_pipeline/filter/inlet HTTP/1.1" 500 Internal Server Error
openwebui  | 2025-03-07 01:37:21.985 | INFO     | uvicorn.protocols.http.httptools_impl:send:468 - 192.168.65.1:44973 - "POST /api/chat/completions HTTP/1.1" 400 - {}
openwebui  | 2025-03-07 01:37:21.997 | INFO     | uvicorn.protocols.http.httptools_impl:send:468 - 192.168.65.1:44973 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 - {}
```

If anyone wants to give it a whirl, here's a Dockerfile:
```
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    restart: always
    ports:
      - "9099:9099"
    environment:
      - PIPELINES_URLS=https://github.com/open-webui/pipelines/blob/main/examples/filters/mem0_memory_filter_pipeline.py
    volumes:
      - pipelines_data:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: always
    ports:
      - "3000:8080"
    environment:
      - WEBUI_AUTH=false
      - OPENAI_API_BASE_URL=http://pipelines:9099
      - OPENAI_API_KEY=(some clever password)
    volumes:
      - open-webui_data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  qdrant_data:
  pipelines_data:
  open-webui_data:
```

PS: (some clever password) is, by default, 0p3n-w3bu!. (That's baked into the source somewhere, it's not a secret.)
