### DISCUSSION TITLE
Redirect URI Mismatch Causing Authentication Error Due to HTTP Instead of HTTPS Configuration

### DISCUSSION THREAD

**Discussion by avononit** [open-webui/open-webui#4077] [General]
# Bug Report

## Description

**Bug Summary:**
The redirect URI for the application specified in the Azure portal does not match the URI used in the request, causing an authentication error.

**Steps to Reproduce:**
1. Attempt to authenticate using the application with the following redirect URI: `http://chatbot.url.com/oauth/microsoft/callback`.
2. Observe the error message indicating a mismatch in the redirect URI.

**Expected Behavior:**
The authentication should proceed successfully without any errors, using the correct redirect URI.

**Actual Behavior:**
The authentication fails with the error message: 
```
AADSTS50011: The redirect URI 'http://chatbot.url.com/oauth/microsoft/callback' specified in the request does not match the redirect URIs configured for the application 'placeholder-application-id'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
```

## Environment

- **Open WebUI Version:** v0.3.10

- **Ollama (if applicable):** 0.2.8

- **Operating System:** macOS
- **Browser (if applicable):** Chrome

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
n/a

**Docker Container Logs:**
n/a

**Screenshots (if applicable):**
n/a

## Installation Method

Manual installation via Azure portal configuration.

## Additional Information

To resolve this issue, the redirect URI needs to be updated to use HTTPS instead of HTTP:
- Change `http://chatbot.url.com/oauth/microsoft/callback` to `https://chatbot.url.com/oauth/microsoft/callback`.

This application is running behind HAProxy.

## docker-compose.yml
```

services:
  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8005:8080 #running behind haproxy
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_URL=https://chatbot.url.com'
      - 'OPENAI_API_KEY=key'
      - 'MICROSOFT_CLIENT_ID=client-id'
      - 'MICROSOFT_CLIENT_TENANT_ID=tenant-id'
      - 'MICROSOFT_CLIENT_SECRET=secret'
      - 'WEBUI_SESSION_COOKIE_SECURE=true'
    restart: unless-stopped
```
