### DISCUSSION TITLE
Cohere Reranking

### DISCUSSION THREAD

**Discussion by erickirsten** [open-webui/open-webui#4412] [Q&A] [answered]
How can something like https://cohere.com/rerank be used as a reranking model with Hybrid Search enabled? 

Is it possible?

**Comment by justinh-rahb** [comment, marked as answer]
Not currently possible, there's no other support in WebUI for re-ranking done by any other method than the built-in Sentence-Transformers based solution.

**Reply by athoik** [reply]
I am using Cohere Reranking through [LiteLLM](https://www.litellm.ai/).

LiteLLM config.yml

```
  - model_name: cohere-rerank-v3.5
    litellm_params:
      model: azure_ai/Cohere-rerank-v3-5-xxx
      api_base: https://<...>.swedencentral.models.ai.azure.com/
      api_key: ...
    model_info:
      mode: rerank
```

OpenWebUI 

<img width="966" height="223" alt="image" src="https://github.com/user-attachments/assets/5a494a5c-e101-4d75-93a6-4227c8d1a4a7" />

All working fine here.

So it's currently, (several months actually) really possible @Fry2712 @justinh-rahb

**Reply by athoik** [reply]
Please note, above LiteLLM configuration, is specific for using Cohere though Azure.

If you are going to use directly Cohere API you need the following.

LiteLLM config.yml (note that API key is read by COHERE_API_KEY environment variable)

```
  - model_name: cohere-rerank-v3.5
    litellm_params:
      model: cohere/rerank-v3.5
    model_info:
      mode: rerank
```

Example docker compose, using stable version tagging.

```
  litellm-proxy:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: litellm-proxy
    restart: always
    ports:
      - "4000:4000"
    environment:
      - COHERE_API_KEY=sk-1234....
    volumes:
      - /opt/litellm/litellm_config.yaml:/app/config.yaml
    command: ["--config", "/app/config.yaml", "--detailed_debug"]
```
