### DISCUSSION TITLE
Not able to start Docker Container | USER_AGENT environment variable not set, consider setting it to identify your requests.

### DISCUSSION THREAD

**Discussion by AmoghSaxena** [open-webui/open-webui#4463] [General]
# Bug Report
NOT ABLE TO START THE CONTAINER
## Installation Method
DOCKER COMMAND WITH OPENAI API_KEY

[Describe the method you used to install the project, e.g., git clone, Docker, pip, etc.]

I am not able to start the docker container with the command mentioned in the document. 

When I start the docker with the command given the container runs for few second and then restart automatically.

Logs are mentioned below:
```logs
root@rpi4:~/openWebUI# docker logs -f 2c4f7aabe89d
Loading WEBUI_SECRET_KEY from file, not provided as an environment variable.
Generating WEBUI_SECRET_KEY
Loading WEBUI_SECRET_KEY from .webui_secret_key
USER_AGENT environment variable not set, consider setting it to identify your requests.



```

Please someone guide me with the process.

**Comment by themw123** [comment]
https://github.com/open-webui/open-webui/discussions/4331

**Comment by jsoques** [comment]
You can try adding a USER_AGENT variable in the environment entry in the docker-compose.yml file. For example:

```
name: openwebui
services:
    open-webui:
        ports:
            - 3333:8080
        environment:
            - OLLAMA_BASE_URL=http://10.0.0.64:11434
            - USER_AGENT=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
        volumes:
            - /home/whothis/open-webui/data:/app/backend/data
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:main
volumes:
    open-webui:
        external: true
        name: open-webui

```
