### DISCUSSION TITLE
Adding vertical spacing to document elements for better readability

### DISCUSSION THREAD

**Discussion by rotemdan** [open-webui/open-webui#4643] [Ideas]
There is currently no added spacing around:
* Paragraphs
* Ordered lists
* Unordered lists
* List items
* Headers
* Tables
* Model name in chat bubble

making the layout look a bit cramped.

I'm currently using the [Stylus extension](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) with the following CSS code to modify the default stylesheet. This allows me to easily experiment with different variations:

```css
@-moz-document domain("localhost") {
    .chat-assistant,
    .chat-user {
        & p:not(:last-child),
        & ul:not(:last-child),
        & ol:not(:last-child),
        & table:not(:last-child) {
            margin-bottom: 1.0em;
        }
        
        & h1:not(:last-child), 
        & h2:not(:last-child),
        & h3:not(:last-child),
        & h4:not(:last-child) {
            margin-bottom: 0.5em; 
        }
        
        & li:not(:last-child) {
            margin-bottom: 0.25em;
        }
    }
    
    .chat-assistant > div:first-child {
        margin-top: 0.5em;   
    }
}
```
(**Edit 1**: I've updated the stylesheet with modifications added in later messages.)
(**Edit 2**: Updated class selectors to work with latest `open-webui` version)

## Before:

![Screenshot_2](https://github.com/user-attachments/assets/0e21e12a-d5d0-47e1-a4b0-a4b1b90521f4)

## After:

![Screenshot_3](https://github.com/user-attachments/assets/73bbad65-5d29-474c-b912-3cebec83d0d9)

**Comment by Algorithm5838** [comment]
I agree. 
Here is my workaround as inspired by you:
```css
@-moz-document domain("localhost") {
    .prose.chat-assistant,
    .prose.chat-user {
        & p:not(:last-child),
        & ul:not(:last-child),
        & ol:not(:last-child) {
            margin-bottom: 1em;
        }
    }
}
```

**Comment by rotemdan** [comment]
Thanks for the improvement, I was just thinking about not adding to the margins to the last child, when you just posted this.

`chat-user` us currently using a single `pre` element, so the margin doesn't have an effect on it, but that doesn't matter for now.

I added tables and headers as well (Gemini generates tables and headers frequently). I decided to give headers 0.5em margin since I felt 1.0em was too much.

```css
@-moz-document domain("localhost") {
    .prose.chat-assistant,
    .prose.chat-user {
        & p:not(:last-child),
        & ul:not(:last-child),
        & ol:not(:last-child),
        & table:not(:last-child) {
            margin-bottom: 1.0em;
        }
        
        & h1:not(:last-child), 
        & h2:not(:last-child),
        & h3:not(:last-child),
        & h4:not(:last-child) {
           margin-bottom: 0.5em; 
        }
    }
}
```

## Before:

![Screenshot_3](https://github.com/user-attachments/assets/631c8003-2cbd-4c5b-a51c-c12488305d0e)

## After:

![Screenshot_1](https://github.com/user-attachments/assets/c9ebeade-5c03-41a7-b8cb-512bd2e05980)

**Comment by rotemdan** [comment]
List items could benefit from small bottom margins. I gave them `0.25em`. Here's my updated stylesheet:

```css
@-moz-document domain("localhost") {
    .prose.chat-assistant,
    .prose.chat-user {
        & p:not(:last-child),
        & ul:not(:last-child),
        & ol:not(:last-child),
        & table:not(:last-child) {
            margin-bottom: 1.0em;
        }
        
        & h1:not(:last-child), 
        & h2:not(:last-child),
        & h3:not(:last-child),
        & h4:not(:last-child) {
            margin-bottom: 0.5em; 
        }
        
        & li:not(:last-child) {
            margin-bottom: 0.25em;
        }
    }
    
    .prose.chat-assistant > div:first-child {
        margin-top: 0.5em;   
    }
}
```
(**Edit**: added a small upper margin to the outer `div` element of the `chat-assistant` element to give some spacing between the model name to the model's text - that's the best way I could find to do that, but it could be done in other ways - this one was the easiest to select)

## Before:

![Screenshot_2](https://github.com/user-attachments/assets/0e21e12a-d5d0-47e1-a4b0-a4b1b90521f4)

## After:

![Screenshot_3](https://github.com/user-attachments/assets/73bbad65-5d29-474c-b912-3cebec83d0d9)

**Comment by Algorithm5838** [comment]
I just kept at 1.
Here are my changes. Note that I had to remove '.prose' for it to work in the dev branch:
```css
@document domain("localhost") {
    .chat-assistant,
    .chat-user {
        & :is(p, h1, h2, h3, h4, h5, h6, table, pre, blockquote, ul, ol):not(:last-child) {
            margin-bottom: 1em;
        }
    }
}
```

**Comment by rotemdan** [comment]
I chose to use 0.5em for headers because I felt that 1em was a bit too much. `em` is relative measure, meaning that the larger font size, the larger the margin. 

For an h2, the rendered font size is 24px. If you leave a margin of 1em, it means you get a margin of 24px, which would create a "gap" in the text. I checked other website like GitHub and Mistral chat interface, and they have a bottom of margin about 0.5em - 0.6em for headers.

I also added a 0.25em margin for list items since I felt they were visually too close together, especially after adding the spacing for other elements.

I also later added 0.5em spacing between the model name and the text, since it looked too close together:
```css
    .prose.chat-assistant > div:first-child {
        margin-top: 0.5em;   
    }
```

Here's how a 0.5em and 1em spacing for an h2 looks like:

## 0.5em:
![Screenshot_4](https://github.com/user-attachments/assets/52db9f38-a364-49f4-8fde-bd8b389443e0)

The heading in the screenshot has a margin of 0.5em, if I change it to 1em instead, it would look like:

## 1em:
![Screenshot_5](https://github.com/user-attachments/assets/6e1b2cf9-483b-4c6c-becf-7ae04d820bde)

# Example for h3:

## 0.5em:
![Screenshot_7](https://github.com/user-attachments/assets/f820003b-4f17-4885-a1f5-0370a316c53d)

## 1em:
![Screenshot_6](https://github.com/user-attachments/assets/91dc03fc-5f24-4718-8cf9-0e45d80f71da)
