### DISCUSSION TITLE
Add support for Github models

### DISCUSSION THREAD

**Discussion by NekodRider** [open-webui/open-webui#5246] [General]
**Is your feature request related to a problem? Please describe.**
Support [Github Models](https://github.com/marketplace/models). Current configurable OpenAI API endpoint solution will encounter `400 Bad Request` because the model id is wrong.

**Describe the solution you'd like**
Github Models supports using OpenAI SDK with custom endpoint(https://models.inference.ai.azure.com), so it works as an OpenAI-compatible API for sure. But the [model list](https://models.inference.ai.azure.com/models) is different and we need the `name` instead of `id`.

```json
{
    "id": "azureml://registries/azure-openai/models/gpt-4o-mini/versions/1",
    "name": "gpt-4o-mini",
    "friendly_name": "OpenAI GPT-4o mini",
    "model_version": 1,
    "publisher": "Azure OpenAI Service",
    "model_family": "OpenAI",
    "model_registry": "azure-openai",
    "license": "custom",
    "task": "chat-completion",
    "description": "GPT-4o mini enables a broad range of tasks with its low cost and latency, such as applications that chain or parallelize multiple model calls (e.g., calling multiple APIs), pass a large volume of context to the model (e.g., full code base or conversation history), or interact with customers through fast, real-time text responses (e.g., customer support chatbots).\n\nToday, GPT-4o mini supports text and vision in the API, with support for text, image, video and audio inputs and outputs coming in the future. The model has a context window of 128K tokens and knowledge up to October 2023. Thanks to the improved tokenizer shared with GPT-4o, handling non-English text is now even more cost effective.\n\nGPT-4o mini surpasses GPT-3.5 Turbo and other small models on academic benchmarks across both textual intelligence and multimodal reasoning, and supports the same range of languages as GPT-4o. It also demonstrates strong performance in function calling, which can enable developers to build applications that fetch data or take actions with external systems, and improved long-context performance compared to GPT-3.5 Turbo.\n\n## Resources\n\n- [OpenAI announcement](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/)\n",
    "summary": "An affordable, efficient AI solution for diverse text and image tasks.",
    "tags": [
      "multipurpose",
      "multilingual",
      "multimodal"
    ]
  },
```

**Comment by VINTX2** [comment]
There is a working function for this:
https://openwebui.com/f/jscheah/github_models_manifold

**Reply by akang943578** [reply]
How to use this?

**Comment by YuenSzeHong** [comment]
it seems `https://models.inference.ai.azure.com/models` don't return full list of models available on `https://github.com/marketplace/models`, newer models, like o1, llama 3.2 are not available there, any ideas?

**Comment by avcode-exe** [comment]
You can use litellm with a config file and docker.

My config:
```yaml
model_list:
  - model_name: Gemini 1.5 Pro 002
    litellm_params:
      model: gemini/gemini-1.5-pro-002
      api_key: "os.environ/GEMINI_API_KEY"
  - model_name: Gemini 1.5 Flash 002
    litellm_params:
      model: gemini/gemini-1.5-flash-002
      api_key: "os.environ/GEMINI_API_KEY"
  - model_name: GPT4o Mini
    litellm_params:
      model: github/gpt-4o-mini
      api_key: "os.environ/GITHUB_MARKETPLACE_API_KEY"
  - model_name: Mistral Large
    litellm_params:
      model: mistral/mistral-large-latest
      api_key: "os.environ/MISTRAL_API_KEY"
  - model_name: Hermes 3 Llama 3.1 405B
    litellm_params:
      model: openai/nousresearch/hermes-3-llama-3.1-405b:free
      api_base: "https://openrouter.ai/api/v1"
      api_key: "os.environ/OPENROUTER_API_KEY"
  - model_name: GLHF Llama3.1 405B
    litellm_params:
      model: openai/hf:meta-llama/Meta-Llama-3.1-405B-Instruct
      api_base: "https://glhf.chat/api/openai/v1"
      api_key: "os.environ/GLHF_API_KEY"
  - model_name: 01AI YI Lightling
    litellm_params:
      model: openai/yi-lightning
      api_base: "https://api.lingyiwanwu.com/v1"
      api_key: "os.environ/01AI_API_KEY"
  - model_name: SambaNova Llama3.1 405B
    litellm_params:
      model: sambanova/Meta-Llama-3.1-405B-Instruct
      api_key: "os.environ/SAMBANOVA_API_KEY"
```
