### DISCUSSION TITLE
Google OAuth login completed with an error.

### DISCUSSION THREAD

**Discussion by dudt** [open-webui/open-webui#5267] [General]
```
version: "3.9"
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "13000:8080"
    environment:
      - WEBUI_URL=https://chat.****.com
      - OPENAI_API_KEY=sk-****
      - ENABLE_OAUTH_SIGNUP=true
      - GOOGLE_CLIENT_ID=******.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=*****
      - GOOGLE_REDIRECT_URI=https://chat.*.com/auth/google/callback
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL= true
      - WEBUI_SESSION_COOKIE_SECURE= true

    volumes:
      - ./open-webui:/app/backend/data

volumes:
  open-webui:
```

Google OAuth 重定向 URI：https://chat.****.com/auth/google/callback 

Problem reproduction: After clicking the Google account login, it redirects to the open-webui homepage, but the login was not successful. The console error is: 
![image](https://github.com/user-attachments/assets/d77baf80-c3cb-4e37-8f9e-5666694175dc)
