### DISCUSSION TITLE
Feature request: prometheus exporter

### DISCUSSION THREAD

**Discussion by itaybar** [open-webui/open-webui#5304] [General]
I think it would be great to add prometheus exporter to the backend, including rhe following metrics

request counter with model and tool used as labels
Error counter with model and tools labels
E2e bucket histogram

**Comment by JTHesse** [comment]
Great idea, I'm also looking for these functionalities!

**Comment by tkg61** [comment]
We could use this as well but also including metrics per person which is something that litellm can't do. we could use litellm for some of these metrics already but having per user or more openwebui integrated metrics would be helpuful here. Once it leaves the chat UI and goes to something like litellm it becomes too vague. I'd like to know who heavy users are and other users who have only sent 1 message.

**Comment by rhuddleston** [comment]
now that litellm move prometheus metrics to paid only this feature is more important https://github.com/BerriAI/litellm/issues/6209

**Reply by ncecere** [reply]
I created this, it might help you out for metrics from litellm

https://github.com/ncecere/exporter-litellm

**Comment by ncecere** [comment]
I have planned creating one based on information from the database, If I finish it I will share it.

**Reply by ncecere** [reply]
well that wasn't to bad

https://github.com/ncecere/exporter-openwebui

**Reply by tkg61** [reply]
Awesome! Any chance for a kubernetes compatible version or QuickStart guide?

**Reply by ncecere** [reply]
just pushed an update, readme docker compose, and the other markdown files should cover what you need.  I'll try to get a k8s one out too

**Reply by ncecere** [reply]
rough pass at a deployment.yml

```yml
apiVersion: v1
kind: Secret
metadata:
  name: openwebui-exporter-secrets
type: Opaque
stringData:
  OPENWEBUI_DB_PASSWORD: "your_password_here"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openwebui-exporter-config
data:
  OPENWEBUI_DB_NAME: "openwebui"
  OPENWEBUI_DB_USER: "openwebui"
  OPENWEBUI_DB_HOST: "your_db_host"
  OPENWEBUI_DB_PORT: "5432"
  DB_MIN_CONNECTIONS: "5"
  DB_MAX_CONNECTIONS: "20"
  METRICS_UPDATE_INTERVAL: "1m"
  METRICS_REQUEST_WINDOW: "24h"
  METRICS_ERROR_WINDOW: "1h"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-exporter
  labels:
    app: openwebui-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui-exporter
  template:
    metadata:
      labels:
        app: openwebui-exporter
    spec:
      containers:
      - name: exporter
        image: nicholascecere/exporter-openwebui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          name: metrics
        envFrom:
        - configMapRef:
            name: openwebui-exporter-config
        - secretRef:
            name: openwebui-exporter-secrets
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: openwebui-exporter
  labels:
    app: openwebui-exporter
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: openwebui-exporter

```
