### DISCUSSION TITLE
feat: FIM Completions

### DISCUSSION THREAD

**Discussion by rndmcnlly** [open-webui/open-webui#5398] [Ideas]
**Is your feature request related to a problem? Please describe.**
I want to allow my students to configure their [Continue](https://www.continue.dev/) VS Code extensions to use my OWUI server as the endpoint for _code completion_ calls. I'm teaching a programming related course and already planning to offer them a support chatbot via OWUI. If a FIM (fill-in-middle) completion endpoint were available, they could access in-editor code support as well (using the API keys they can get for themselves in the OWUI user settings pages).

**Describe the solution you'd like**
Offer an endpoint compatible with the [FIM completion endpoint from Deepseek](https://platform.deepseek.com/api-docs/api/create-completion). In the same way that we have the `/openai` route, we might have a `/deepseek` route or the like. The main difference from normal text completion is the including of a `suffix` parameter. Maybe it would also work to support an optional `suffix` parameter on some existing text completion endpoint.

**Describe alternatives you've considered**
I can already use models like [`deepseek-coder-v2`](https://ollama.com/library/deepseek-coder-v2) via Ollama. Presumably I could use the *through* OWUI if I had a Ollama backend configured. However, I'm planning to use Deepseek's hosted API service. Currently, my students can have normal chat conversations with the Deepseek model if I configure it as an alternate OpenAI-compatible URL. However, this doesn't help them in their editor (VS Code).

**Additional context**
Here's how the Continue extension accesses the Deepseek API for FIM completions: https://github.com/continuedev/continue/blob/3791774e45ae87821f6539f38da5c0752d63fe4f/packages/openai-adapters/src/apis/DeepSeek.ts#L22

**Comment by sergeijakovlev** [comment]
Hi! This is probably too late to help you, but perhaps will aid someone else looking for this. `openai` provider itself still does not support FIM. Multiple providers, however, extend `openai` with minimal changes specifically to enable FIM support. Both `${apiBase}/completions`  and `${apiBase}/v1/chat/completions` endpoints seem to work with Open WebUI v0.6.15.

Options that work:
- `inception` - uses `apiBase/completions` endpoint and temperature: 0.0 for completions;
- `siliconflow` (also adds rerank, have not tested how that affects anything).

Options that do not work:
- `deepseek` - uses `apiBase/beta/completions` path;
- `llamastack` - is not listed by Continue for autocomplete at all;
- `moonshot` - tries to send some requests to `api.moonshot.cn` regardless of overridden base path.

The config I ended up with:

```
name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: qwen2.5-coder:14b
    provider: inception 
    model: qwen2.5-coder:14b
    apiBase: https://openwebui.internal/ollama/v1
    apiKey: placeholder
    roles:
      - autocomplete
      - chat
      - edit
      - apply
  - name: deepseek-coder-v2:16b
    provider: inception
    model: deepseek-coder-v2:16b
    apiBase: https://openwebui.internal/ollama/v1
    apiKey: placeholder
    roles:
      - autocomplete
      - chat
      - edit
      - apply
  - name: phi4-reasoning:plus
    provider: openai
    model: phi4-reasoning:plus
    apiBase: https://openwebui.internal/ollama/v1
    apiKey: placeholder
    roles:
      # phi4-reasoning:plus does not seem to support FIM according to the template
      - chat
      - edit
      - apply
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
```
