### DISCUSSION TITLE
Is there a way to use Internal's Host Ollama in Development mode?

### DISCUSSION THREAD

**Discussion by andreafuturi** [open-webui/open-webui#5630] [General]
**Is your feature request related to a problem? Please describe.**
I'm would like to contribute to Open Web UI but I get this error both with localhost and 127.0.0.1
backend-1   | INFO:     Waiting for application startup.
backend-1   | INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
backend-1   | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
backend-1   | INFO:     Application startup complete.
backend-1   | INFO  [open_webui.apps.openai.main] get_all_models()
backend-1   | INFO  [open_webui.apps.ollama.main] get_all_models()
backend-1   | ERROR [open_webui.apps.ollama.main] Connection error: Cannot connect to host 127.0.0.1:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]

**Describe the solution you'd like**
I have Ollama on my MacBook I don't need it in docker, any way to use my Ollama instead of the docker one?

**Describe alternatives you've considered**
Any possibile solution is fine but I would prefer to use Ollama on my MacBook since I use it also for other things

**Additional context**
I followed this tutorial:
https://docs.openwebui.com/tutorial-development/#in-docker-container

**Comment by ZeKap** [comment]
Same issue here too.
Tried `host.docker.internal::11434`, `127.0.0.1:11434`, `localhost:11434`, `172.17.0.1:11434` for Ollama API.
Ollama is on host (Linux here) and open-webui in docker. I tried with this docker-compose:
``` yaml
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    restart: always
    environment:
      WEBUI_NAME: "A super name"
      WEBUI_URL: "edited for privacy"
      PORT: "3900"
      #OLLAMA_BASE_URL: "http://localhost:11434"
    ports:
      - "3900:3900"
    volumes:
      - /var/www/open-webui/config:/app/backend/data
      #network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

I tried with and without editing port, with and without network_mode, with and without extra_hosts.
No matter what I put in OLLAMA_BASE_URL, nothing works and I have the toast error: "WebUI could not connect to Ollama". And I tried editing it in admin panel too
