### DISCUSSION TITLE
[BUG] login succeeds but UI displays no content

### DISCUSSION THREAD

**Discussion by aleontiev** [open-webui/open-webui#5987] [General]
# Bug Report

## Installation Method

Kubernetes via Helm

## Environment

- **Open WebUI Version:** was happening on v0.3.30, tried upgrading to v0.3.32 but same issue
- **Ollama**: disabled
- **Pipelines**: disabled

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

After login, I am able to use OpenWebUI. This was the case for the first day after installation - had no issues, was able to login with username/password and also with Google OAuth.

## Actual Behavior:

Login is successful, I can see the toast message indicating that I have signed in. However, afterwards the screen remains blank and I can see errors in console:

![image](https://github.com/user-attachments/assets/70ec9d5e-976c-418b-8931-a19ab4686873)

...and network tab shows that some (but not all??) of the startup API requests are failing with 401 errors, particularly "tools" and sometimes "banners":

![image](https://github.com/user-attachments/assets/84579237-3e25-4be4-92ba-960381fa338b)

I tried clearing localStorage and cookies, this resets the login. But after logging in again, same issue. Nothing obvious in backend logs except for the 401s I am seeing on the client side. All other requests are 200s

## Description

See Expected/Actual

## Reproduction Details

**Steps to Reproduce:**
- Install on Kubernetes via Helm (mostly default settings, Ollama and Pipelines disabled)
- Create initial account
- Log out
- Log back in
 
## Logs and Screenshots

See Actual Behavior

## Additional Information

Loved using OpenWebUI for about a day until this started happening consistently :(

**Comment by tjbck** [comment]
Seems to be a browser cache issue, keep us updated!

**Reply by esciron** [reply]
> Seems to be a browser cache issue, keep us updated!

I don't think so, something similar is happening to me and is on every browser after updating from 3.30 to 3.32. The only error I can find in the console is "GET /api/v1/documents/ HTTP/1.1" 404 Not Found

![not loading](https://github.com/user-attachments/assets/2ef61665-5ef3-49fb-8d81-5dfc6d9aaa46)

EDIT: Just replaced the backend files with the 3.29 and it's working perfectly. This has something to do with the more recent updates. Probably 3.31 or 3.32.
Yes, can confirm, last working backend is the 3.30 version, 3.31 do not show any UI after logging.

**Reply by tjbck** [reply]
`/documents` endpoint has been deprecated from 0.3.31, and Open WebUI does not make any requests to that endpoint anymore. Vast majority of people cannot reproduce your issue. Have you tried visiting the webui from incognito mode to 100% rule out the cache issue?

**Reply by aleontiev** [reply]
I've tried with Incognito / removing all site data and I'm still experiencing this

**Reply by aleontiev** [reply]
Is there anything that might cause inconsistencies with the SECRET_KEY -- I'm now seeing that the `banners` and `tools` API calls are no longer failing, but `functions` and `knowledge` are failing with 401s. All requests being sent with the same token. It makes me think the API server is referencing another secret key in some requests, hence the JWT is failing to verify.

**Reply by esciron** [reply]
> `/documents` endpoint has been deprecated from 0.3.31, and Open WebUI does not make any requests to that endpoint anymore. Vast majority of people cannot reproduce your issue. Have you tried visiting the webui from incognito mode to 100% rule out the cache issue?

Of course I did, I already mentioned I also used different browsers.
This is on windows 10, happens in 2 different machines with manual installation in both. Previously installed version -> Just regular git pull origin main and then the requirements, I had updated open webui on those pc before with no problem, is only with 3.31+ that this is happening.

**Reply by tjbck** [reply]
Very strange indeed, I'm unable to reproduce any of the issues here unfortunately so I would greatly appreciate if you let us know your findings!

**Reply by arjoonn-s** [reply]
This is also affecting us. Our setup was simpler.

1. docker compose file with ollama and webui running in it.
2. Served over https with our caddyfile.
3. We can access stuff if we work with `localhost:8080` but if we go via our domain after the login nothing works.
    - We can see that a few APIs fail with 401.
    - The first one to fail is `/api/v1/auths/`.
    - A notable difference in this and the 8080 api call is that in the proxied version only `token` is sent in the cookies whereas in `8080` session and csrftoken is also sent.
    
    
```
name: mp_ollama

services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - mp_ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - mp_ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    environment:
      - WEBUI_SESSION_COOKIE_SECURE=true
      - DEFAULT_USER_ROLE=admin
      - OLLAMA_BASE_URL=http://ollama:11434
      - RAG_EMBEDDING_ENGINE=ollama
      - AUDIO_STT_ENGINE=openai
      - IMAGE_GENERATION_ENGINE=openai
        # ----
      - WEBUI_AUTH=false
      - X_OAUTH_CLIENT_ID=asdf
      - X_OAUTH_CLIENT_SECRET=asdf
      - X_OPENID_PROVIDER_URL=https://gitea.asdf.com/.well-known/openid-configuration
      - X_OAUTH_PROVIDER_NAME=Gitea
    ports:
      - "8080:8080"
    volumes:
      - mp_ollama_webui:/app/backend/data
    depends_on:
      - ollama
    networks:
      - mp_ollama

  tunnel:
    build: tunnel
    restart: always
    command: sh /app/run.sh
    environment:
      BASTION: mp.asdf
    volumes:
      - ~/.ssh:/host_ssh:ro
    networks:
      - mp_ollama

volumes:
  mp_ollama_data:
    name: ollama_data
  mp_ollama_webui:
    name: ollama_webui

networks:
  mp_ollama:
    driver: bridge
```

Our caddyfile 

```
ollama.asdf.com {
        import logging
        basicauth /* {
                import employees_only
        }

        encode gzip

        handle {
                reverse_proxy http://127.0.0.1:11435
        }
}
```
