### DISCUSSION TITLE
o1-preview should work out-of-the-box

### DISCUSSION THREAD

**Discussion by Nitschi** [open-webui/open-webui#6915] [General]
# Bug Report

## Installation Method

Docker
docker-compose.yml:
```
services:
    open_webui:
        hostname: chatgpt
        image: ghcr.io/open-webui/open-webui:git-96c8654
        ports:
            - "8080:8080"
        environment:
            - WEBUI_URL=http://localhost:8080
            - ENABLE_SIGNUP=True
            - DEFAULT_MODELS="gpt-4o"
            - ENABLE_OLLAMA_API=False
            - ENABLE_OPENAI_API=True
            - OPENAI_API_KEY=$OPENAI_API_KEY
            - TASK_MODEL="gpt-4o"
```

## Environment

- **Open WebUI Version:** v0.3.35
- **Ollama (if applicable):** -

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Firefox 131.0.3 (64-bit)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I set up Open WebUI with `docker compose up`, register a user, create a new chat, select `o1-preview` as a model and can ask a question and get an answer.

## Actual Behavior:

I set up Open WebUI with `docker compose up`, register a user, create a new chat, select `o1-preview` as a model.

Instead of an Answer I get the following error:
"""
Uh-oh! There was an issue connecting to o1-preview.
Unsupported value: 'stream' does not support true with this model. Supported values are: false.
""
![image](https://github.com/user-attachments/assets/3231db0c-b0ab-4fcb-a423-195851edfe1a)

## Description

**Bug Summary:**
o1-preview model returns error, but should work with the default configuration.

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Docker Container Logs:**
[logs.txt](https://github.com/user-attachments/files/17730054/logs.txt)

## Additional Information

I am aware of https://github.com/open-webui/open-webui/pull/5645 which enables a workaround, when I go into the settings, but in my opinion there should be some way that this will work out of the box.
Otherwise manual steps are needed after deployment, which I would like to avoid.
