### DISCUSSION TITLE
REST API docs not found any more

### DISCUSSION THREAD

**Discussion by Ex0ry** [open-webui/open-webui#6978] [General]
# Bug Report

## Installation Method

Docker Compose:
```yaml
services:
  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    # Expose Ollama API outside the container stack
    #ports:
      #- ${OLLAMA_WEBAPI_PORT-11434}:11434

  open-webui:
    build:
      context: ./git/open-webui
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
```

## Environment

- **Open WebUI Version:** v0.3.35
- **Ollama (if applicable):** v0.4.1

- **Operating System:** Win11
- **Browser (if applicable):** Any browser

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Fast API Docs are shown.

## Actual Behavior:

![image](https://github.com/user-attachments/assets/8efd6325-0ebe-411f-9b39-b878b1376484)

## Description

**Bug Summary:**
None of the Swagger Documentation Links are reachable.

## Reproduction Details
Try to access any /docs page that is mentioned at https://docs.openwebui.com/getting-started/advanced-topics/api-endpoints#swagger-documentation-links.

Previously this has worked flawless.. (URL is the same and should be correct therefore.)

**Steps to Reproduce:**
--> See above
--> No steps needed as the docs do not open in the first place

## Logs and Screenshots

**Browser Console Logs:**
```
GET https://SOME_BASE_URL/ollama/docs 404 (Not Found)
```

**Docker Container Logs:**
```
open-webui  | INFO:     connection open
open-webui  | INFO:     10.12.14.78:0 - "POST /ws/socket.io/?EIO=4&transport=polling&t=PCmN7F9&sid=2X_6wvRqn6ng_SlWAAAB HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=websocket&sid=-31gBqysAsGkBqcRAAAC HTTP/1.1" 400 Bad Request
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=websocket&sid=2X_6wvRqn6ng_SlWAAAB HTTP/1.1" 400 Bad Request
open-webui  | INFO:     10.12.14.78:0 - "POST /ws/socket.io/?EIO=4&transport=polling&t=PCmN7F1&sid=-31gBqysAsGkBqcRAAAC HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:61950 - "POST /ws/socket.io/?EIO=4&transport=polling&t=PCmN7FA&sid=7Ojt52uVs30b7wEjAAAA HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:61964 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7FA.0&sid=7Ojt52uVs30b7wEjAAAA HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7F2&sid=-31gBqysAsGkBqcRAAAC HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7FA&sid=2X_6wvRqn6ng_SlWAAAB HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7Tw HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=websocket&sid=ubRMmQHzNG1-kyVaAAAG HTTP/1.1" 400 Bad Request
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7Fr&sid=2X_6wvRqn6ng_SlWAAAB HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7Fh&sid=-31gBqysAsGkBqcRAAAC HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "POST /ws/socket.io/?EIO=4&transport=polling&t=PCmN7U8&sid=ubRMmQHzNG1-kyVaAAAG HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7U8.0&sid=ubRMmQHzNG1-kyVaAAAG HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7YJ&sid=-31gBqysAsGkBqcRAAAC HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7YT&sid=2X_6wvRqn6ng_SlWAAAB HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ollama/docs HTTP/1.1" 404 Not Found
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN8DS HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=websocket&sid=_LqzS0E6VmVXfxspAAAI HTTP/1.1" 400 Bad Request
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7Ym&sid=2X_6wvRqn6ng_SlWAAAB HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7Yd&sid=-31gBqysAsGkBqcRAAAC HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN7Ya&sid=ubRMmQHzNG1-kyVaAAAG HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "POST /ws/socket.io/?EIO=4&transport=polling&t=PCmN8Dh&sid=_LqzS0E6VmVXfxspAAAI HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN8Dh.0&sid=_LqzS0E6VmVXfxspAAAI HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN8Dx&sid=2X_6wvRqn6ng_SlWAAAB HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN8Do&sid=-31gBqysAsGkBqcRAAAC HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PCmN8Dv&sid=ubRMmQHzNG1-kyVaAAAG HTTP/1.1" 200 OK
open-webui  | INFO:     10.12.14.78:0 - "GET /ollama/docs HTTP/1.1" 404 Not Found
open-webui  | INFO:     10.12.14.78:0 - "GET /ollama/docs HTTP/1.1" 404 Not Found
open-webui  | INFO:     10.12.14.78:0 - "GET /ollama/docs HTTP/1.1" 404 Not Found
open-webui  | INFO:     10.12.14.78:0 - "GET /ollama/docs HTTP/1.1" 404 Not Found
open-webui  | INFO:     10.12.14.78:0 - "GET /ollama/docs HTTP/1.1" 404 Not Found
open-webui  | INFO:     10.12.14.78:0 - "GET /ollama/docs HTTP/1.1" 404 Not Found
```
