### DISCUSSION TITLE
Issue with Open WebUI and Pipelines Connection

### DISCUSSION THREAD

**Discussion by sitzbrau** [open-webui/open-webui#7031] [Issues]
### Description
I am experiencing an issue with connecting to the pipelines in Open WebUI. Here are the details of the problem and the steps I have taken so far.

### Environment
**Docker Containers:**

- pipelines: ghcr.io/open-webui/pipelines:main
- ollama: ollama/ollama
- open-webui: ghcr.io/open-webui/open-webui:ollama

**Host:** Ubuntu on an EC2 instance
**Network Configuration:** Port 9099 allowed in the security group

### Steps to Reproduce
**Start the Containers:**
bash
```
docker run -d -p 9099:9099 -v pipelines:/app/pipelines --name pipelines ghcr.io/open-webui/pipelines:main
docker run -d --gpus=all -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
docker run -d -p 3000:8080 --gpus=all -v /var/lib/docker/volumes/ollama/_data:/root/.ollama -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:ollama
```

**Configure the Connection in Open WebUI:**

- Go to "Settings" > "Connections"
- Add or modify the connection with:
- URL: http://localhost:9099 (or http://host.docker.internal:9099)
- Key: 0p3n-w3bu!

### Expected Behavior
The connection to the pipelines should be established successfully, and the "Verify Connection" button should not show any errors.

### Actual Behavior
Despite the correct configuration, I receive the error "OpenAI: Network Problem" when verifying the connection.

### Additional Information
**Container Status**
The pipelines container is running and listening on port 9099:

```
CONTAINER ID   IMAGE                                  COMMAND               CREATED          STATUS                    PORTS                                           NAMES
a2fc21515249   ghcr.io/open-webui/pipelines:main      "bash start.sh"       13 hours ago     Up 18 minutes             0.0.0.0:9099->9099/tcp, :::9099->9099/tcp       pipelines
```

**Network Configuration**
The port 9099 is open and in use by the pipelines container:
bash
```
sudo netstat -tlnp | grep 9099

Output:
text
tcp        0      0 0.0.0.0:9099            0.0.0.0:*               LISTEN      1222/docker-proxy
tcp6       0      0 :::9099                 :::*                    LISTEN      1228/docker-proxy

```
**Logs of Pipelines Container**
The logs of the pipelines container show no critical errors:
bash
`docker logs pipelines
`
Output:
```

INFO:     Started server process [7]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9099 (Press CTRL+C to quit)
```

**Docker Inspect Output**
The docker inspect output for the pipelines container shows the correct configuration:
json
```
"HostConfig": {
    "Binds": [ "pipelines:/app/pipelines" ],
    "PortBindings": { "9099/tcp": [ { "HostIp": "", "HostPort": "9099" } ] },
   ...
}
```

**Steps Taken**

- Verified that localhost or host.docker.internal resolves correctly.
- Checked firewall rules to ensure port 9099 is not blocked.
- Tested the connection using curl http://localhost:9099.

**Request**
I would appreciate any help in identifying and resolving the issue that prevents the connection to the pipelines in Open WebUI.
Example Commands
bash
```
docker run -d -p 9099:9099 --add-host=host.docker.internal:host-gateway -v pipelines:/app/pipelines --name pipelines ghcr.io/open-webui/pipelines:main
docker logs pipelines
sudo netstat -tlnp | grep 9099
curl http://localhost:9099
```

_Thank you for your assistance._

**Comment by clduab11** [comment]
I'm having this exact same issue; Docker w/ bundled Ollama installed, upgraded to 0.4.1. Windows Powershell 7. 

I run the following command:

`docker run -d -p 9099:9099 --add-host=host.docker.internal:host-gateway -v pipelines:/app/pipelines --name pipelines --restart always ghcr.io/open-webui/pipelines:main`

And everything appears to work correctly; but I get a _lot_ of hangups and reconnects...

![image](https://github.com/user-attachments/assets/c08e2c16-fea4-4d44-a8a0-54b7c0f98a45)

It constantly loops like this. 

![image](https://github.com/user-attachments/assets/0bd1d3e4-5914-4c35-8f06-fe2f89f52549)
![image](https://github.com/user-attachments/assets/748d3304-7081-48dc-9e63-51f56ce8819c)
![image](https://github.com/user-attachments/assets/c3ff3c93-598b-43d3-aea7-b265a2c1ac5a)
![image](https://github.com/user-attachments/assets/b22ebf74-24dd-47fe-9884-df2c75c16147)

Everything seems to be in place and work fine, but the looping is causing the Network Problem I think, and when I say it seems like it saves... just fine? I'm not sure. I tried killing and removing the pipelines container, and I even tried system pruning to no avail...

I'm almost positive it's a me issue; I'm just still _**super**_ new to all this, so I've got some figuring out to do. But given it's a brand new version, I figured if someone else ran into it they'd know someone else is experiencing the same thing.

I should also note that I even tried to throw in a command to force-install and override the warnings, but to no avail. I did manage to start pulling stuff in per the Docker logs, but there's no end to the endless looping for a myriad of issues that I'm encountering.

**Comment by clduab11** [comment]
For what it's worth to those who find this helpful...

After doing some reconfiguring (my instance of Open WebUI/Ollama is ran as the docker-command that BUNDLES Ollama in with it, not just Ollama previously installed externally)...

Part of what was causing my pipelines connection to auto-drop/restart is due to running the command as is from the Pipelines Plugins GitHub here [https://github.com/open-webui/pipelines](url).

Instead, I wrapped the bundled Docker/Ollama command on open-webui's GitHub per normal, along with the pipelines launcher, and tika content extraction service into one docker-compose.yml as below...

```
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - "3000:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    restart: always
    depends_on:
      - tika

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      PIPELINES_URLS: "https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py"
    volumes:
      - ./pipelines:/app/pipelines
    restart: always
    depends_on:
      - open-webui

  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - "9998:9998"
    restart: always

volumes:
  pipelines:
    external: true
    name: pipelines
  ollama:
    external: true
    name: ollama
  open-webui:
    external: true
    name: open-webui
```

After deleting any running containers and making sure my .yml was in the place as where it needed to be, I just now run `docker-compose up -d` and once the command runs, all is well.

The issue that was throwing off the command and causing it issues was in my former version of this .yml (may be related to how the Pipeline Plugins commands is structured...)... is that in line 29, it originally was structureed as `- pipelines:/app/pipelines` when it **needed** to be `- ./pipelines:/app/pipelines` for it to function properly.

Many thanks to the Discord member meganoob1337 for reaching out to me on Reddit through my posts and trouble-shooting this issue for me!!
