### DISCUSSION TITLE
Setting Up Ollama-WebUI for Multi-GPU Usage

### DISCUSSION THREAD

**Discussion by ewijaya** [open-webui/open-webui#706] [General]
Hello,

I'm trying to configure Ollama-WebUI for use with multiple GPUs. Specifically, I aim to run `llama:34b-v1.6-fp16 69GB` on eight 16GB GPUs. While I've had success running it on a single GPU through the Ollama CLI, I'm encountering difficulties getting the WebUI to utilize multiple GPUs.

Here's what my current Ollama API URL setup looks like: 

<img width="650" alt="Screenshot 2024-02-11 at 15 43 10" src="https://github.com/ollama-webui/ollama-webui/assets/9668738/983095f4-df85-4383-a4ea-5a726ec6e719">

Despite this setup, I'm not able to get all GPUs to work together.

To set up the WebUI, I'm using the following command:

```
docker compose -f docker-compose.yaml -f docker-compose.gpu.yaml up -d --build
```

I've also included the relevant sections of my YAML configuration files: 

docker-compose.yaml file

```
version: '3.8'

services:
  ollama:
    volumes:
      - /home/ubuntu/storage1/ollama_models:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest

  ollama-webui:
    build:
      context: .
      args:
        OLLAMA_API_BASE_URL: '/ollama/api'
      dockerfile: Dockerfile
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    volumes:
      - ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OLLAMA_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  ollama-webui: {}
  ```
  
  docker-compose.gpu.yaml
  
  ```
  version: '3.8'

services:
  ollama:
    restart: unless-stopped
    # GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
 ```               

Does anyone know how to adjust the settings or setup so that Ollama-WebUI works with all my GPUs?

Thank you.
