### DISCUSSION TITLE
Auto Bounce to SSO if it's the only Login Option

### DISCUSSION THREAD

**Discussion by stsazama** [open-webui/open-webui#7337] [Ideas]
The way I have been using Open WebUI is with only the OIDC OAuth login option, so a user arrives at the login page just to click an extra "Continue with SSO" button. Would it make sense to redirect the user straight to `/oauth/{provider}/login` in this case, in the interest of having a seamless SSO process?
- If `WEBUI_AUTH` is enabled and user is not already logged in
- and `ENABLE_LOGIN_FORM` is false
- and there is only one OAuth provider

I think I have this working locally, although it may not be the best solution.

**Comment by thefury24** [comment]
Yes, this would be great.

**Reply by HarelKeren** [reply]
please implement that feature

**Comment by ranjithshivakumaraswamy** [comment]
@stsazama what is the work around solution you have built ? can you share ?

**Reply by thefury24** [reply]
Not OP, but what we did was edit the layout.svelte file in src/routes

You want to change the goto function from /auth to 						await goto('/oauth/oidc/login'); instead.

**Reply by ranjithshivakumaraswamy** [reply]
works thanks @stsazama !!

**Comment by ips972** [comment]
Can this auto SSO login be done when ldap/Active directory is used?? For local ent. Users?

**Comment by yushao2** [comment]
```
spec:
  gateways:
    - open-webui
  hosts:
    - open-webui.mycompany.com
  http:
    - match:
        - uri:
            regex: /(api|_app|static|ws|oauth).*
      route:
        - destination:
            host: open-webui.mycompany-open-webui.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /auth
          withoutHeaders:
            Cookie:
              regex: .*istio-prevent-further-redirects=1.*
      rewrite:
        uri: /oauth/oidc/login
      route:
        - destination:
            host: open-webui.mycompany-open-webui.svc.cluster.local
            port:
              number: 80
          headers:
            response:
              add:
                Cache-Control: no-store
                Pragma: no-cache
                Set-Cookie: istio-prevent-further-redirects=1; Max-Age=5
    - match:
        - uri:
            prefix: /
          withoutHeaders:
            Cookie:
              regex: (^|.*; *)token=.*
      rewrite:
        uri: /oauth/oidc/login
      route:
        - destination:
            host: open-webui.mycompany-open-webui.svc.cluster.local
            port:
              number: 80
          headers:
            response:
              add:
                Cache-Control: no-store
                Pragma: no-cache
                Set-Cookie: istio-prevent-further-redirects=1; Max-Age=5
    - match:
        - uri:
            prefix: /
          withoutHeaders:
            Cookie:
              regex: .*oauth_id_token=.*
      rewrite:
        uri: /oauth/oidc/login
      route:
        - destination:
            host: open-webui.mycompany-open-webui.svc.cluster.local
            port:
              number: 80
          headers:
            response:
              add:
                Cache-Control: no-store
                Pragma: no-cache
                Set-Cookie: istio-prevent-further-redirects=1; Max-Age=5
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: open-webui.mycompany-open-webui.svc.cluster.local
            port:
              number: 80
          headers:
            response:
              add:
                Cache-Control: no-store
                Pragma: no-cache
```

i got something very hacky to kinda work on istio virtualservice for our deployment on kubernetes
