### DISCUSSION TITLE
k8s: data persistent issue

### DISCUSSION THREAD

**Discussion by jkh1** [open-webui/open-webui#742] [General]
# Bug Report

## Description

**Bug Summary:**
I am running ollama-webui on k8s. I've had user accounts disappear on several occasions. In two cases this seems to have been caused by a k8s upgrade that restarted the pods. In another case, this seems to have been caused by a crash.

I believe this is because the user accounts are saved in the container. Can they be saved on a persistent volume instead? 
Can this be made configurable?

**Steps to Reproduce:**
Create user accounts. Stop the web ui pod and restart it.

**Expected Behavior:**
User accounts should still be there.

**Actual Behavior:**
User accounts are gone.

This could be a security issue because pods are automatically restarted and the first login becomes admin.

## Environment
Kubernetes 

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [ x] I have reviewed the troubleshooting.md document.

## Installation Method
kubectl apply -k ./kubernetes/manifest

**Comment by tjbck** [comment]
Hi, thanks for reporting this issue. Could you verify that everything is configured correctly and docker volume (`-v ollama-webui:/app/backend/data` flag) has been mounted to the webui? It sounds like the container was unable to find the same volume that was used previously. Keep us updated!

**Comment by jkh1** [comment]
Thanks for the quick reply. I can see /app/backend/data/ollama.db from inside the running container.

**Comment by jkh1** [comment]
Maybe this lack of persistence is due to a quirk of the k8s cluster I have access to. 
I think this is fixed by changing the webui deployment to a statefulset with a persistent volume claim mounted to /app/backend/data.
Fo this, I renamed webui-deployment.yaml to webui-statefulset.yaml and made the following changes:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama-webui
...
        resources:
          limits:
            cpu: "1000m"
            memory: "4Gi"
        volumeMounts:
        - name: webui-volume 
          mountPath: /app/backend/data
 ...       
  volumeClaimTemplates:
  - metadata:
      name: webui-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
```
Note that compared to the original from the repo, I increased the amount of memory because I thought it might have crashed due to an OOM error.
