### DISCUSSION TITLE
Ollama Track Version in Docker

### DISCUSSION THREAD

**Discussion by stondino00** [open-webui/open-webui#7434] [General]
We are running the most recent 0.4.6 of openweb-ui.

How do we track when ollama is updated in the openwebui's docker images?  Is there a changelog somewhere?

Looks like there is an update for ollama to 0.4.5.

![image](https://github.com/user-attachments/assets/0c70badb-9d1d-4db1-8e79-7652405746e3)

![image](https://github.com/user-attachments/assets/58182e49-ba04-4ebc-b831-946cce0b6eeb)

**Comment by clduab11** [comment]
Chiming in here to say I'm running the 0.4.7, but my Ollama version is also 0.4.2.

I'm running the OWUI instance w/ bundled Ollama inside Docker. At first I thought it was just how my YAML was configured...

Do we need to be figuring out a way to update Ollama separately? 0.5 has the new Llama3.3 70B model I'd like to see if I could try out.

```
services:
  webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - "3000:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=gpu,compute,utility
      - LOCAL_INTERFACE=1
      - PLUGIN_DOWNLOAD=1
    volumes:
      - ./openwebui:/root/.ollama
      - ./appdata:/app/backend/data
    networks:
      - shared-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PIPELINES_URLS="https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py"
    volumes:
      - pipelines:/app/pipelines
      - ./.data-pipelines:/app/pipelines 
    depends_on:
      webui:
        condition: service_healthy
    networks:
      - shared-network
    restart: always

  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - "9998:9998"
    networks:
      - shared-network
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300 # Check every 5 minutes
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_INCLUDE_STOPPED=true
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  pipelines:
    driver: local
  data:
    driver: local

networks:
  shared-network:
    driver: bridgeservices:
  webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - "3000:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=gpu,compute,utility
      - LOCAL_INTERFACE=1
      - PLUGIN_DOWNLOAD=1
    volumes:
      - ./openwebui:/root/.ollama
      - ./appdata:/app/backend/data
    networks:
      - shared-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PIPELINES_URLS="https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py"
    volumes:
      - pipelines:/app/pipelines
      - ./.data-pipelines:/app/pipelines 
    depends_on:
      webui:
        condition: service_healthy
    networks:
      - shared-network
    restart: always

  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - "9998:9998"
    networks:
      - shared-network
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300 # Check every 5 minutes
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_INCLUDE_STOPPED=true
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  pipelines:
    driver: local
  data:
    driver: local

networks:
  shared-network:
    driver: bridge
```
 
That's my YAML if I need to add a line for Ollama to be updated as well. I just don't know how to update it without installing Ollama locally, and I'd really prefer to keep the OWUI/bundled Ollama Docker instance configured how I have it.
