### DISCUSSION TITLE
Open WebUI - [CPU][Stack Portainer][Docker Swarm][Traefik]

### DISCUSSION THREAD

**Discussion by pedrofariasx** [open-webui/open-webui#7657] [Show and tell]
**Gostaria de compartilhar com vocês minha Stack Portainer, com Docker em Swarm + Traefik habilitado.**

```
version: "3.8"

services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    hostname: openwebui
    networks:
      - network_public
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.openwebui.rule=Host(`openwebui.seusite.com`)"
        - "traefik.http.routers.openwebui.entrypoints=websecure"
        - "traefik.http.routers.openwebui.priority=1"
        - "traefik.http.routers.openwebui.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.openwebui.service=openwebui"
        - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
    volumes:
      - open-webui-local:/app/backend/data
    environment:
      OLLAMA_BASE_URLS: http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    hostname: ollama
    networks:
      - network_public
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ollama-local:/root/ollama

volumes:
  ollama-local:
    driver: local
  open-webui-local:
    driver: local

networks:
  network_public:
    external: true

```
