### DISCUSSION TITLE
How to run non-docker AMD?

### DISCUSSION THREAD

**Discussion by thalesfsp** [open-webui/open-webui#7911] [General]
I see (https://github.com/open-webui/open-webui/blob/main/docker-compose.amdgpu.yaml) the docker version, what about non-Docker version? Need to set / install something? Best!

```
services:
  ollama:
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-rocm}
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION-11.0.0}'
```
