### DISCUSSION TITLE
Frontend Continues to Stream Content Character by Character After Model Output Completion in v0.5.0, Especially Noticeable with Fast-Response Models

### DISCUSSION THREAD

**Discussion by cr-zhichen** [open-webui/open-webui#8088] [General]
# Bug Report

## Installation Method

I installed Open WebUI using `docker-compose`.

## Environment

- **Open WebUI Version:** v0.5.0
- **Operating System:** Windows 10
- **Browser:** Edge 131.0.2903.112 (Official Build) (64-bit)

## Expected Behavior:

After the large model completes its output, the frontend should display the full content immediately, rather than slowly streaming it character by character.

## Actual Behavior:

Even after the large model has completed its output, the frontend continues to stream the content character by character at a slow pace. This issue is particularly noticeable with fast-response models like `o1-mini`, and the difference before and after upgrading to v0.5.0 is significant.

## Description

**Bug Summary:**
After upgrading to v0.5.0, the frontend continues to stream content character by character even after the large model has completed its output. This issue is especially pronounced with fast-response models like `o1-mini`.

## Reproduction Details

**Steps to Reproduce:**
1. Start Open WebUI using `docker-compose`.
2. Open the browser and access Open WebUI.
3. Use a fast-response model like `o1-mini` for a conversation.
4. Observe whether the frontend continues to stream content character by character after the model has completed its output.

## Additional Information

This issue only appeared after upgrading to Open WebUI v0.5.0. In previous versions, the frontend displayed content at a speed consistent with the model's output. However, after the upgrade, there is a noticeable delay in the frontend's display, especially with fast-response models.

**Comment by tjbck** [comment]
This is likely due to the fact that responses get saved every new chunk to enable async chat support. Optimization PRs are welcome, however I really don’t see a way to optimize. Faster server with better hardware will not experience this issue or at least the difference will be negligible.

**Reply by cr-zhichen** [reply]
The server I am using is equipped with an E5-2630 v2 processor and 64GB of RAM. I believe that the hardware of my server is relatively high-end, yet I am still encountering this issue. Therefore, I think the problem may not be closely related to the server's performance.

**Comment by tjbck** [comment]
I'm unable to reproduce the "latency" issue you're describing with 16gb mac m1.

https://github.com/user-attachments/assets/ec8d6304-f2a6-400c-89f1-18d42b059638

**Reply by cr-zhichen** [reply]
https://github.com/user-attachments/assets/ebb45bea-386e-4b16-8911-ac9ca620734a

I observed that during the response process, the server's hard drive maximum write speed even reached 30MB/s. I believe this is an unusual occurrence. In standby mode, the resource usage of my OpenWebUI and PostgreSQL is below 0.1%, but when a user engages in a chat, the usage of both the service and the database increases to over 5%.

**Reply by cr-zhichen** [reply]
> 20241226-141003.mp4 
> 我观察到，在响应过程中，服务器硬盘的最大写入速度甚至达到了 30MB/s。我认为这是不寻常的现象。在待机模式下，我的 OpenWebUI 和 PostgreSQL 的资源使用率均低于 0.1%，但当用户进行聊天时，服务和数据库的使用率都会上升至超过 5%。

The previous statement was incorrect. The 30MB/s write speed was caused by another user uploading images. I just tested it individually, and the user reported a write speed of approximately 600-1000KB/s.

**Comment by cr-zhichen** [comment]
Just now, while I was reviewing the source code, I noticed that every time the LLM returns a stream of data, it calls the upsert_message_to_chat_by_id_and_message_id method. Within this method, there is a direct call to update the database. I suspect that this is the reason why the response speed has slowed down.

**Comment by cr-zhichen** [comment]
https://github.com/user-attachments/assets/8d9dcb39-e788-4c1c-b9b0-506c26c3b2b7

The video above shows the deployment of versions v0.4.8 and v0.5.0 locally using Docker. The model being called is the local ollama's qwen2.5-code:7b. As can be clearly seen from the video, there is a noticeable difference in the output speed.

My `docker-compose.yml` files are as follows:

<details>
  <summary>v0.4.8</summary>

```yaml
version: '3.8'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.4.8
    container_name: openwebui-v0.4.8
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - 9021:8080
    environment:
      - WEBUI_AUTH=false
      - DATABASE_URL=postgresql://openwebui:9PF3R6tk95yVn4o@openwebui-postgres:5432/openwebui_db
    depends_on:
      - openwebui-postgres
    restart: unless-stopped

  openwebui-postgres:
    image: postgres:17
    container_name: openwebui-postgres-v0.4.8
    environment:
      - POSTGRES_DB=openwebui_db
      - POSTGRES_USER=openwebui
      - POSTGRES_PASSWORD=9PF3R6tk95yVn4o
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
```

</details>

<details>
  <summary>v0.5.0</summary>

```yaml
version: '3.8'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.5.0
    container_name: openwebui-v0.5.0
    volumes:
      - ./data/open-webui:/app/backend/data
    ports:
      - 9022:8080
    environment:
      - WEBUI_AUTH=false
      - DATABASE_URL=postgresql://openwebui:9PF3R6tk95yVn4o@openwebui-postgres:5432/openwebui_db
    depends_on:
      - openwebui-postgres
    restart: unless-stopped

  openwebui-postgres:
    image: postgres:17
    container_name: openwebui-postgres-v0.5.0
    environment:
      - POSTGRES_DB=openwebui_db
      - POSTGRES_USER=openwebui
      - POSTGRES_PASSWORD=9PF3R6tk95yVn4o
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
```

</details>
