### DISCUSSION TITLE
Function is not getting env variable for some reason

### DISCUSSION THREAD

**Discussion by gyzerok** [open-webui/open-webui#8187] [Q&A]
Hello everyone!

I am using docker and am trying to configure a [function](https://openwebui.com/f/xgawatt/DeepseekAPI/) to add deepseek to my models list. However for some reason function is not getting the value of the `DEEPSEEK_API_KEY` env variable.

I've already verified, that this variable exists inside container by execing into it and echoing. So it is there, but the Python code isn't getting it. What could be wrong? Do I miss some crucial config?

Here is my `docker-compose.yml` bit
```
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    networks:
      - caddy-net
    environment:
      - ENABLE_ADMIN_CHAT_ACCESS=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    volumes:
      - ./appdata/open-webui/data:/app/backend/data
      - /etc/localtime:/etc/localtime:ro
    restart: 'unless-stopped'
```
