### DISCUSSION TITLE
API keys only work after first login upon server restart

### DISCUSSION THREAD

**Discussion by ghmer** [open-webui/open-webui#8206] [Issues]
# Bug Report

## Installation Method

docker-compose stack with open-webui, ollama and redis

## Environment

- **Open WebUI Version:** 0.5.2
- **Ollama (if applicable):** 0.5.4

- **Operating System:** debian
- **Browser (if applicable):** not applicable

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

An API key should work regardless of a user login. When a server is restarted, the owner of an API key should not be required to login before their API key can be used.

## Actual Behavior:

Upon server/docker stack restart, I receive "HTTP 400: Bad Gateway" responses using http requests with an "Authorization: Bearer API_KEY" header until I logon to open-webui via browser.

## Description

**Bug Summary:**
After a server restart, http requests to the Ollama backend via open-webui (authenticated via API key) results in "http 400 - Bad Gateway" responses. The issue persists unless the owner of the API key logs into open-webui via browser. Then, the API key is working properly until the next server restart.

## Reproduction Details

**Steps to Reproduce:**
- Login to open-webui via browser. Retrieve your API key
- Test your API key. You should get responses from the api backend (for example, ollama)
- restart the server
- Test your API key. You will get "http 400 - Bad Gateway" responses
- Login to open-webui via browser. 
- Test your API key again. It is working properly, now.

**Comment by ghmer** [comment]
Not sure if anything is required from my side as this issue was converted to a discussion. Let me know :-)

**Comment by spammenotinoz** [comment]
I couldn't replicate this could it be your proxy? (assuming you are using one)

**Reply by ghmer** [reply]
> I couldn't replicate this could it be your proxy? (assuming you are using one)

Definitely not the proxy, I tried accessing open-webui directly, same issue. But maybe it is worth mentioning that I enabled OIDC on my stack.

**Reply by jojasadventure** [reply]
I have this too, API only works when logged in first, IP

**Comment by ikesler** [comment]
![image](https://github.com/user-attachments/assets/5d2d3205-8583-4957-8753-61637974efc3)
This value is reset after server restart. New value every time I restart the container. Volume configuration is (Ansible + Podman):

```yaml
- name: Openwebui container
  containers.podman.podman_container:
    name: openwebui
    image: ghcr.io/open-webui/open-webui:ollama
    state: quadlet
    volumes:
      - "/d/alpha/ollama:/root/.ollama"
      - "/d/alpha/openwebui:/app/backend/data"
    ports:
      - 30555:8080
    memory: 25g
```
