### DISCUSSION TITLE
Set Ollama model directory in docker compose

### DISCUSSION THREAD

**Discussion by norton-chris** [open-webui/open-webui#836] [General]
I understand the Ollama handles the model directory folder, however, I'm launching Ollama and open-webui with docker compose: ./run-compose.sh --enable-gpu --build

I see in Ollama to set a different model directory you export OLLAMA_MODEL=/path/to/models

I did that in the docker-compose.yaml and added my models path to volumes /root/.ollama.
Here's a snippet of my docker-compose.yaml:
```
services:
  ollama:
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - ollama:/root/.ollama
      - /mnt/2TB_SSD/text-gen/text-generation-webui/models:/root/.ollama/models
      ....(rest of docker-compose)
```
but I still don't see the models in the webui or when I run `ollama list` in the ollama docker container.

What am I doing wrong?
