### DISCUSSION TITLE
How do i pre-load tools and functions before first startup?

### DISCUSSION THREAD

**Discussion by xblaauw** [open-webui/open-webui#8955] [Q&A]
Right now i cloned the repo, made some small changes here and there to my liking (mostly integrations with my pre-existing setup through an environment variable file). I then rebuild it, either with or without dropping the docker volume. This workflow is awesome, its very quick to make big changes and i can easily revert back (just use git and rebuild).

I find myself often wanting to deploy my setup using my specific environment file and small adjustments so my family members can have their own instance instead of relying on mine, while still benefiting from the stuff i added into openwebui (I don't want to guarantee continuity for them, they can do that themselves haha).

However, I can't figure out what to do to include my prompts, tools and functions etc as part of the repo and have them persist across rebuilds while dropping the volume. Both tools and functions are just scripts, they don't get in the way in any way. So my question is:

> How do i pre-load tools and functions such that they are available for the admin immediately after launch?

I will continue to look into this, if i find a solution i will post here! Next thing I'm going to try is to write a shell script that connects to the db so i can try to figure out if they live in there somewhere.

I have searched (for about an hour) for similar discussions, but i find that the search tools are lacking, so i may have missed the relevant post, in that case, please point me in the right direction and close this issue :)

**Comment by arun-prakash-fokus** [comment]
Code available under:  [git@github.com:arun-prakash-fokus/owi.git](git@github.com:arun-prakash-fokus/owi.git)

Consider the following simple folder structure

```tree
.
├── webui
│   ├── configs
│   │   ├── config_de-DE.json
│   │   └── config_en-US.json
│   └── pipeline
│       ├── mypipe_pipe.py
│       └── template.json
├── .service.webui.env
└── docker-compose.yml
```

./webui/configs/config_en-US.json
```json
{
    "version": 0,
    "ui": {
        "default_locale": "en-US",
        "prompt_suggestions": [
            {
                "title": [
                    "Help me study",
                    "vocabulary for a college entrance exam"
                ],
                "content": "Help me study vocabulary: write a sentence for me to fill in the blank, and I'll try to pick the correct option."
            },
            {
                "title": [
                    "Give me ideas",
                    "for what to do with my kids' art"
                ],
                "content": "What are 5 creative things I could do with my kids' art? I don't want to throw them away, but it's also so much clutter."
            },
            {
                "title": [
                    "Tell me a fun fact",
                    "about the Roman Empire"
                ],
                "content": "Tell me a random fun fact about the Roman Empire"
            },
            {
                "title": [
                    "Show me a code snippet",
                    "of a website's sticky header"
                ],
                "content": "Show me a code snippet of a website's sticky header in CSS and JavaScript."
            },
            {
                "title": [
                    "Explain options trading",
                    "if I'm familiar with buying and selling stocks"
                ],
                "content": "Explain options trading in simple terms if I'm familiar with buying and selling stocks."
            },
            {
                "title": [
                    "Overcome procrastination",
                    "give me tips"
                ],
                "content": "Could you start by asking me about instances when I procrastinate the most and then give me some suggestions to overcome it?"
            },
            {
                "title": [
                    "Grammar check",
                    "rewrite it for better readability "
                ],
                "content": "Check the following sentence for grammar and clarity: \"[sentence]\". Rewrite it for better readability while maintaining its original meaning."
            }
        ]
    }
}
```

./webui/pipeline/template.json
```json
{
    "id": "",
    "name": "",
    "type": "pipe",
    "content": "",
    "meta": {
        "description": "",
        "manifest": {}
    },
    "is_active": true,
    "is_global": false
}
```

./webui/pipeline/mypipe_pipe.py
```python
import os

from pydantic import BaseModel, Field


class Pipe:
    class Valves(BaseModel):
        BASE_URL: str = Field(
            default=os.getenv("MYPIPE_BASE_URL", ""), description="Base URL for accessing the MYPIPE application."
        )
        API_KEY: str = Field(
            default=os.getenv("MYPIPE_API_KEY", ""),
            description="API key for authenticating requests to the MYPIPE application.",
        )
        MODEL_ID: str = Field(
            default=os.getenv("MYPIPE_DEFAULT_MODEL_ID", ""),
            description="Default model for generating the response in the MYPIPE application.",
        )

    def __init__(self):
        self.valves = self.Valves()

    def pipe(self, body: dict):
        # Logic goes here
        print(self.valves, body)  # This will print the configuration options and the input body
        return "Hello, World!"
```

./.service.webui.env
```env
##############################################
# CHANGE IT TO REFLECT YOUR PROD ENVIRONMENT #
# DONT STORE PASSWORDS & SENSITIVE DATA HERE #
##############################################

# https://docs.openwebui.com/getting-started/env-configuration

# sets the default locale for the application
DEFAULT_LOCALE=en-US

# webui
WEBUI_NAME=OWI
WEBUI_SECRET_KEY=t0p-s3cr3t

# admin
WEBUI_ADMIN_EMAIL=admin@admin.com
WEBUI_ADMIN_USER=admin
WEBUI_ADMIN_PASS=admin

# mypipe service
MYPIPE_BASE_URL=http://mypipe:8000
MYPIPE_API_KEY=0p3n-w3bu!
MYPIPE_DEFAULT_MODEL_ID=mistral:latest

# mypipe pipeline function
PIPE_FUNC_ID=mypipe
PIPE_FUNC_NAME=MYPIPE
PIPE_FUNC_DESCRIPTION=Pipeline function of MYPIPE
PIPE_FUNC_FILE=mypipe_pipe
```

./docker-compose.yml
```yml
name: owi

services:  
  # ai web interface
  open-webui:
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:0.5.20-cuda
    ports:
      - 8080:8080
    env_file:
      - .service.webui.env
    entrypoint:
      - bash
      - -c
      - |
        echo "Copy the default locale specific config ...."
        cp -n /app/backend/open_webui/configs/config_$${DEFAULT_LOCALE}.json /app/backend/data/config.json
        echo "Starting Open WebUI server..."
        /app/backend/start.sh &

        # Wait for Open WebUI API to become available
        echo "Waiting for Open WebUI to start..." &&
        while ! curl -s -o /dev/null "http://localhost:8080/health"; do
          sleep 2;
        done &&

        echo "Open WebUI started"

        echo "Sign up default admin user ..."
        SIGNUP_RESPONSE=$(curl -s -X POST "http://localhost:8080/api/v1/auths/signup" \
          -H "Content-Type: application/json" \
          --data-raw "{\"name\":\"$${WEBUI_ADMIN_USER}\", \"email\":\"$${WEBUI_ADMIN_EMAIL}\", \"password\":\"$${WEBUI_ADMIN_PASS}\"}")

        API_KEY=$(echo "$${SIGNUP_RESPONSE}" | jq -r '.token')

        echo "Received API_KEY: $${API_KEY}"

        JSON_TEMPLATE_PATH="/app/backend/open_webui/pipeline/template.json"
        PYTHON_FILE_PATH="/app/backend/open_webui/pipeline/"$${PIPE_FUNC_FILE}.py

        # Read the Python file and escape special characters for JSON
        PYTHON_CODE=$(jq -Rs . < "$${PYTHON_FILE_PATH}")

        # Read the template and replace placeholders
        DATA_RAW=$(jq --arg id "$${PIPE_FUNC_ID}" \
                      --arg name "$${PIPE_FUNC_NAME}" \
                      --arg desc "$${PIPE_FUNC_DESCRIPTION}" \
                      --argjson content "$${PYTHON_CODE}" \
                      '.id=$$id | .name=$$name | .meta.description=$$desc | .content=$$content' \
                      "$${JSON_TEMPLATE_PATH}")

        echo "Adding Pipe function to Open WebUI"
        curl -s -X POST "http://localhost:8080/api/v1/functions/create" \
          -H "Authorization: Bearer $${API_KEY}" \
          -H "Content-Type: application/json" \
          --data-raw "$${DATA_RAW}"

        # Keep the container running
        wait
    volumes:
      - webui.data:/app/backend/data
      - ${PWD}/webui/configs:/app/backend/open_webui/configs:ro
      - ${PWD}/webui/pipeline:/app/backend/open_webui/pipeline:ro
    networks:
      - internal

volumes:
  webui.data:
    name: owi-webui-data


networks:
  internal:
    name: owi-internal
```

![sc-owi](https://github.com/user-attachments/assets/a9961a5f-5588-42c2-8fc2-49cfe84cfb49)
