### DISCUSSION TITLE
Keycloak OIDC SSO: Open WebUI not redirecting back to itself (HTTP 400 Bad Request)

### DISCUSSION THREAD

**Discussion by lindner-tj** [open-webui/open-webui#9077] [Issues]
Hello Everyone,

No matter what I try, I can't get Open WebUI to work with my Keycloak realm. It seems that Open WebUI can't redirect to itself succesfully after becoming authenticated in Keycloak.

## Installation Method

docker compose

## Environment

- **Open WebUI Version:** [v0.5.7](https://github.com/open-webui/open-webui/releases/tag/v0.5.7)

- **Operating System:** Ubuntu 22.04.5 LTS
- **Browser (if applicable):** Chrome, Firefox

## Expected Behavior:

being logged-in successfully and redirected back to Open WebUI

## Actual Behavior:

Browser says: `{"detail":"The email or password provided is incorrect. Please check for typos and try logging in again."}`

## Description

**Bug Summary:**
I set up a fresh Open WebUI Container with no users yet and try to connect it to my Keycloak realm.

## Logs and Screenshots

**Browser Console Logs:**
excerpt from Chrome-HAR file:
```json
"request": {
          "method": "GET",
          "url": "https://openwebui.tds.mycompany.lan/oauth/oidc/callback?state=DEIzrWScM6ZtZF5sysMFcwjpsXMOTr&session_state=feda3b18-6a0d-4c6f-b0aa-c1917efd1a89&iss=https%3A%2F%2Fsso.mycompany.com%2Frealms%2FMycompany&code=ee5c1e76-c274-4a9e-9585-95c91120b405.feda3b18-6a0d-4c6f-b0aa-c1917efd1a89.85785b45-4468-424d-9136-aff8367e9d4b",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br, zstd"
            },
            {
              "name": "Accept-Language",
              "value": "en"
            },
            {
              "name": "Cache-Control",
              "value": "no-cache"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Host",
              "value": "openwebui.tds.mycompany.lan"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "Sec-Fetch-Dest",
              "value": "document"
            },
            {
              "name": "Sec-Fetch-Mode",
              "value": "navigate"
            },
            {
              "name": "Sec-Fetch-Site",
              "value": "cross-site"
            },
            {
              "name": "Sec-Fetch-User",
              "value": "?1"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
            },
            {
              "name": "sec-ch-ua",
              "value": "\"Not A(Brand\";v=\"8\", \"Chromium\";v=\"132\", \"Google Chrome\";v=\"132\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "sec-ch-ua-platform",
              "value": "\"Windows\""
            }
          ],
          "queryString": [
            {
              "name": "state",
              "value": "DEIzrWScM6ZtZF5sysMFcwjpsXMOTr"
            },
            {
              "name": "session_state",
              "value": "feda3b18-6a0d-4c6f-b0aa-c1917efd1a89"
            },
            {
              "name": "iss",
              "value": "https%3A%2F%2Fsso.mycompany.com%2Frealms%2FMycompany"
            },
            {
              "name": "code",
              "value": "ee5c1e76-c274-4a9e-9585-95c91120b405.feda3b18-6a0d-4c6f-b0aa-c1917efd1a89.85785b45-4468-424d-9136-aff8367e9d4b"
            }
          ],
          "cookies": [],
          "headersSize": 1732,
          "bodySize": 0
        },
        "response": {
          "status": 400,
          "statusText": "Bad Request",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Content-Length",
              "value": "106"
            },
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "Date",
              "value": "Wed, 29 Jan 2025 15:20:37 GMT"
            },
            {
              "name": "Server",
              "value": "uvicorn"
            },
            {
              "name": "X-Process-Time",
              "value": "0"
            }
          ],
          "cookies": [],
          "content": {
            "size": 106,
            "mimeType": "application/json",
            "compression": 0,
            "text": "{\"detail\":\"The email or password provided is incorrect. Please check for typos and try logging in again.\"}"
          },
          "redirectURL": "",
          "headersSize": 263,
          "bodySize": 106,
          "_transferSize": 369,
          "_error": null,
          "_fetchedViaServiceWorker": false
        },
```

**Docker Container Logs:**
when I click on the "Sign in with SSO" Button, I get in the docker logs:
```
INFO:     10.1.16.232:0 - "GET /oauth/oidc/login HTTP/1.1" 302 Found
WARNI [open_webui.utils.oauth] OAuth callback error: invalid_client: Invalid client or Invalid client credentials
INFO:     10.1.16.232:0 - "GET /oauth/oidc/callback?state=923lUhS3jpoFyJq2Y3WSxWvkCNcm7t&session_state=feda3b18-6a0d-4c6f-b0aa-c1917efd1a89&iss=https%3A%2F%2Fsso.lindner-group.com%2Frealms%2FLindner&code=45e49a1d-c06e-4631-bf5d-d32ff9334847.feda3b18-6a0d-4c6f-b0aa-c1917efd1a89.85785b45-4468-424d-9136-aff8367e9d4b HTTP/1.1" 400 Bad Request
INFO:     connection closed
```

## Additional Information
.env file with SSO config (I checked in the container and the values are indeed getting set as environment variables inside the container):
```
# SSO Config
OAUTH_CLIENT_ID='https://openwebui.tds.mycompany.lan'
OAUTH_CLIENT_SECRET='mysecret'
OPENID_PROVIDER_URL='https://sso.mycompany.com/realms/Mycompany/.well-known/openid-configuration'
OAUTH_PROVIDER_NAME='Mycompany.SSO'
OAUTH_SCOPES='openid email profile'
ENABLE_OAUTH_SIGNUP=true
OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
```
I didn't specify `OPENID_REDIRECT_URI` as the browser was already sending the request to the correct URL (i.e. https://openwebui.tds.mycompany.lan/oauth/oidc/callback)

Open WebUI appears to succesfully authenticate itself against Keycloak, however the redirect back to Open WebUI fails with HTTP Code 400 (Bad Request)

**Comment by lindner-tj** [comment]
Thanks to my colleague @FloB0 I figured it out. Open WebUI uses [Starlette](https://docs.authlib.org/en/latest/client/starlette.html) for its OAuth implementation. And Starlette can't handle special characters like / or : in the client ID.

**Reply by rajeshhazari** [reply]
Hi @lindner-tj ,
Thanks for update, I'm in process of setting up key clock sso also.
What is the final solution , can we integrate  keycloak sso, if so please share me what changes required, do we need to escape special chars? 
Thanks

**Reply by aur3l14no** [reply]
@rajeshhazari I think you could just avoid using those chars. Something like "yet-another-open-webui" would work.

**Comment by windshetty** [comment]
This worked for me.

The folder structure is 

```
├── docker-compose.yml
└── keycloak
    ├── realm-export.json


```

The docker-compose.yml file

```
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    command: start-dev --import-realm
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
    - ./keycloak:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      LOG_LEVEL: debug
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/localhost/8080'
      start_interval: 10s
    networks:
      - webnet

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    ports:
      - "3000:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      OAUTH_CLIENT_ID: aiassistant
      OAUTH_CLIENT_SECRET: aiassistantsecret
      OAUTH_PROVIDER_NAME: aiassistant
      OPENID_PROVIDER_URL: http://keycloak:8080/realms/aiassistant/.well-known/openid-configuration
      OAUTH_SCOPES: openid email profile
      ENABLE_OAUTH_SIGNUP: true
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      OPENID_REDIRECT_URI: http://localhost:3000/oauth/oidc/callback
      LOG_LEVEL: debug
    networks:
      - webnet

networks:
  webnet:

```

The following 'realm-export.json' file contains  realm, client and user creation data. This file is read by the keycloak container. This will help create realm, client and user automatically. 
```
{
  "realm": "aiassistant",
  "enabled": true,
  "clients": [
    {
      "clientId": "aiassistant",
      "secret": "aiassistantsecret",
      "enabled": true,
      "protocol": "openid-connect",
      "publicClient": true,
      "rootUrl": "http://localhost:3000",
      "redirectUris": [
        "http://localhost:3000/oauth/oidc/callback"
      ],
      "standardFlowEnabled": true
    }
  ],
  "users": [
    {
      "username": "testuser",
      "enabled": true,
      "firstName": "Test",
      "lastName": "User",
      "email": "testuser@email.com",
      "emailVerified": true,
      "credentials": [
        {
          "type": "password",
          "value": "testpass",
          "temporary": false
        }
      ]
    }
  ]
}
```

Once both containers are running, I was able to point the browser to http://localhost:3000/. This gets redirected to keycloak and you can login with 'testuser/testpass' (this is the only user I have created to keep it simple). Once logged in successfully, you will see the Open WebUI page.
