### DISCUSSION TITLE
Support RamaLama as default instead of Ollama

### DISCUSSION THREAD

**Discussion by LorenDB** [open-webui/open-webui#9178] [Ideas]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Ollama has been accused of very sketchy behavior and has refused to implement features that would be very user-beneficial (e.g. Vulkan support). The commentary in the below links will tell you more:

https://news.ycombinator.com/item?id=42886680
https://github.com/ggerganov/llama.cpp/pull/11016#issuecomment-2599740463

**Describe the solution you'd like**
Open WebUI should consider moving away from Ollama as a default and switch to something like [RamaLama](https://github.com/containers/ramalama) instead to prevent user-hostile software.

**Describe alternatives you've considered**
Really any software other than Ollama would be fine as an alternative.

**Comment by meminens** [comment]
I couldn't get ramalama work with open-webui. Can someone please help? Below is my docker compose for open-webui. And I installed ramalama via `uv`. When is start ramalama with `ramalama serve`, I get port conflict error.

```
services:
    open-webui:
        network_mode: host
        volumes:
            - open-webui:/app/backend/data
        environment:
            - OLLAMA_BASE_URL=http://127.0.0.1:8080
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:main
volumes:
    open-webui:
        external: true
        name: open-webui
```
