### DISCUSSION TITLE
Additional Python Package with Code Interpreter

### DISCUSSION THREAD

**Discussion by alesha-pro** [open-webui/open-webui#9390] [Ideas]
# Feature Request

Code Interpeter's new built-in functionality is delightful! I would like to be able to put additional python packages in that environment - is there any way to do that? I would like this feature very much!

**Comment by vividfog** [comment]
+1

I tried to pre-install packages in the same venv where OpenWebUI is running (in uv .venv) but that didn't work, so the packages aren't inherited by the sandbox venv it seems. If they would be inherited, that'd already be a big win — and increased sandbox escalation risk if not running with trusted users only.

So, perhaps the Admin could configure and point OpenWebUI to a dedicated Code Interpreter venv Python interpreter for sandboxes to use? Or is that possible today? That way at least there would be a global less-spartan venv to for all Code Interpreters to run on in the system.

```
code_interpreter:
  enabled: true
  sandbox_venv: "/path/to/ci_venv/bin/python"
  installed_packages:
    - numpy
    - pandas
    - matplotlib
    - scipy
    - requests
```

Or maybe this is a per-group conf. 

It's great if it works with [uv](https://docs.astral.sh/uv/) .venvs too, but a regular Python pip is fine if trouble.
