### DISCUSSION TITLE
Query about Referencing Models/Personalities from Open WebUI in LiteLLM Proxy Configuration

### DISCUSSION THREAD

**Discussion by flefevre** [open-webui/open-webui#9518] [Q&A]
Hi team,

I hope this message finds you well. I am currently working on configuring the proxy for LiteLLM and I have a question regarding the integration of models or personalities from Open WebUI.

Is it possible to make references to models or personalities accessible via an endpoint in the configuration of the LiteLLM proxy? If so, could you please provide some guidance or examples on how to achieve this?

Any help or clarification would be greatly appreciated.

Thank you in advance for your assistance!

Best regards,

François

```
- model_name: codegemma
    litellm_params:
      model: ollama/codegemma:latest
      api_base: http://ollama:11434
      stream: True
```
