### DISCUSSION TITLE
When use openwebui,I always meet error:SyntaxError: Unexpected token 'd', "data: {"id"... is not valid JSON

### DISCUSSION THREAD

**Discussion by twythebest** [open-webui/open-webui#9987] [General]
SyntaxError: Unexpected token 'd', "data: {"id"... is not valid JSON?
but ollama serve run well, how to solve?

**Comment by AaronBaird1** [comment]
same here.   Very simple setup:  official docker container with openai key.  no local models.
No nginx server, local connection only.

**Reply by NWilliamsSCU** [reply]
Until OpenAI starts limiting free searches...

**Comment by Mujadded** [comment]
I am facing this exact problem, too. The funny thing is when I run in mac this works without problem but in ubuntu it gives the error. I know this shouldn't be the problem when using docker but it is the problem. I have no idea why.
```
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "80:8080"
    environment:
      - OPENAI_API_KEY=open_api_key
    volumes:
      - open-webui:/app/backend/data
    restart: always

volumes:
  open-webui:
  ```

**Reply by Mujadded** [reply]
After 🕒 **spending hours** troubleshooting, I **found a solution**! Setting `ENABLE_WEBSOCKET_SUPPORT` to `false` 🛠️ **fixes the WebSocket issue**. It actually disables the WebSocket, I believe 🤔, but **it works seamlessly** ✅ nonetheless. 🎉

```yaml
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "80:8080"
    environment:
      - OPENAI_API_KEY=open_key
      - ENABLE_WEBSOCKET_SUPPORT=false
    volumes:
      - open-webui:/app/backend/data
    restart: always
    network_mode: bridge
    expose:
      - "8080"
volumes:
  open-webui:
```

Hope this helps anyone facing the same issue! 😊
