### ISSUE TITLE
bug: Including file_metadata in /files/ route not working

### ISSUE THREAD

**Issue by almajo** [open-webui/open-webui#10342]
# Bug Report

## Environment

- **Open WebUI Version:** 0.5.14

**Confirmation:**

- [ X  ] I have read and followed all the instructions provided in the README.md.
- [ X ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Since one of the last versions, 'file_metadata' was added to the /files POST route when uploading files. When adding a dictionary, I want this to be added within `meta` of the file.

## Actual Behavior:

When calling the API (even through the Swagger UI), the API returns a 422 Error: Uprocessable Entity

## Description

**Bug Summary:**

Either through python requests or CURL, I can't get it working.

Through the UI I send the following request:

```bash
curl -X 'POST' \
  'http://localhost:3000/api/v1/files/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@a357116e-9ddd-4f72-86dd-2d855be398a3 Kopie.pdf;type=application/pdf' \
  -F 'file_metadata="{
    "test": "test1, test2, test3",
}"'
```

and receive this response:

```json
{
  "detail": [
    {
      "type": "dict_type",
      "loc": [
        "body",
        "file_metadata"
      ],
      "msg": "Input should be a valid dictionary",
      "input": "\"{\r\n    \"test\": \"test1, test2, test3\",\r\n}\""
    }
  ]
}
```

with headers 
```yaml
 access-control-allow-credentials: true 
 access-control-allow-origin: http://localhost:3000 
 content-length: 170 
 content-type: application/json 
 date: Wed,19 Feb 2025 09:00:41 GMT 
 server: uvicorn 
 vary: Origin 
 x-process-time: 0 
```

I also played around sending the request through request where I tried adding the metadata to json or data argument. Same results.

Sending no metadata works to upload the file

## Reproduction Details

**Steps to Reproduce:**

Super simple. Open Swagger UI on <webui>/docs and send a POST request to /api/v1/files/ with an uploaded file and include metadata.
