### ISSUE TITLE
feat: How can the user persist sign in after the container was upgraded?

### ISSUE THREAD

**Issue by Anduin2017** [open-webui/open-webui#11436]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.

### Problem Description

Hi. I am using Docker Swarm to deploy Open WebUI.

```yaml
version: '3.9'

services:
  open-web:
    image: hub.aiursoft.cn/ghcr.io/open-webui/open-webui:main
    environment:
      # Temp endpoint. Migrate to container ASAP.
      - OLLAMA_BASE_URL=http://ollama_server:11434/
      - ENABLE_OPENAI_API=False
      - WEBUI_AUTH=True
      - ENABLE_SIGNUP=True
      - DEFAULT_USER_ROLE=user
      - SHOW_ADMIN_DETAILS=False
      - ENABLE_COMMUNITY_SHARING=False
      - ENABLE_MESSAGE_RATING=False
      - ENABLE_TAGS_GENERATION=False
      - ENABLE_EVALUATION_ARENA_MODELS=False
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      - proxy_app
      - ollama_net
    deploy:
      replicas: 1
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'

networks:
  proxy_app:
    external: true
  ollama_net:
    external: true

volumes:
  open-webui-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /swarm-vol/open-webui-data

secrets:
  bing-search-key:
    external: true

```

However, after the image was upgraded, all signed in users are signed out automatically. And they need to sign in again manually.

How can we persist their sign in status? Like persisting the JWT key on the server?

### Desired Solution you'd like

Maybe persist a file which is the JWT key on the server?
