### ISSUE TITLE
feat: Open WebUI & Ollama docker-compose.yml

### ISSUE THREAD

**Issue by extreme4all** [open-webui/open-webui#11943]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.

### Problem Description

Hey i was searching for a docker compose but couldn't find it so i thought i'd share my own docker compose, they may be useful somewhere in the documentation.

```yml
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```

### Desired Solution you'd like

docker-compose.yml file in documentation
