### ISSUE TITLE
bug: Firefox - When using ALT+TAB in maximized openwebui it shows file dialog

### ISSUE THREAD

**Issue by peteh** [open-webui/open-webui#1315]
# Bug Report

## Description

**Bug Summary:**
When tabbing out of a maximized firefox window with openwebui in Kubuntu (wayland) and tabbing back, the add files dialog is shown instead of going back to the prompt. 

**Steps to Reproduce:**
* open the webui in Firefox (I have port 3001 mapped instead of 3000)
* Firefox must be maximzed
* Open a new prompt, select any mode
* ALT + TAB out of Firefox
* ALT + TAB back to Firefox
* The page now shows the "Add files dialog"

**Expected Behavior:**
Normal Alt tab behavior and back to prompt, not open files dialog

**Actual Behavior:**
Opens the add file dialog (see screenshots)

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- Kubuntu 23.10 KDE with Wayland
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
Firefox 124
## Reproduction Details

**Confirmation:**

- [* ] I have read and followed all the instructions provided in the README.md.
- [ *] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots
Before ALT+TAB
![image](https://github.com/open-webui/open-webui/assets/918728/08815c2a-2c4e-4b07-9765-ece05dcb291a)

After ALT+TAB:
![image](https://github.com/open-webui/open-webui/assets/918728/b80c8581-564f-4adb-9905-5ecf1741ed32)

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method
* Using docker compose 
```
services:
  ollama:
    image: ollama/ollama:rocm
    #image: ollama/ollama:latest
    container_name: ollama-rocm
    ports:
      - "11434:11434"
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    volumes:
      - ./data:/root/.ollama
    environment:
      - 'HSA_OVERRIDE_GFX_VERSION=11.0.1'

  open-webui:
    build:
      context: .
      args:
        OLLAMA_API_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3001:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://homeassistant.home:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

```
## Additional Information
Chrome works without this issue
