### ISSUE TITLE
Issue 400: '_type' while downloading the file for knowledge.

### ISSUE THREAD

**Issue by RubanVladyslav** [open-webui/open-webui#13875]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

latest in docker-hub)

### Operating System

Windows 10

### Browser (if applicable)

Chrome

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have listed steps to reproduce the bug in detail.

### Expected Behavior

Successfully load file into knowledge

### Actual Behavior

After trying to load a .txt file, I caught the following error in the browser:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
index.ts:204 Objectdetail: "400: '_type'"[[Prototype]]: Object
```

All systems are deployed to the server with nginx configuration

### Steps to Reproduce

1) Use my Docker setup
2) Use OpenAI
3) Load the .txt file into knowledge

### Logs & Screenshots

![Image](https://github.com/user-attachments/assets/85caa3ac-98fc-44d7-a114-0265d5bcccc7)

![Image](https://github.com/user-attachments/assets/3e944332-2c07-4255-aec8-45ef12f4b42f)

### Additional Information

```
services:
    chroma_db:
      image: ghcr.io/chroma-core/chroma:latest
      command: ["run", "--host", "${CHROMA_HTTP_HOST}", "--port", "${CHROMA_HTTP_PORT}", "--path", "/app/chroma_db/data"]
      volumes:
        - chroma_data:/app/chroma_db/data
      networks:
        - demo

    open-webui:
      image: ghcr.io/open-webui/open-webui
      depends_on:
        - chroma_db
      ports:
        - "${WEBUI_PORT}:${WEBUI_PORT}"
      environment:
        - "HF_HUB_OFFLINE=1"
        - "CHROMA_HTTP_HOST=${CHROMA_HTTP_HOST}"
        - "CHROMA_HTTP_PORT=${CHROMA_HTTP_PORT}"
        - "PORT=${WEBUI_PORT}"
      volumes:
        - webui_data:/app/backend/data
      env_file: .env
      restart: unless-stopped
      networks:
        - demo

networks:
  demo:
    driver: bridge

volumes:
  chroma_data:
  webui_data:
```
