### ISSUE TITLE
Cannot upload document

### ISSUE THREAD

**Issue by cellulosa** [open-webui/open-webui#1418]
# Bug Report

## Description

**Bug Summary:**
When I click on the + icon and select a document, I receive error 400.
RAG works if I place the very same document on the `/docs` folder and run a `Scan`.

**Steps to Reproduce:**
I am running the service with `docker-compose`:

```yml
services:

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ${DOCKER_CONFIG_DIR}/open-webui:/app/backend/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
```

**Expected Behavior:**
The documents gets uploaded and stored in the `/docs` folder.

**Actual Behavior:**
When I try to upload a document, I see this error being thrown in the backend (see below).

## Environment

- **Operating System:** MacOS Sonoma 14.4.1 on Apple M2
- **Browser (if applicable):** Firefox 124.0.1 (64-bit)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
```shell
open-webui          | INFO:apps.rag.main:file.content_type: application/pdf
open-webui          | ERROR:apps.rag.main:400: Something went wrong :/
open-webui          | Traceback (most recent call last):
open-webui          |   File "/app/backend/apps/rag/main.py", line 464, in store_doc
open-webui          |     raise HTTPException(
open-webui          | fastapi.exceptions.HTTPException: 400: Something went wrong :/
open-webui          | 
open-webui          | INFO:     10.5.0.2:0 - "POST /rag/api/v1/doc HTTP/1.1" 400 Bad Request
```

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

Docker-compose
