### ISSUE TITLE
bug: redirects to localhost:3000 on 0.6.11 azure ad sso

### ISSUE THREAD

**Issue by fanuelsen** [open-webui/open-webui#14380]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.

### Problem Description

After updating the docker container to the latest version login with azure got broken for me, i get this error in the logs on the client: "localhost:3000/auth#token=eyJhbGciOiJIUzl1NilsInR5cCI6IkpXVCJ9.eyJpZCI6ImFmZD
RhMzg5LTg0YjAtNDgxNi1iY2MyLWM4Y2RIZGNIOTEyNiJ9.7qaZ7WXrfd2LG8GbMcZLrxy
ZRUxZ1PwQ7tqwaynOtFQ" because Safari can't connect to the server "localhost".

the open-webui 
2025-05-27 06:53:27.959 | INFO     | uvicorn.protocols.http.httptools_impl:send:476 - - "GET /oauth/microsoft/callback?code=redacted &session_state=redacted HTTP/1.1" 307 - {}

### Desired Solution you'd like

to logon as i used to do in version 0.6.10

### Additional Context

This happend after pulling the new image. 0.6.11

**Comment by tsueri** [comment]
I use it with zitadel and got the same problem.

**Comment by Breidenbach-Murach** [comment]
We have the same issue after the update to 0.6.11. 
A simple rollback of the container using the "0.6.10" tag did not fix it, as the login prompt seemingly gets stuck after the redirect.

**Comment by tsueri** [comment]
I have read the changelog. My problem persists even with the environment variable.

This is my compose.yml:
```
services:
    open-webui:
        ports:
            - 3000:8080
        environment:
            - OLLAMA_BASE_URL=redacted
            - OLLAMA_AUTH_TRUSTED_HEADER=X-Remote-User
            - OAUTH_CLIENT_ID=redacted
            - OAUTH_CLIENT_SECRET=redacted
            - OPENID_PROVIDER_URL=redacted
            - OAUTH_PROVIDER_NAME=SSO
            - OAUTH_SCOPES=openid email profile
            - ENABLE_OAUTH_ROLE_MANAGEMENT=true
            - ENABLE_OAUTH_SIGNUP=true
            - OAUTH_ROLES_CLAIM=user.roles
            - OAUTH_ALLOWED_ROLES=user
            - OAUTH_ADMIN_ROLES=admin
            - WEBUI_URL=https://redacted
        volumes:
            - ./data:/app/backend/data
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:main
    watchtower:
        image: containrrr/watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 open-webui
        depends_on:
          - open-webui
```
