### ISSUE TITLE
issue: UnboundLocalError on Database Initialization

### ISSUE THREAD

**Issue by manooll** [open-webui/open-webui#14942]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

0.6.4

### Operating System

Ubuntu 24.04.2 LTS

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

Open WebUI should connect to the PostgreSQL database and start normally.

### Actual Behavior

When running Open WebUI (tested with v0.6.4 and latest) in Docker Compose with a valid PostgreSQL backend, the container fails to start due to a Python exception:

```
UnboundLocalError: cannot access local variable 'db' where it is not associated with a value
```

This occurs in `/app/backend/open_webui/internal/db.py` during the `handle_peewee_migration(DATABASE_URL)` call.

**Note:** The application starts and works as expected when using the default (SQLite) backend (i.e., when `DATABASE_URL` is not set). The error only occurs when attempting to use PostgreSQL by setting `DATABASE_URL`.

---

## Environment

- **Open WebUI image:** ghcr.io/open-webui/open-webui:v0.6.4 (also fails with latest)
- **Docker Compose version:** 1.29.2
- **PostgreSQL image:** postgres:15-alpine
- **Host OS:** Ubuntu 24.04.2 LTS (EC2)
- **Relevant docker-compose.yml excerpt:**

```yaml
open-webui:
  image: ghcr.io/open-webui/open-webui:v0.6.4
  container_name: ai-ui-open-webui
  environment:
    - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    # ... other env vars ...
  depends_on:
    postgres:
      condition: service_healthy
    redis:
      condition: service_healthy
    litellm:
      condition: service_healthy
  # ... rest omitted ...
```

### Steps to Reproduce

1. Deploy Open WebUI with the above docker-compose config and a healthy Postgres backend.
2. Start the container: `docker-compose up -d open-webui`
3. Observe the container fails with the above Python error.

### Logs & Screenshots

```
File "/app/backend/open_webui/internal/db.py", line 75, in <module>
    handle_peewee_migration(DATABASE_URL)
File "/app/backend/open_webui/internal/db.py", line 68, in handle_peewee_migration
    if db and not db.is_closed():
UnboundLocalError: cannot access local variable 'db' where it is not associated with a value
```

### Additional Information

- The same error occurs specifically with PostgreSQL backend.
- All other services (Postgres, Redis, LiteLLM) are healthy.
- Removing/recreating containers and volumes does not resolve the issue.
- This appears to be a regression in recent Open WebUI images.
- **Again, the application works as expected with the default SQLite backend, but fails with PostgreSQL.**
