### ISSUE TITLE
issue: Authentication issue with openwebui and Keycloak

### ISSUE THREAD

**Issue by infra823** [open-webui/open-webui#15082]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.
- [x] I am using the latest version of Open WebUI.

### Installation Method

Docker

### Open WebUI Version

0.6.13

### Ollama Version (if applicable)

0.9.0

### Operating System

Ubuntu 22.04

### Confirmation

- [x] I have read and followed all instructions in `README.md`.
- [x] I am using the latest version of **both** Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have **provided every relevant configuration, setting, and environment variable used in my setup.**
- [x] I have clearly **listed every relevant configuration, custom setting, environment variable, and command-line option that influences my setup** (such as Docker Compose overrides, .env values, browser settings, authentication configurations, etc).
- [x] I have documented **step-by-step reproduction instructions that are precise, sequential, and leave nothing to interpretation**. My steps:
- Start with the initial platform/version/OS and dependencies used,
- Specify exact install/launch/configure commands,
- List URLs visited, user input (incl. example values/emails/passwords if needed),
- Describe all options and toggles enabled or changed,
- Include any files or environmental changes,
- Identify the expected and actual result at each stage,
- Ensure any reasonably skilled user can follow and hit the same issue.

### Expected Behavior

- When connecting with Keycloak Oauth provider, users and admins are properly recognized in Open-webui

### Actual Behavior

- Login works for all users, but admins are not recognized

### Steps to Reproduce

1. Install Keycloak from the image quay.io/keycloak/keycloak:26.2.5
2. Create a client for open-webui in keycloak
3. Create a regular user account in Keycloak
4. Create a user account in Keycloak with the admin scope
5. Install Open-webui from the 0.6.13 image "main-cuda" with only keycloak as auth provider (see below env configuration)
6. Access Open-webui website and select the Keycloak auth provider
7. Try to log into Open-webui with keycloak as a user -> works OK
8. Try to log into Open-webui with keycloak as an admin -> auth works but user is not admin

### Logs & Screenshots

```yaml
# openwebui container env excerpt
      GLOBAL_LOG_LEVEL: INFO
      OPENWEBUI_SKIP_USER_APPROUVAL: true
      OPENWEBUI_DEFAULT_USER_STATE: "active"
      OPENWEBUI_ALLOW_NEW_USERS: true
      BYPASS_MODEL_ACCESS_CONTROL: True
      WEBUI_URL: https://internal/
      PORT: 3000
      ENABLE_OAUTH_SIGNUP: true
      ENABLE_SIGNUP: false
      ENABLE_LOGIN_FORM: false
      ENABLE_OAUTH_GROUP_MANAGEMENT: true
      ENABLE_OAUTH_ROLE_MANAGEMENT: true
      ENABLE_PERSISTENT_CONFIG: false
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      OAUTH_CLIENT_ID: ***
      OAUTH_CLIENT_SECRET: ****
      OPENID_PROVIDER_URL: https://internal/keycloak/realms/internal/.well-known/openid-configuration
      OAUTH_PROVIDER_NAME: openwebui
      OPENID_REDIRECT_URI: https://internal/oauth/oidc/callback
      OAUTH_SCOPES: openid email profile
      OAUTH_ALLOWED_ROLES: user,admin
      OAUTH_ADMIN_ROLES: admin
      OAUTH_ROLES_CLAIM: realm_access.roles
      DEFAULT_USER_ROLE: user
      CORS_ALLOW_ORIGIN: null
```
