### ISSUE TITLE
feat: Qdrant Support for RAG

### ISSUE THREAD

**Issue by tdiprima** [open-webui/open-webui#15197]
### Check Existing Issues

- [x] I have searched the existing issues and discussions.

### Problem Description

Hey all — they said Qdrant isn't *officially* supported per [#6386](https://github.com/open-webui/open-webui/discussions/6386), **but the [docs](https://docs.openwebui.com/getting-started/env-configuration/#vector-database) suggest otherwise.** Qdrant is listed as a supported vector database.

The related Qdrant-specific variables like `QDRANT_API_KEY`, `QDRANT_URI`, and `ENABLE_QDRANT_MULTITENANCY_MODE` also show Open WebUI has some infrastructure for it, but the following error suggests it's not fully functional.

I've got Qdrant running fine outside of WebUI, but trying to add documents throws:
`400: 'NoneType' object has no attribute 'collection_exists'`.

ChromaDB just isn't cutting it for RAG — **it's way too slow once you scale past a few hundred docs.** Qdrant could seriously improve performance here. Would love to see better support and clearer error handling around this. Happy to help test. 🙏

### Desired Solution you'd like

Qdrant should play nicely with Open WebUI.

### Alternatives Considered

A faster vector database should be the default database.

### Additional Context

Using ChromaDB for RAG? You ask a question, then wait a full *minute and a half* just to ***start*** getting a response. Then it trickles out... one. word. at. a. time. with long pauses in between — while your fan spins up like a jet engine about to take off. 🛫

**Comment by tdiprima** [comment]
Just saw #10008 mentioning Open WebUI creating a collection per document, which could hurt performance at scale (e.g., ~1400 files crashing). Enabling `ENABLE_QDRANT_MULTITENANCY_MODE` might help consolidate collections. Could this be addressed alongside better Qdrant support? Happy to test any fixes!

> "OpenWebUI creates a qdrant collection both for your file (for every single one separately)..."  [Comment 12215374](https://github.com/open-webui/open-webui/discussions/10008#discussioncomment-12215374).

**Comment by tjbck** [comment]
PR Welcome, Qdrant is 100% managed by external contributions.

**Comment by guenhter** [comment]
@tdiprima what issue do you have? We also use qdrant with `ENABLE_QDRANT_MULTITENANCY_MODE` turned on, and it works fine for us.

**Comment by tdiprima** [comment]
@guenhter Thanks for jumping in! Here's the main issue I'm hitting:

Qdrant is running fine outside Open WebUI, **but** when I try to add documents through the UI, I get this error:

> 400: 'NoneType' object has no attribute 'collection_exists'

From what I can tell, it's choking on a call that assumes a collection manager exists but returns `None`. This happens even with `ENABLE_QDRANT_MULTITENANCY_MODE=true`.

Would it help if I shared my `docker-compose.yml`? I'm happy to post it if that’ll shed more light.

Also, I saw in #10008 that Open WebUI might be making a new Qdrant collection *per file*, which would wreck performance at scale (I've got >1400 files). Are you doing anything custom to consolidate collections or batch uploads?

Appreciate any insight — I really want to get Qdrant working as a drop-in upgrade from ChromaDB, especially for larger datasets.

**Comment by guenhter** [comment]
We don't do anything special. This is how my compose looks like:

```yaml
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "127.0.0.1:6333:6333"

  owui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    depends_on:
      - qdrant
    ports:
      - "80:8080"
    volumes:
      - ./owui:/app/backend/data
    environment:
      - VECTOR_DB=qdrant
      - QDRANT_API_KEY=
      - QDRANT_URI=http://qdrant:6333
```

Even if `ENABLE_QDRANT_MULTITENANCY_MODE=true`, this works
