### ISSUE TITLE
Variable PORT is not included in the documentation

### ISSUE THREAD

**Issue by tristangrimaux** [open-webui/open-webui#1689]
The documentation correctly states the use of the option "--net host" when having problems to connect but fails to provide the environment variable PORT to configure the web port because when running the docker container in the same network as the host, the options to publish a port are ignored.

Also, the documentation on the environment variables fails to provide the existence of the variable PORT that I could find in the source code.

A better example line could be this

`docker run -d -p 9090:8080 --net host -e PORT=9090 -e OLLAMA_BASE_URL=http://10.10.20.1:11434 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
`

or a docker compose version like this:

```
services:
    open-webui:
        ports:
            - 9090:8080
        network_mode: host
        environment:
            - PORT=9090
            - OLLAMA_BASE_URL=http://10.10.20.1:11434
        volumes:
            - open-webui:/app/backend/data
        container_name: open-webui
        restart: always
        image: ghcr.io/open-webui/open-webui:main
volumes:
    open-webui:
        external: true
        name: open-webui

```
