### ISSUE TITLE
Image Generation Not Working

### ISSUE THREAD

**Issue by kmc7468** [open-webui/open-webui#1927]
# Bug Report

## Description

**Bug Summary:**
Maybe from v0.1.123, image generation using AUTOMATIC1111 doesn't work.

**Steps to Reproduce:**
1. Click the image generation button
2. Error

**Expected Behavior:**
Generated image should be displayed.

**Actual Behavior:**
Error

## Environment

- **Open WebUI Version:** 0.1.123
- **Ollama (if applicable):** 0.1.32

- **Operating System:** Ubuntu Server 22.04 LTS

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
`Something went wrong :/ cannot access local variable 'image_id' where it is not associated with a value`

**Docker Container Logs:**
![image](https://github.com/open-webui/open-webui/assets/18364980/0431c4a7-e377-469d-bd57-e2ffde1be21f)

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/18364980/0a78c847-ea15-4071-bf14-be7d51753094)

## Installation Method

I used the following `docker-compose.yml` file:

```
services:
  server:
    container_name: open-webui-server
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=<OMITTED>
      - DEFAULT_MODELS=llama3:8b-instrct-q8_0
      - ENABLE_MODEL_FILTER=True
      - MODEL_FILTER_LIST=codellama:13b-instruct-q6_K;dolphin-llama3:8b-v2.9-q8_0;gemma:7b-instruct-v1.1-q8_0;llama2-uncensored:7b-chat-q8_0;llama3:8b-instruct-q8_0;llava:7b-v1.6-mistral-q8_0;mistral:7b-instruct-v0.2-q8_0
      - AUTOMATIC1111_BASE_URL=<OMITTED>
      - ENABLE_IMAGE_GENERATION=True
    ports:
      - 4000:8080

volumes:
  open-webui-data:
```

## Additional Information

Previously I used v0.1.120 and it worked well. AUTOMATIC1111 version is 1.9.3. It generates images well therefore I think it is open-webui backend's bug. Thank you for your effort!
