### ISSUE TITLE
GGUF/HuggingFace import is broken on ollama v0.1.35+

### ISSUE THREAD

**Issue by Snuupy** [open-webui/open-webui#2189]
# Bug Report

## Description

**Bug Summary:**

HuggingFace model download/import from url doesn't work on ollama v0.1.35+. Also, loading previously imported models from GGUF/HF don't work either. Last working version is v0.1.34.

**Steps to Reproduce:**

Go to open-webui, insert any GGUF link from HF

**Expected Behavior:**

it should download and import the GGUF from HF without error, then allow me to select the model to load.

**Actual Behavior:**

model gets downloaded, does not get imported properly, with error:

```
ollama       | time=2024-05-11T17:10:52.261Z level=WARN source=routes.go:749 msg="bad manifest" name=registry.ollama.ai/library/Meta-Llama-3-8B-Instruct-correct-pre-tokenizer-and-EOS-token-Q8_0.gguf:latest error="open /root/.ollama/models/manifests/registry.ollama.ai/library/meta-llama-3-8b-instruct-correct-pre-tokenizer-and-eos-token-q8_0.gguf/latest: no such file or directory"
```

this error happens with all HF GGUFs on ollama v0.1.35+

## Environment

- **Open WebUI Version:** v0.1.124
- **Ollama (if applicable):** tested: 0.1.36 (not working), 0.1.35 (not working), 0.1.34 (working), 0.1.33 (working)

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Librewolf v125.0.3-1

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
  - [x] let me know if necessary and I will attach them. I do not believe it is a browser issue.
- [x] I have included the Docker container logs.

## Installation Method

docker-compose, with the following docker-compose.yml (manual edits were necessary because the script does not detect mobile chipsets, i.e. 780M, 680M, etc.)

```
services:
  open-webui:
    ports:
      - 3000:8080
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - '/ollama/api=http://ollama:11434/api'
      - local_files_only=False
    container_name: open-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:latest
    extra_hosts:
      - host.docker.internal:host-gateway
  ollama:
    container_name: ollama
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    image: ollama/ollama:0.1.36-rocm # 0.1.34 works
    environment:
      - "HSA_OVERRIDE_GFX_VERSION=11.0.0"
      - "OLLAMA_DEBUG=1"
      - "OLLAMA_MAX_VRAM=16106127360"
      - "OLLAMA_NUM_PARALLEL=2"
      - "OLLAMA_MAX_LOADED_MODELS=2"
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    security_opt:
       - "seccomp=unconfined"
    group_add:
      - video
```

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

included above

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!
