### ISSUE TITLE
bug: During pulling two models from ollama style of window is broken

### ISSUE THREAD

**Issue by luboszima** [open-webui/open-webui#2687]
# Bug Report

## Description

While downloading two models at the same time in the setting window, the text in the window started to shake. 

Video prove: https://youtu.be/0aHMVtOJNYU

**Bug Summary:**
Shaking text in setting window in tab Models

**Steps to Reproduce:**

I ran locally ollama
```
ollama serve
```

Web UI in docker container
```
services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
#    depends_on:
#      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
      - 'ENABLE_SIGNUP=False'
      - 'WEBUI_AUTH=False'
      - 'WEBUI_NAME=Lubos Playground'
      - 'DEFAULT_MODELS=llama3,'
#      - 'DOCS_DIR=/docs'
    extra_hosts:
      - host.docker.internal:host-gateway
    network_mode: host
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
```

Steps: 
1. Go to settings -> Models
<img width="791" alt="image" src="https://github.com/open-webui/open-webui/assets/11191064/c13f8c5a-06a1-4f1a-b971-d412abf3f260">
2. Pull a model from Ollama.com: Try to download llama3
3. Pull a model from Ollama.com: Try to download deepseek-coder
4. Now you can observe destroyed style and shaking like in the video.

## Environment

- **Open WebUI Version:** 0.1.125
- **Ollama (if applicable):** 0.1.39
- **Operating System:** MacOS Sonoma 14.5
- **Browser (if applicable):** Google Chrome 125.0.6422.142  (Official Build) (arm64)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

[![IMAGE ALT TEXT](http://img.youtube.com/vi/0aHMVtOJNYU/0.jpg)](http://www.youtube.com/watch?v=0aHMVtOJNYU "Video Title")
video: https://youtu.be/0aHMVtOJNYU

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!
