### ISSUE TITLE
Lack of documentation: SearXNG query URL

### ISSUE THREAD

**Issue by mdillondc** [open-webui/open-webui#2717]
I don't see how a full bug report would be warranted here. This is simply lack of documentation.

**Help structuring searxng query url**
I cannot for the life of me figure out how the `Searxng Query URL` should be structured under "Document Settings - Web Params"

**I have tried:**
Enter a search url to an instance with JSON enabled, e.g. `https://some.searxng.instance/search?q=%&format=json` and `https://some.searxng.instance/` and `https://some.searxng.instance/search&format=json`

I expect the `%` to be replaced with my actual search query. Instead, the search just searches for the actual percentage sign and comes up with e.g. `https://en.wikipedia.org/wiki/Percent_sign` as a source.

- **Open WebUI Version:** 0.2.0

**Comment by mdillondc** [comment]
I'm an idiot. Sorry.

**Comment by Morethanevil** [comment]
Additional info:

I have setup Searx-NG a long time ago with the standard "settings.yml"

For anyone who gets "403 Forbidden" like me, you need to enable JSON in the settings.yml

![Screenshot_20240602_111824](https://github.com/open-webui/open-webui/assets/110860055/edb992c1-05c5-4512-8bc2-d75752a2fda3)

**Comment by bannert1337** [comment]
@Morethanevil this should be added to the documentation! ^^

**Comment by remkolems** [comment]
Not only that:

1. Navigate to: `Workspace` -> `Documents` -> `Document Settings` -> `Web Params`
2. Toggle `Enable Web Search`
3. `Select Web Search Engine` from dropdown menu

![image](https://github.com/open-webui/open-webui/assets/45675902/8f37fa14-2d21-46e2-b929-97bd39741007)

Furthermore, I had hoped to configure it directly within the docker compose file. For now, I was unable to do so with environment variables. Any suggestions?

**Comment by Expro** [comment]
Indeed, environment variables for enabling Web Search seems to be missing.

**Comment by justinh-rahb** [comment]
> Indeed, environment variables for enabling Web Search seems to be missing.

These ones? https://docs.openwebui.com/getting-started/env-configuration#web-search

**Comment by Expro** [comment]
Even setting those results in web search being disabled and requiring in-UI intervention.

**Comment by justinh-rahb** [comment]
`ENABLE_RAG_WEB_SEARCH=True`
`RAG_WEB_SEARCH_ENGINE=searxng`

These will be added to the docs shortly.

**Comment by alkeryn** [comment]
I tried to set up but it doesn't seem to be doing anything, how should you trigger web searches ?

**Comment by Expro** [comment]
Click "+" on text field and toggle "Web Search". Documentation is lacking here.

I would love to have that toggle not hidden behind "+".

**Comment by alkeryn** [comment]
@Expro Oh, thank you hahaha

**Comment by DustyTurtleDip** [comment]
Is there a way to enable "Web Search" by default in new conversation ?

**Comment by alkeryn** [comment]
@DustyTurtleDip i don't think so but i'm not even sure you would want that as it's slower.
@Expro after some testing it'd be nice if it used the context to make the query and make one only if it determines that it is necessary.

for example if i ask what the weather is like where i live, it is unable to look up the personal information i gave in "memory" and make a search to look for that town.

still cool though.

**Comment by tjbck** [comment]
PR to our docs would be greatly appreciated 🙌 

https://github.com/open-webui/docs/blob/main/docs/tutorial/web_search.md

**Comment by samssausages** [comment]
Thank you for the info here, especially @Morethanevil adding the info to the searxng config file fixed the issue I was having!  Pretty cool that this works with no google API!

**Comment by justinh-rahb** [comment]
> PR to our docs would be greatly appreciated 🙌
> 
> https://github.com/open-webui/docs/blob/main/docs/tutorial/web_search.md

Ask and ye shall receive 👍 https://github.com/open-webui/docs/pull/94

**Comment by mdillondc** [comment]
> Click "+" on text field and toggle "Web Search". Documentation is lacking here.
> 
> I would love to have that toggle not hidden behind "+".

It took me a while to find this as well.

It might add clutter, but I feel that the search button should not be hidden. How about placing it as a greyed-out icon next to the `+` icon? The user can then click it to toggle the search on or off with just one click. It is quite cumbersome to click `+ > move mouse > click the toggle > refocus the prompt input field` and then perform the search. If you don't want to search in your next prompt, you have to repeat all the clicks to disable the search. The best solution would be a keybinding to toggle the search, or something like `#search search query here`.

Also, if one enables search and prompts `"Help me find a good carrying harness I can use if my dog gets injured on a hike"`, the AI could try to rephrase the search query in a way it deems optimal and submit that as the search prompt instead of exactly what the user wrote.

Of course, if the program or AI could be smart enough to detect when a search is needed, that would be ideal. However, this is probably optimistic right now, depending on the model in use and several other factors.

**Comment by justinh-rahb** [comment]
> Also, if one enables search and prompts `"Help me find a good carrying harness I can use if my dog gets injured on a hike"`, the AI could try to rephrase the search query in a way it deems optimal and submit that as the search prompt instead of exactly what the user wrote.

It already does so for prompts over 100 characters. It's been proposed to make this a configurable option (with `0` meaning always rewrite it).

**Comment by mdillondc** [comment]
> Web search toggle button will remain in the `+` button where the rest of the `tools` feature will also be added.

Understood. But what about a keybinding to quickly toggle?

**Comment by alkeryn** [comment]
@justinh-rahb but does it uses the whole conversation context to generate the search ?

**Comment by remkolems** [comment]
> > PR to our docs would be greatly appreciated 🙌
> > [open-webui/docs@`main`/docs/tutorial/web_search.md](https://github.com/open-webui/docs/blob/main/docs/tutorial/web_search.md?rgh-link-date=2024-06-04T18%3A32%3A53Z)
> 
> Ask and ye shall receive 👍 [open-webui/docs#94](https://github.com/open-webui/docs/pull/94)

So in summary `docker compose` file: 

```yaml
services:
  open-webui:
    environment:
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
```
or (syntax also possible, but less preferable)

```yaml
services:
  open-webui:
    environment:
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE="searxng"
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL="http://searxng:8080/search?q=<query>"
```

FWIW I'm running a separate dedicated SearXNG docker compose behind a reverse proxy for offloading SSL (hence the use of https internally). `SEARXNG_QUERY_URL` would become `SEARXNG_QUERY_URL: "https://search.domain.com/search?q=<query>"`, whereby search.domain.com is self-chosen.

A lot of activity for a closed issue ;-)

**Comment by justinh-rahb** [comment]
> while I do agree that should be the standard, as defined by searx-ng but my Open-WebUI was able to search the web with my Query URL like this: `http://<searxng.domain.tld>/`

The `search?q=<query>` part was made optional in between docs being written and the eventual merge of the feature. Think I'll leave it in the docs anyway as it feels more _proper_ to me to specify the full path.

**Comment by jars101** [comment]
Hello, anyone getting "Expecting value: line 4 column 1 (char 3)" when trying to query searxng  through openwebui? I can access and browse just fine directly searcxng on its ports via web interface. Also, settings.yml have json and html format. Any help is aprreciated it. thanks!

**Comment by janus78** [comment]
I have tried all of the proposed changes on my side but still the web search not work, I am using searxng from a docker container and on all my test I receive an  alert when I select web search and send the text, the alert indicates an error on line 1 col 1 , I have active the json response on yaml config, tested locally on searxng location and returned json but seems that the search from open webui is not returning json but html from that request and the parse fails, does anyone have the same issue?, thanks.

**Comment by remkolems** [comment]
@janus78 

1. Does SearXNG work on its own as expected?
2. Could you share your config?
3. Could you share the alert? Print screen and drop in the comment (ctrl-v on windows)
4. Does `setting.yml` of SearXNG resemble: 
```yaml
# removed all other parts
search:
# ... removed other parts for this section for readability ...

  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - json # to enable ollama/open-webui
 
# rest of file also deleted
```

**Comment by remkolems** [comment]
This is my SearXNG `docker-compose.yml` file btw:

```yaml
#
# https://github.com/searxng/searxng
# https://github.com/searxng/searxng/blob/master/searx/settings.yml
#
services:
  # Temporary busybox container to set correct permissions to unix shared socket folder
  # https://hub.docker.com/_/busybox/tags?page=1&name=latest
  tmp:
    image: busybox:latest@sha256:50aa4698fa6262977cff89181b2664b99d8a56dbca847bf62f2ef04854597cf8
    #command: sh -c "chown -R 33:33 /tmp/docker/ && chmod -R 770 /tmp/docker/"
    command: sh -c "chmod -R 777 /tmp/docker/"
    env_file:
      - .env
    volumes:
      - "${SEARXNG_HOME}/tmp/docker/"
    security_opt:
      - no-new-privileges:true
  #
  # redis
  #
  # https://hub.docker.com/_/redis/tags?page=1&name=alpine
  searxng-redis:
    image: redis:7.2.5-alpine3.19@sha256:892b41c092a599f76c30b48e9dcfb185ce8cea3560970b1c4f2745c89bb34344
    container_name: searxng-redis
    # hostname: searxng-redis
    restart: unless-stopped
    env_file:
      - .env
    # Download Redis at https://redis.io/download/ and unpack to extract redis.conf
    # Redis.conf contains the available commands
    # Removed from entrypoint
    # --unixsocket /tmp/docker/redis.sock
    # --unixsocketperm 755
    entrypoint: >
      redis-server --bind 127.0.0.1
      --appendonly no
      --save ""
      --protected-mode yes
      --maxmemory 50M
      --maxmemory-policy allkeys-lru
    networks:
      - lan
    ports:
      - 9736:6379
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - "${SEARXNG_HOME}/redis_data:/data:rw"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # Add shared volume from Temporary busybox container
    volumes_from:
      - tmp
    depends_on:
      - tmp
    # Run as a member of the www-data GID 33 group but keep redis uid as 999
    #user: "999:33"
    security_opt:
      - no-new-privileges:true
  #
  # searxng
  #
  # https://hub.docker.com/r/searxng/searxng/tags
  searxng:
    image: searxng/searxng:latest@sha256:2ceb4ddf2cb8a0227af416c3110dcefc188af3538a9c1a34937d2a30a837d942
    container_name: searxng
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - lan
    ports:
      - 8080:8080
    volumes:
      - "${SEARXNG_HOME}/searxng_data:/etc/searxng:rw"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # Add shared volume from Temporary busybox container
    volumes_from:
      - tmp
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
      - INSTANCE_NAME=SearXNG
      - SEARXNG_SECRET=${SEARXNG_SECRET_KEY}
      # https://docs.searxng.org/admin/engines/settings.html#redis
      - SEARXNG_REDIS_URL=unix:///tmp/docker/redis.sock?db=0 # Redis URL must specify one of the following schemes (redis://, rediss://, unix://)
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "1m"
    #     max-file: "1"
    depends_on:
      - tmp
      - searxng-redis
    # UID should be 977. Does not work ...
    #user: "977:33"
    security_opt:
      - no-new-privileges:true

networks:
  lan:
    ipam:
      driver: default

```
