### ISSUE TITLE
Postgres problem with the new 0.3.8

### ISSUE THREAD

**Issue by madpin** [open-webui/open-webui#3747]
# Bug Report

## Description

**Bug Summary:**
The new version: 0.3.8 the website shows the error: "Internal Server Error"
And absolutely no logs in the terminal.
I'm using the docker-compose:

In my case:
```
  owui:
    image: ghcr.io/open-webui/open-webui:0.3.7
    container_name: owui
    user: 1002:1002
    networks:
      - caddy
      - infra
      - llm_infra
    environment:
      - PORT=8081
      - GLOBAL_LOG_LEVEL=DEBUG
    env_file:
      - owui.env
    volumes:
      - ${HOME}/configs/open-webui:/app/backend/data
    labels:
      caddy: owui.xxxxx.com
      caddy.reverse_proxy: "{{upstreams 8081}}"
    restart: unless-stopped
```

**Steps to Reproduce:**
With the postgres in another docker, I wasn't able to make it work.
If I turn off postgres, it was working fine with the sqlite.

**Expected Behavior:**
No errors :)

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Open WebUI Version:** 0.3.8
- **Ollama (if applicable):** NA

- **Operating System:** Ubuntu, but actually Docker
- **Browser (if applicable):** NA

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!
