### ISSUE TITLE
recommend adding a docker-compose.yaml file 

### ISSUE THREAD

**Issue by Hisma** [open-webui/open-webui#3777]
many of us run multiple docker containers and like to organize in a docker-compose file.  Here is the docker command I run to run open-webui - 
``docker run -d -p 3000:8080 --gpus all --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --network=host --restart always ghcr.io/open-webui/open-webui:cuda``

here it is in docker-compose format - 

Here's the Docker Compose equivalent of the provided Docker run command:

```yaml
version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
    restart: always

volumes:
  open-webui:
```

note - I need to use the option `network_mode: host` for some reason.  Others may not need this so it can be commented out by default.  

I think others will find this useful and it can be added as an additional file for those who prefer to orchestrate docker containers using `docker compose`.
