### ISSUE TITLE
0.3.8 break trusted header auth

### ISSUE THREAD

**Issue by chain710** [open-webui/open-webui#3793]
# Bug Report

## Description

**Bug Summary:**

0.3.8 break trusted header auth

I have nginx with Authelia handling user authentication, where nginx passes the validated user email as Remote-Email to access the Open webui. Everything was working fine until I upgraded Open webui to version 0.3.8 today.

Reverting back to version 0.3.7 temporarily resolved the issue.

**Steps to Reproduce:**

upgrade to 0.3.8

env 
```
    environment:
      - ENABLE_SIGNUP=False
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Remote-Email
```

**Expected Behavior:**

Should auto login

**Actual Behavior:**

Login failed with error: "The email or password provided is incorrect. Please check for typos and try logging in again."

## Environment

- **Open WebUI Version: 0.3.8
- **Ollama (if applicable): not relevant

- **Operating System: windows 11
- **Browser (if applicable): Chrome 126

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
```
{
    "status": true,
    "name": "Open WebUI",
    "version": "0.3.8",
    "default_locale": "",
    "default_models": "gpt-3.5-turbo",
    "default_prompt_suggestions": [
        {
            "title": [
                "Help me study",
                "vocabulary for a college entrance exam"
            ],
            "content": "Help me study vocabulary: write a sentence for me to fill in the blank, and I'll try to pick the correct option."
        },
        {
            "title": [
                "Give me ideas",
                "for what to do with my kids' art"
            ],
            "content": "What are 5 creative things I could do with my kids' art? I don't want to throw them away, but it's also so much clutter."
        },
        {
            "title": [
                "Tell me a fun fact",
                "about the Roman Empire"
            ],
            "content": "Tell me a random fun fact about the Roman Empire"
        },
        {
            "title": [
                "Show me a code snippet",
                "of a website's sticky header"
            ],
            "content": "Show me a code snippet of a website's sticky header in CSS and JavaScript."
        },
        {
            "title": [
                "Explain options trading",
                "if I'm familiar with buying and selling stocks"
            ],
            "content": "Explain options trading in simple terms if I'm familiar with buying and selling stocks."
        },
        {
            "title": [
                "Overcome procrastination",
                "give me tips"
            ],
            "content": "Could you start by asking me about instances when I procrastinate the most and then give me some suggestions to overcome it?"
        }
    ],
    "features": {
        "auth": true,
        "auth_trusted_header": true,
        "enable_signup": false,
        "enable_web_search": true,
        "enable_image_generation": true,
        "enable_community_sharing": false,
        "enable_admin_export": true
    },
    "audio": {
        "tts": {
            "engine": "openai",
            "voice": "alloy"
        },
        "stt": {
            "engine": "openai"
        }
    },
    "oauth": {
        "providers": {}
    }
}

index.ts:116  POST https://xxxx/api/v1/auths/signin 400 (Bad Request)
{
    "detail": "The email or password provided is incorrect. Please check for typos and try logging in again."
}

```

**Docker Container Logs:**
No relevant log

**Screenshots (if applicable):**

![image](https://github.com/open-webui/open-webui/assets/486539/18f6bfad-482a-4bf8-bd76-ea0c68f78da0)

## Installation Method

Docker compose

```
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.3.7
    container_name: open-webui
    ports:
      - 8080:8080
    environment:
      - OLLAMA_BASE_URL=http://xxx
      - OPENAI_API_BASE_URL=https://xxx
      - OPENAI_API_KEY=xxx
      - ENABLE_MODEL_FILTER=True
      - MODEL_FILTER_LIST="xxx"
      - ENABLE_SIGNUP=False
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=Remote-Email
    volumes:
      - ${DATA_ROOT}/open-webui/data:/app/backend/data
    restart: unless-stopped
```
