### ISSUE TITLE
bug: [object Object] error when sending subsequent messages to the chat.

### ISSUE THREAD

**Issue by fracergu** [open-webui/open-webui#4158]
# Bug Report

## Description

**Bug Summary:**
When using Open WebUI with an OpenAI API key, sending a second message in the chat occasionally results in no response. Refreshing the browser shows an error with the content [object Object]. Sometimes, it regenerates another response or duplicates the chat.

**Steps to Reproduce:**
1. Launch Open WebUI with an OpenAI API key.
2. Send a message in the chat.
3. Wait for the response.
4. Send a second message.
5. Observe the response, or lack thereof.
6. Refresh the browser to see if an error occurs.

**Expected Behavior:**
The application should respond to the second message without any issues and should not throw errors or duplicate chat entries.

**Actual Behavior:**
Sometimes the application does not respond after sending the second message. A page refresh yields an error showing [object Object]. Other times, it generates another response or duplicates the chat.

## Environment

- **Open WebUI Version:** 0.3.10
- **Ollama (if applicable):** Not using ollama

- **Operating System:** Server is running Debian 12, Clients Windows 11 and Arch 
- **Browser (if applicable):** Tested in Chrome 127.0.6533.73 and Firefox 128.0.3

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
I have recorded the issue on this [jam](https://jam.dev/c/3eaea634-9ebc-4cf5-af94-dce1b191e406), console logs and network requests can be checked here.

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]
Did not see anything relevant on the logs far away than the 500s that can be checked on the jam. Anyways here they are on [pastebin](https://pastebin.com/6Vud3hwD) (my public ip obfuscated and will be destroyed in 6 months)

**Screenshots (if applicable):**
![image](https://github.com/user-attachments/assets/9766f690-38c1-4242-a5c4-3014308fac0a)

## Installation Method

I have installed the app with the following docker-compose file:
```yml
services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    environment:
      - OPENAI_API_KEY=my-api-key
    volumes:
      - open-webui:/app/backend/data
    networks:
      - proxy-network

volumes:
  open-webui:

networks:
  proxy-network:
    external: true
```

## Additional Information

The issue can be reproduced consistently but does not occur every time. I've attempted testing in both Chrome and Firefox, including clean versions without extensions. I also have tested seveal models from OpenAI (4o, 4o-mini and 3.5-turbo) and happens on all of them.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!
