### ISSUE TITLE
Large memory footprint

### ISSUE THREAD

**Issue by saffroy** [open-webui/open-webui#4188]
# Bug Report

## Description

**Bug Summary:**

The open-webui process takes over 600MB after a fresh restart.

**Steps to Reproduce:**

I installed ollama and open-webui with docker, using the following docker-compose file:

```
version: '3.8'

services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: always
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ollama:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HCC_AMDGPU_TARGET=gfx1030

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "127.0.0.1:8090:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

volumes:
  ollama:
  open-webui:
```

Right now I have 1 user, 3 models and 2 chats recorded in open-webui.

**Expected Behavior:**

Use less memory, pretty please?

**Actual Behavior:**

It uses about 650MB of memory:

```
$ top -b -n1 |grep -E 'pt_main|RES'
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 735653 root      20   0 2623204 651824 159724 S   0.0   4.0   0:08.89 pt_main+

$ docker inspect -f '{{.State.Pid}}' open-webui 
735653

$ ps -fp 735653
UID          PID    PPID  C STIME TTY          TIME CMD
root      735653  735631  1 16:07 ?        00:00:08 /usr/local/bin/python3 /usr/local/bin/uvicorn main:app --host 0.0.0.0 --port 8080 --forwarded-allow-ips *

$ docker image inspect ghcr.io/open-webui/open-webui:main |jq '.[0].RepoDigests[0]' 
"ghcr.io/open-webui/open-webui@sha256:4d89fa0ea85a86e5f1c25dcdac3c810e433ebaf1f77d6a4cb667d07489ad3e7c"

```

This seems to be the docker image: https://github.com/open-webui/open-webui/pkgs/container/open-webui/245045804?tag=main

## Environment

- **Open WebUI Version:** 0.3.10
- **Ollama (if applicable):** 0.3.0

- **Operating System:** Docker on Debian 12
- **Browser (if applicable):** Firefox 128

## Reproduction Details

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

`docker-compose up -d` with the file above.

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!
