### ISSUE TITLE
v0.3.11 fails to start via Docker

### ISSUE THREAD

**Issue by PixelSolve** [open-webui/open-webui#4424]
# Bug Report

## Description

**Bug Summary:**

v0.3.10 works without issues with following docker compose, while the latest 0.3.11 version crashes the container:

```
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:git-c74e7df #0.3.10 commit
    container_name: open-webui
    volumes:
      - /home/{user}/Docker/open-webui:/app/backend/data
    ports:
      - 4000:4000
    environment:
      - 'OLLAMA_BASE_URL=http://192.168.0.10:11434'
      - 'PORT=4000'
```
When I change the image to :latest which should be 0.3.11, the container fails to start and is stopped after about 5 seconds.

## Environment

- **Operating System:** [raspberryOS]

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Docker Container Logs:**
Unfortunately logs are not showing any information at all, they are just blank.

## Installation Method

Using Portainer stack with this docker compose to start the container

## Additional Information

I am not really sure if I am doing anything wrong, but it is quite difficult for me to debug what is actually happening because the container just crashes. When I switch back to the 0.3.10 commit, everything works again.

I also tried to clean up the local folder entirely to have fresh start in case some files did not like being there with the new version, and the result was the same.

I hope that we will find a way to figure out what is happening, thank you!
