### ISSUE TITLE
Incorrect docker compose file specified in documentation -> development

### ISSUE THREAD

**Issue by rushilchugh01** [open-webui/open-webui#4527]
The docker compose file mentioned at https://docs.openwebui.com/tutorial-development/ throws the following errors errors - 
- services.backend.environment.[0]: unexpected type map[string]interface {} -> Caused due to "ENV: dev" inside the environment section 
- service "ollama" refers to undefined volume ollama: invalid compose project -> missing "ollama:{}" under the volumes section
- Due to missing value of WEBUI_AUTH, the exception ERROR_MESSAGES.ENV_VAR_NOT_FOUND is raised

The following docker compose file corrects the both of them. Unable to find the source of the same to raise a PR

```
name: open-webui-dev

services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: no
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  frontend:
    build:
      context: .
      target: build
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "3000:5173"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json

  backend:
    build:
      context: .
      target: base
    command: ["bash", "dev.sh"]
    env_file: ".env"
    environment:
     - ENV=dev
     - WEBUI_AUTH=False
    volumes:
      - data:/app/backend/data
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8080:8080"
    restart: no
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - backend/data
        - action: rebuild
          path: backend/requirements.txt

volumes:
  data: {}
  ollama: {}
```
