### ISSUE TITLE
feat: package as executable (desktop app)

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#470]
Ideally we would want something like Ollama

Maybe we could use https://pyinstaller.org/en/stable/

**Comment by justinh-rahb** [comment]
More options for deployment are always a great idea. Packaging on macOS can bit a bit of a chore, you'll need a $99/yr developer account to create signed/notarized binaries. Anything else is pretty easy using pyinstaller.

**Comment by oliverbob** [comment]
> More options for deployment are always a great idea. Packaging on macOS can bit a bit of a chore, you'll need a $99/yr developer account to create signed/notarized binaries. Not sure if you need to pay for signing Windows binaries or not, but it's at least easier to bypass for the user if you don't.

While it is seems impractical to do it with Mac OS, it isn't the case on Windows and Linux, Android, etc. But I believe there is a way to package on multiplatform using flutter.

Thought that would perhaps mean creating a new sibling for flutter project. It allows you to create apps for desktop, and according to the docs, including iOS. Tried it in the past but didn't have mac. It works on all platforms though. The snap store also works as executable. Tried it in some apple devices to work.

**Comment by justinh-rahb** [comment]
On the packaging front, I am actively looking into Flatpak:

```yaml
app-id: org.ollama-webui.Ollama-WebUI
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: start-webui.sh
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --share=network
  - --filesystem=home
  - --device=dri
  - --env=ENV=prod
  - --env=SCARF_NO_ANALYTICS=true
  - --env=DO_NOT_TRACK=true
modules:
  - name: nodejs
    buildsystem: simple
    build-commands:
      - npm install
      - npm run build
      - mkdir -p /app/frontend
      - cp -r build/* /app/frontend/
    sources:
      - type: git
        url: https://github.com/ollama-webui/ollama-webui
        tag: main  # Specify the correct branch or tag here
      - type: archive
        url: https://chroma-onnx-models.s3.amazonaws.com/all-MiniLM-L6-v2/onnx.tar.gz
        dest: /app/data/onnx_models
  - name: python-backend
    buildsystem: simple
    build-commands:
      - pip3 install --no-cache-dir torch torchvision torchaudio -f https://download.pytorch.org/whl/cpu
      - pip3 install --no-cache-dir -r backend/requirements.txt
      - install -D backend/start.sh /app/bin/start-webui.sh
      - cp -r backend/* /app/backend/
      - cp -a /app/data/onnx_models /root/.cache/chroma/onnx_models
    sources:
      - type: git
        url: https://github.com/ollama-webui/ollama-webui
        tag: main  # Specify the correct branch or tag here
    post-install:
      - mkdir -p /app/bin
      - echo -e '#!/bin/sh\nexec /app/backend/start.sh' > /app/bin/start-webui.sh
      - chmod +x /app/bin/start-webui.sh
```

```yaml
name: Build and Release Flatpak

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

jobs:
  flatpak-build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update -y
          sudo apt-get install -y flatpak flatpak-builder

      - name: Add Flathub repository
        run: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak application
        run: flatpak-builder --force-clean build-dir org.ollama.WebUI.yaml

      - name: Create bundle
        run: flatpak build-bundle build-dir ollama-webui.flatpak org.ollama.WebUI

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: |
            ## Release ${{ github.ref_name }} of Ollama WebUI
            
            ### 🚀 New Features
            - List new features here
            - Improvements or bug fixes
      
            ### 📦 Installation Instructions
            To install Ollama WebUI on your system, follow these steps:
            1. Ensure Flatpak is installed on your system.
            2. Download `ollama-webui.flatpak`.
            3. Install the application using `flatpak install ollama-webui.flatpak`.
      
          tag_name: ${{ github.ref_name }}
          files: |
            ollama-webui.flatpak
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true # Adjust these as preferred
          prerelease: true # Adjust these as preferred
```

I'll wait til after the rename to start the PR.
