### ISSUE TITLE
feat: OAuth/OIDC 

### ISSUE THREAD

**Issue by K-J-VV** [open-webui/open-webui#483]
**Is your feature request related to a problem? Please describe.**
Add feature to enable account creation via OAuth/OIDC

**Describe the solution you'd like**
Integrating ollama-webui with auth providers such as Authentik, Keycloak, etc

**Describe alternatives you've considered**
N/A

**Additional context**
Being able to create a local account as an admin upon initialization should remain, but afterwards the admin account should be able to add the relevant information to change the default login page to redirect to a self-hosted OAuth/OIDC provider

**Comment by mafrasiabi** [comment]
It would be very good to have integration with AzureAD too.

**Comment by josh** [comment]
Ever since the new user accounts were rolled out, I've been wanting some kind of way to delegate auth as well.

In my specific case, my ollama-webui is behind a [Tailscale](https://tailscale.com) VPN. They have a pretty lightweight set of [trusted identity headers](https://tailscale.com/kb/1312/serve#identity-headers) when proxied to. It seems like a few other SSO providers like [Authelia can be configured to pass along trusted headers](https://caddyserver.com/docs/caddyfile/directives/forward_auth#examples).

From the ollama-webui side, you'd configure some envvar like `OLLAMA_AUTH_TRUSTED_HEADER=X-Remote-User` to enable this delegated auth mode. The Python backend would look for this header and automatically log in or create an account for the user given in the header value.

I wondering if this approach would cover your auth use cases as well? If so, I might take a stab at a PR implementation.

**Comment by explorigin** [comment]
Just a heads up. I'm working on integrating https://fastapi-users.github.io/fastapi-users/latest/ into ollama-webui. That will give us OAUTH2 for these clients: https://frankie567.github.io/httpx-oauth/oauth2/#provided-clients. Give me a few weeks.

**Comment by elvis-cai** [comment]
thanks @explorigin 🙇 it will be a killer feature in the open llm UI market. 
I am keen to have this feature for demo in the coming weeks, if you don't mind, Could I know if there's any estimation for it available?

**Comment by explorigin** [comment]
Sorry, no estimate. I started on it but work/life got crazy. If you need it for work then work on it. I've started with fastapi-users library but that has some considerations:
- It uses different REST-API endpoints that are difficult to customize so changing some of these will require a bit of front-end work as well.
- It uses a slightly different DB schema that will need reconciling
- Open-WebUI uses Peewee. FastAPI-users has adapters for other ORMs but not Peewee. I haven't decided if I'm going to roll a convert to SQLAlchemy in this or write a Peewee adapter.

And that's all before getting to the Oauth configuration that needs to be exposed in a smart manner.  So it's not a simple feature.

**Comment by aitzubi** [comment]
I will be interested on testing this when it is available. It would be great to add an option to automatically verify users based on their domain.

Keep the good job guys!

**Comment by m00nwtchr** [comment]
+ for auth via Forwarded Headers, for many selfhosted setups something like OIDC/OAuth is pretty overkill.

**Comment by explorigin** [comment]
Yep, I announced and then ghosted. Sorry. Going through a job change. Don't count on me for this.

**Comment by tjbck** [comment]
@cheahjs I believe a lot of people would find this tutorial useful, if you could make a PR here: https://github.com/open-webui/docs, we'd greatly appreciate it! Thanks for all the effort to make Open WebUI even better thus far!

**Comment by Michelklingler** [comment]
I agree super well done documentation!
Thanks a lot!

**Comment by AsteroidOrangeJuice** [comment]
@cellulosa I can confirm this works with Authelia with the Remote-Email header too! Thanks @cheahjs !!

**Comment by sammcj** [comment]
Anyone managed to get this working with Traefik + Authentik?

**Comment by cellulosa** [comment]
> @cellulosa I can confirm this works with Authelia with the Remote-Email header too! Thanks @cheahjs !!

could you share your config? Thanks!

**Comment by eingemaischt** [comment]
This sound absolutely fantastic! Is it possible to transmit the users role (admin, user etc) as trusted header, too?

**Comment by justinh-rahb** [comment]
> This sound absolutely fantastic! Is it possible to transmit the users role (admin, user etc) as trusted header, too?

I'd probably like to have the author of the PR @cheahjs weigh in on that, but my assumption right now is that they get the default role as normal (pending), though this can be changed to user, or admin. Otherwise changing it must be done manually by admins.

**Comment by aitzubi** [comment]
Anybody knows how to implement this using Keycloak?

**Comment by Michelklingler** [comment]
On my Side Woking well with Oauth2-proxy.
Only issue is that I can't log out for some reason.

Below is the working config to add to your docker compose:

```
### SERVICE : Oauth2-proxy - for SSO authentification with Google ###
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    hostname: oauth2-proxy
    command: --custom-sign-in-logo https://YourLogo.png
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_UPSTREAMS: http://hostIp:8080/
      OAUTH2_PROXY_CLIENT_ID: xxxx.apps.googleusercontent.com ### Exemple with google auth
      OAUTH2_PROXY_CLIENT_SECRET: xxxx
      OAUTH2_PROXY_EMAIL_DOMAINS: YourDomain
      OAUTH2_PROXY_REDIRECT_URL: https://YourDomaine/oauth2/callback
      OAUTH2_PROXY_COOKIE_SECRET: xxxx 
      OAUTH2_PROXY_COOKIE_SECURE: "false"
    restart: unless-stopped
    ports:
      - 80:4180/tcp
```
      
     **-> This is only the config on your host side.**
     Make sure that all endpoints listed in this page are reachable in your domain from your Authenticator System (ex:google):
     https://oauth2-proxy.github.io/oauth2-proxy/features/endpoints

**Comment by hkng** [comment]
I also don't know how to sign out with oauth2-proxy

**Comment by sammcj** [comment]
FYI Authentik auth seems to now be broken with the release of v0.1.124.

Tried with both the same config as I had for v0.1.123 (auth enabled), and with a fresh deployment with empty DB etc... and auth disabled.

I suspect it has something to do with this: https://github.com/open-webui/open-webui/issues/929#issuecomment-2101623934

**Comment by tjbck** [comment]
@sammcj Just pushed a fix for trusted header support, let me know if the issue persists!

**Comment by sammcj** [comment]
@tjbck thanks it looks like that fixed webui_auth:true + authentik.

FYI the behaviour is now:

- webui_auth: true + authentik (w/ header) = works ✅ 
- webui_auth: true (no authentik) = works ✅
- webui_auth: false + authentik (w/ header) = You do not have permission to access this resource. Please contact your administrator for assistance. (I suspect this is intended behaviour and as such a ✅)

Note however -

- webui_auth: false + authentik (no header) + rm -rf the db = You do not have permission to access this resource. Please contact your administrator for assistance. 🤔 
- webui_auth: false (no authentik) + rm -rf the db = You do not have permission to access this resource. Please contact your administrator for assistance. 🤔

**Comment by NathanAdhitya** [comment]
As mentioned by hkng, I think a post-logout redirect is needed.
Currently, with oauth2-proxy, the sign out button does not work.

**Comment by Macmee** [comment]
Hi! I was wondering if oauth2-proxy is still working (or probably im just setting it up wrong!)

when I visit mydomain.com/oauth2/auth I can see these headers:

```
Gap-Auth: my@email.com
X-Auth-Request-Email: my@email.com
```

and ive tried setting both of these in docker-compose like:

```
    environment:
      - 'WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-Auth-Request-Email'
```

So I _think_ my headers are getting set, but when I visit openwebui I see:

> You do not have permission to access this resource. Please contact your administrator for assistance.

**Comment by LopezRoman** [comment]
Is there a way to redirect the user after a successful authentication using `WEBUI_AUTH_TRUSTED_EMAIL_HEADER`?

For example, I have my Open WebUI embedded in an html block of a Moodle instance (seperate server) which utilizes a PHP script to call `http://localhost:3001/api/v1/auths/signin` with the appropriate post, headers, and json data however I am not redirected. I do see the user created and I am returned the new user data (username, email, token, etc.), just no redirect. I am not using tailescale nor cloudlfar, just the [generic configurationl](https://docs.openwebui.com/tutorial/sso/#generic-configurationl)

**Comment by leiguangyan** [comment]
@LopezRoman  Hello, have you deployed keycloak yourself? Can I refer to the docker-compose you deployed?

**Comment by keesfluitman** [comment]
im confused. The Documentation says a lot about ENV variables for OAuth. For instance:
ENABLE_OAUTH_SIGNUP
OAUTH_CLIENT_SECRET
etc.
Yet when I add my Authentik OAuth settings in there. Nothing happens. And considering the lack of topics about this, Im confused as to if it actually even exists?
Why does it say it here?
https://docs.openwebui.com/getting-started/env-configuration/#oauth

**Comment by ProjectMoon** [comment]
I'm trying to set this up with Authelia. It redirects to Authelia fine, but the redirect URL for OpenWebUI itself is always `http://` instead of `https://`. I have session cookie security set to secure, which makes the oauth client `https_only`. Why would it attempt to callback to an HTTP URL?

**Comment by christiangierschner** [comment]
Hi,
I successfully set up OAUTH with Keycloak. Is there a way to disable the native open-webui login and get redirected straight to Keycloak. So users don't get confused or don't use the button below the login fields?

**Comment by Louden7** [comment]
@christiangierschner check out #4068 as it might satisfy your request.

**Comment by christiangierschner** [comment]
Nice! Thank you so much...i will try it
I would love an automatic forward to OAuth when opening webui url if 
```
ENABLE_OAUTH_SIGNUP: true
ENABLE_LOGIN_FORM: false
```

**Comment by keesfluitman** [comment]
OAUTH i get a middleware error. Using Authentik. Everything should be right but nothing works.
Trusted header works partly, it logs in, but then doesn't use the received token to further request.
```
open-webui  | INFO:     2001:1711:fa46:3bc0:9d5c:11cd:b1ab:758:0 - "GET /api/v1/configs/banners HTTP/1.1" 403 Forbidden
open-webui  | INFO:     2001:1711:fa46:3bc0:9d5c:11cd:b1ab:758:0 - "GET /api/models HTTP/1.1" 403 Forbidden
open-webui  | INFO:     2001:1711:fa46:3bc0:9d5c:11cd:b1ab:758:0 - "GET /api/v1/documents/ HTTP/1.1" 403 Forbidden
open-webui  | INFO:     2001:1711:fa46:3bc0:9d5c:11cd:b1ab:758:0 - "GET /api/v1/tools/ HTTP/1.1" 403 Forbidden
open-webui  | INFO:     2001:1711:fa46:3bc0:9d5c:11cd:b1ab:758:0 - "GET /api/v1/chats/tags/all HTTP/1.1" 403 Forbidden
open-webui  | INFO:     2001:1711:fa46:3bc0:9d5c:11cd:b1ab:758:0 - "GET /api/v1/prompts/ HTTP/1.1" 403 Forbidden
``` 

```
# OAuth credentials
OAUTH_CLIENT_ID=ID
OAUTH_CLIENT_SECRET=SECRET

# OpenID provider URL
OPENID_PROVIDER_URL=https://authentik.domain.com/application/o/oidc-openwebui/.well-known/openid-configuration

# OAuth provider name
OAUTH_PROVIDER_NAME=Authentik

# OAuth scopes
OAUTH_SCOPES=email profile

ENABLE_OAUTH_SIGNUP=true
OAUTH_MERGE_ACCOUNTS_BY_EMAIL=false
```

Can anyone help me? Im at a loss here. I read about how easy it is, etc. But it's just refusing to work.

**Comment by christiangierschner** [comment]
i didnt do any magic it worked right out of the box...
we have a docker host with traefik + local acme for https certificate

```
services:
  ollama:
    image: ghcr.io/open-webui/open-webui:v0.3.11
    volumes:
      - ollama-webui:/app/backend/data
    environment:
      OLLAMA_BASE_URL: http://ollama-api:11434
      ENABLE_OAUTH_SIGNUP: true
      ENABLE_LOGIN_FORM: false
      ENABLE_SIGNUP: false
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      OAUTH_USERNAME_CLAIM: name
      OAUTH_CLIENT_ID: ollama
      OAUTH_CLIENT_SECRET:
      OPENID_PROVIDER_URL: https://$KEYCLOAKURL/auth/realms/$REALMNAME/.well-known/openid-configuration
      OAUTH_PROVIDER_NAME: Keycloak
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - backend
      - frontend

    labels:
      - traefik.enable=true
      - traefik.http.routers.ollama.rule=Host(`$HOST_NAME`)
      - traefik.http.routers.ollama.tls.certresolver=internal-acme
      - traefik.http.routers.ollama.service=ollama
      - traefik.http.routers.ollama.entrypoints=https
      - traefik.http.services.ollama.loadbalancer.server.port=8080
```
