### ISSUE TITLE
feat: Add CSS classes to elements for custom themes

### ISSUE THREAD

**Issue by SethBurkart123** [open-webui/open-webui#521]
### **Is your feature request related to a problem? Please describe.**
The current implementation of themes requires complex css selectors that will break as soon as the base styles are modified making them extremely hard to maintain. eg. the current rose-pine theme uses selectors such as:
```css
.rose-pine
	.text-white.bg-gray-100.dark\:text-gray-800.dark\:bg-gray-600.disabled.transition.rounded-lg.p-1.mr-0\.5.w-7.h-7.self-center {
	background-color: #6e6a86;
	transition: background-color 0.2s ease-out linear;
}
```
In order to change simple properties. If styling got changed in the base, these selectors would instantly be invalidated and break the theme.

### **Describe the solution you'd like**
I propose that to all important elements that should be possible to select with css there should either be accessibility attributes, id's or classes added so that it's a whole lot easier to create and maintain alternative themes.

---

I'm open to create a fix for this myself with a pull request if people are interested.
