### ISSUE TITLE
Mounting Documents in Docker no longer shows up in settings > Admin Settings > Documents

### ISSUE THREAD

**Issue by LucasZapico** [open-webui/open-webui#6236]
# Bug Report

**Important: Before submitting a bug report, please check whether a similar issue or feature request has already been posted in the Issues or Discussions section. It's likely we're already tracking it. In case of uncertainty, initiate a discussion post first. This helps us all to efficiently focus on improving the project.**

**Let's collaborate respectfully. If you bring negativity, please understand our capacity to engage may be limited. If you're open to learning and communicating constructively, we're more than happy to assist you. Remember, Open WebUI is a volunteer-driven project maintained by a single maintainer, supported by our amazing contributors who also manage full-time jobs. We respect your time; please respect ours. If you have an issue, We highly encourage you to submit a pull request or to fork the project. We actively work to prevent contributor burnout to preserve the quality and continuity of Open WebUI.**

## Installation Method

```yml 
services:
  open-webui:
 
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "5353:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
    env_file: .env.openwebui
    volumes:
      - open-webui:/app/backend/data
      - ${DIR_PATH}:/app/backend/data/docs
    extra_hosts:  
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  open-webui:

```

## Environment

- **Open WebUI Version:** v0.3.32
-  **Ollama (if applicable):**  v0.3.13 

- **Operating System:** Ubuntu 24.04.1 LTS x86_64 
- 
- **Browser (if applicable):** Chromium Version 129.0.6668.100 (Official Build) snap (64-bit)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [ x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When I used an earlier version I was able to mount a directory in my docker compose(docker image) and then create a model with "awareness" of all the documents in the directory. When I queried the agent it would use the knowledge in the directory to return a response along with references to the documents. 

I would like to leverage this behavior again. 

## Actual Behavior:

Mounted directories do not appear in the app; I  have explored the following locations. 

`settings > Admin Settings > Documents`
`workspace > knowledge` 
`workspace > create a model > select knowledge` 

## Reproduction Details

`docker compose up`

Replace <path/to/doc/dir> with path to desired document dir. 

```yml 
services:
  open-webui:
        image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "5353:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
    env_file: .env.openwebui
    volumes:
      - open-webui:/app/backend/data
      - <path/to/doc/dir>:/app/backend/data/docs
    extra_hosts:  
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  open-webui:

```

## Logs and Screenshots

[openwebui-container-log-10-16-2024.json.log](https://github.com/user-attachments/files/17400588/openwebui-container-log-10-16-2024.json.log)

## Additional Information

I went into the docker container `docker exec -it open-webui /bin/sh` to `/app/backend/data/docs` and my documents are there.
