### ISSUE TITLE
Geolocation issues

### ISSUE THREAD

**Issue by isingasimplesong** [open-webui/open-webui#6578]
# Geolocation issues

Open-webui suddenly began to ask for geolocation before sending anything to the models (local ollama models and API models alike), and fail

## Expected Behavior:

- should not require geolocation
- should work whether geolocation allowed or not 

## Actual Behavior:

- fail in both case (except on brave, where it works when geolocation is allowed)

## steps to reproduce

- when i deny the geolocation, i just get an error : `Unknown error acquiring position` and `user denied geolocation`, and then i can't use open-webui

- In Firefox, when allowing the access to my geolocation, the UI get unresponsive and i can't interact with it anymore 

- In chromium, when allowing the access to my geolocation, i get `Failed to query location from network service. Check the DevTools console for more information.`. In the console i get the following errors : 

```
Network location provider at 'https://www.googleapis.com/' : Returned error code 429.
```

```
index.ts:386 Error getting user location: 
GeolocationPositionError {code: 2, message: 'Failed to query location from network service. Check the DevTools console for more information.'}
code
: 
2
message
: 
"Failed to query location from network service. Check the DevTools console for more information."
[[Prototype]]
: 
GeolocationPositionError
(anonymous)	@	index.ts:386
Promise.catch		
re	@	index.ts:385
V	@	index.ts:259
bt	@	Chat.svelte:1518
await in bt		
(anonymous)	@	Chat.svelte:1020
await in (anonymous)		
pt	@	Chat.svelte:962
await in pt		
me	@	Chat.svelte:896
await in me		
hl	@	Chat.svelte:2320
await in hl		
(anonymous)	@	lifecycle.js:105
(anonymous)	@	lifecycle.js:104
X	@	Placeholder.svelte:212
(anonymous)	@	lifecycle.js:105
(anonymous)	@	lifecycle.js:104
Nt	@	MessageInput.svelte:545
(anonymous)	@	lifecycle.js:105
(anonymous)	@	lifecycle.js:104
Enter	@	RichTextInput.svelte:321
(anonymous)	@	index.js:99
(anonymous)	@	index.js:3132
someProp	@	index.js:5490
ce.keydown	@	index.js:3132
t.dom.addEventListener.t.input.eventHandlers.<computed>	@	index.js:3052
``` 

- It weirdly seem to work fine (with geolocation on) in Brave (when disabling any "brave shield")

---

## Installation Method

i run open-webui in docker, with docker-compose : 

```
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 3000:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./open-webui:/app/backend/data
    environment:
      - OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}
      - OPENAI_API_KEYS=${OPENAI_API_KEYS}
    restart: unless-stopped
```

## Environment

- **Open WebUI Version:** v0.3.35

- **Operating System:** ubuntu 22.04.5
- **Browser (if applicable):** Firefox 131.0.3, Chromium 130.0.6723.69, Brave v1.71.118

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs (nothing relevant there)
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.
