### ISSUE TITLE
MODEL_FILTER_LIST not working as expected

### ISSUE THREAD

**Issue by FuzzyStatic** [open-webui/open-webui#6781]
# Bug Report

## Installation Method

Through `docker compose`:

```yaml
  open-webui: 
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:latest
    environment:
      - OLLAMA_BASE_URLS=http://ollama:11434
      - DEFAULT_USER_ROLE=user
      - ENABLE_MODEL_FILTER=True 
      - MODEL_FILTER_LIST="model-0:latest;model-1:latest;model-2:latest"
    ports:
      - "8081:8080"
```

## Environment

macOS Sonoma 14.6.1

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I expected all 3 models to be in the users available models list.

## Actual Behavior:

I only see `model-1` in the list. 

## Description

**Bug Summary:**

The list seems to ignore any models that do not begin with and end with a semicolon `;`. If I add semicolons to the front and back then I see all three models in the list; `MODEL_FILTER_LIST=";model-0:latest;model-1:latest;model-2:latest;"`

## Reproduction Details

**Steps to Reproduce:**

Create different models and add them `MODEL_FILTER_LIST` along with `ENABLE_MODEL_FILTER=True`. Log in as a basic user and notice that any models that are not surrounded with a semicolon `;` are not in the user's available models list at the top left.
