### ISSUE TITLE
WEBUI_NAME environment name is not setting the WebUI name

### ISSUE THREAD

**Issue by nitulkukadia** [open-webui/open-webui#8293]
I have bring up the open web ui with the environment variable WEBUI_NAME.

https://docs.openwebui.com/getting-started/advanced-topics/env-configuration#webui_name

But is not displaying the same  in the UI.

Have seen the code here, but seems it is not being used,
https://github.com/open-webui/open-webui/blob/main/backend/open_webui/config.py
Below is the compose file:

## docker-compose.yaml. Replace necessary values before using
version: '3.8'
services:
  open-webui:
    image: zpt-customized-open-webui:git-ffeae78
    environment:
      - 'WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-Forwarded-Email'
      - OLLAMA_BASE_URL=http://0.0.0.0:11434
      - WEBUI_NAME=Custom Name
      - DEFAULT_USER_ROLE=admin
      - ENABLE_MODEL_FILTER=True
      - MODEL_FILTER_LIST=llama3:8b-instruct-q4_0; codellama:7b-instruct
    restart: always
    ports:
      - 8080:8080

**Comment by tkg61** [comment]
If you have spaces in the name, make sure the value is wrapped in quotes. e.g. WEBUI_NAME='Custom Name'

**Comment by nitulkukadia** [comment]
With the quotes, it is not working

**Comment by deseven** [comment]
Try `key : value` format:
```yml
version: '3.8'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:git-ffeae78
    environment:
      WEBUI_AUTH_TRUSTED_EMAIL_HEADER: "X-Forwarded-Email"
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
      WEBUI_NAME: "Custom Name"
      DEFAULT_USER_ROLE: "admin"
      ENABLE_MODEL_FILTER: "True"
      MODEL_FILTER_LIST: "llama3:8b-instruct-q4_0,codellama:7b-instruct"
    restart: always
    ports:
      - 8080:8080
```
