### ISSUE TITLE
WebSearch with local searx not working :

### ISSUE THREAD

**Issue by gamersalpha** [open-webui/open-webui#8842]
Hello ,

so this my configuration evrything is uptodate to 23/01/2025

I work with docker : SearxNG - Ollama - OpenWebUI

1/ Installation Searxng : 

```
services:
  swag:
    container_name: searxng
    image: searxng/searxng
    ports:
      - 8080:8080
    volumes:
      - /volume1/docker/searx/:/etc/searxng
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    environment:
      - PUID=1000
      - PGID=1000
      - BASE_URL=https://searx.portail.domaine.fr
      - INSTANCE_NAME=NamelSearch
      - TZ=Europe/Paris
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE="searxng"
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL="https://searx.portail.domaine.fr/search?q=<query>"
```

i got two Environement variables : 

```
SEARXNG_HOSTNAME=https://searx.portail.domaine.fr/
SEARXNG_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

With that my searxNg works perfectly : 

![Image](https://github.com/user-attachments/assets/5d138534-74f0-474b-ad12-b08eca747ee8)

2/ now let's install ollama with docker : 

```

networks:
  net_ai:

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['net_ai']
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    #- ollama_storage:/root/.ollama
     - /volume1/docker/ollama/:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['net_ai']
  container_name: ollama-pull-llama
  volumes:
    #- ollama_storage:/root/.ollama
    - /volume1/docker/ollama/:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "sleep 3; OLLAMA_HOST=ollama:11434 ollama pull llama3.1; OLLAMA_HOST=ollama:11434 ollama pull nomic-embed-text"

services:
  flowise:
    image: flowiseai/flowise
    networks: ['net_ai']
    restart: unless-stopped
    container_name: flowise
    environment:
        - PORT=3002
    ports:
        - 3002:3002
    extra_hosts:
      - "host.docker.internal:host-gateway"        
    volumes:
        #- ~/.flowise:/root/.flowise
        - /volume1/docker/flowise:/root/.flowise        
    entrypoint: /bin/sh -c "sleep 3; flowise start"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    networks: ['net_ai']
    restart: unless-stopped
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=${OPENWEBUI_URL_OLLAMA}
      - WEBUI_SECRET_KEY=${OPENWEBUI_KEY}
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE="searxng"
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=${OPENWEBUI_URL}        
    ports:
      - "3001:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      #- open-webui:/volume1/docker/ollama-web/web-openui/data
      - /volume1/docker/open-webui/data:/volume1/docker/ollama-web/web-openui/data


  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    networks: ['net_ai']
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      #- qdrant_storage:/qdrant/storage
      - /volume1/docker/qdrant/storage:/qdrant/storage

  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu
```

this my .env files : 
```
# Change the name of this file to .env after updating it!


OPENWEBUI_URL='https://searx.portail.domaine.fr/search?q=<query>'
OPENWEBUI_KEY='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

OPENWEBUI_URL_OLLAMA='https://ollama.portail.domaine.fr/'

```

So my Ollama and OpenWEBUI Works perfect 

![Image](https://github.com/user-attachments/assets/63326d9c-aac2-45ec-9a4e-7ca880902170)

and my openWebui to

so now i will search with openWebui ollama and SearchNG

and i got this error  : 

![Image](https://github.com/user-attachments/assets/dc5d4c1b-800a-4141-84f5-eb0b04b6668e)

Do u know how debug this error please ? 

thanks
