### ISSUE TITLE
Deepseek r1 : answer loading infinitively

### ISSUE THREAD

**Issue by BenDes21** [open-webui/open-webui#8984]
<img width="934" alt="Image" src="https://github.com/user-attachments/assets/b8ae676b-88b0-40ce-8385-f55d66febcd0" />

<img width="934" alt="Image" src="https://github.com/user-attachments/assets/279545b0-7227-40f2-9846-8f4a0a277edb" />

Hi there, deepseek r1 is loading infinitively  even a restart of open web ui, I don't see any errors on the logs, what can be the solution ?

**Comment by emimix** [comment]
I'm getting the same issue (v0.5.7). It happens every time I try Deepseek R1...

**Comment by alexfisher** [comment]
Same issue for me.

**Comment by kbranvh** [comment]
same here latest 0.5.7

**Comment by kbranvh** [comment]
check this, seems to make sense.... 

https://github.com/open-webui/open-webui/discussions/9004

**Comment by emimix** [comment]
> check this, seems to make sense....
> 
> [#9004](https://github.com/open-webui/open-webui/discussions/9004)

I checked that, and it’s not related to my issue.

**Comment by Detrol** [comment]
I think the reason might be the DDOS attack on them.
https://status.deepseek.com/

**Comment by rikhuijzer** [comment]
@tjbck could you re-open this issue? I consistently have the same issue with WebUI 0.5.7 and DeepInfra's API. Occasionally DeepSeek R1 will complete, but 4 out of 5 times it will just hang. In the browser console, the error is "WebUI could not connect to Ollama". I have set `max_tokens` in the user interface to 80k, so that is not the problem. Answering hangs even while being well below that token limit. This is my configuration:

```yml
services:
  open-webui:
    container_name: 'open-webui'
    image: 'ghcr.io/open-webui/open-webui:main'
    volumes:
      - './open-webui:/app/backend/data:rw'
    ports:
      - '3003:8080'
    environment:
      ENABLE_SIGNUP: 'False'
      OPENAI_API_BASE_URLS: 'https://api.deepinfra.com/v1/openai'
    env_file:
      - 'OPENAI_API_KEYS.env'
      - 'WEBUI_SECRET_KEY.env'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'unless-stopped'
```
