### ISSUE TITLE
SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by dfengpo** [open-webui/open-webui#9503]
![Image](https://github.com/user-attachments/assets/04026b53-0ef8-44f5-9951-34e1883c67f1)

**Comment by lazarusdmx** [comment]
I am getting a similar JSON error:

![Image](https://github.com/user-attachments/assets/6b96732d-b127-4cb4-9562-320c6d813cd3)

I'm thinking something broke in the new update--it was working this morning, then I pulled the new update, and all models now deliver this error.  

there's no obvious errors in the ollama logs so far.

looking at my openwebui logs, it mostly looks fine.  the only thing seems to be messing up is this:
INFO:     <my ip> - "GET /ws/socket.io/?EIO=4&transport=websocket HTTP/1.1" 400 Bad Request

these started cropping up after I ran a web search enabled request which you can see above in the logs.

[INFO     192.168.50.190 - GET apiv1.txt](https://github.com/user-attachments/files/18690948/INFO.192.168.50.190.-.GET.apiv1.txt)

**Comment by ddowhy** [comment]
Same!!

![Image](https://github.com/user-attachments/assets/84a41cc1-509b-4d65-a148-57c1dad02b41)

**Comment by dfengpo** [comment]
Thank you for your reply. Could you please send out your nginx configuration

**Comment by dfengpo** [comment]
> I had to enable WebSocket support on my nginx proxy in order to get rid of the error message mentions above.

Thank you for your reply. Could you please send out your nginx configuration

**Comment by dfengpo** [comment]
> > I had to enable WebSocket support on my nginx proxy in order to get rid of the error message mentions above.
> 
> thanks! I just went into nginx proxy manager, and enabled websocket support on my open-webui proxy host, and 30 seconds later the issue was no longer showing up.

Thank you for your reply. Could you please send out your nginx configuration

**Comment by Anaphylaxis** [comment]
> > > I had to enable WebSocket support on my nginx proxy in order to get rid of the error message mentions above.
> > 
> > 
> > thanks! I just went into nginx proxy manager, and enabled websocket support on my open-webui proxy host, and 30 seconds later the issue was no longer showing up.
> 
> Thank you for your reply. Could you please send out your nginx configuration

https://nginx.org/en/docs/http/websocket.html

**Comment by PantelisDeveloping** [comment]
> > I had to enable WebSocket support on my nginx proxy in order to get rid of the error message mentions above.
> 
> Thank you for your reply. Could you please send out your nginx configuration

Using the below syntax fixed the issue for me (adapt it in your nginx configuration)

...
location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

**Comment by Mjmorell** [comment]
To add for a cluster with an nginx ingress, you can add the following to the ingress you set up for the open-webui web address:

Mainly, just add the annotation and match the name of the service used

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/websocket-services: ${name of service}
...
spec:
  ingressClassName: nginx
  rules:
    - host: $URL
      http: 
        paths:
          - backend:
              service:
                name: ${name of service}
                port:
                  number: 80
            path: /
            pathType: Prefix
```
